### ISSUE TITLE
"Bytecode stream version too low" during nqp build

### ISSUE THREAD

**Issue by robertlemmen** [MoarVM/MoarVM#1009]
hi folks,

2018.10 moar+nqp did build fine in the debian build system, but 2018.11 fail during nqp build on mips and s390x:

https://buildd.debian.org/status/fetch.php?pkg=nqp&arch=mips&ver=2018.11%2Bdfsg-1&stamp=1543690442&raw=0
https://buildd.debian.org/status/fetch.php?pkg=nqp&arch=s390x&ver=2018.11%2Bdfsg-1&stamp=1543693370&raw=0

note the "Bytecode stream version too low" 

please let me know if there is anything I can do to help debug this

**Comment by AlexDaniel** [comment]
Maybe bisecting it can help.

**Comment by lizmat** [comment]
Feels to me this is something related to the MAST work that @niner has done, so maybe he should be pinged?

**Comment by robertlemmen** [comment]
I can't give you access to a big-endian system, because they are not mine, but if you have tests to run then just let me know and I'll give them a spin!

**Comment by niner** [comment]
Fixed with MoarVM commits 652b2f4a7e0538e4a8ec82c586775b894711fdfa, 73b079c3756137491c967c0adc8ad3a5ea2ba785, b8ba4707c86f3874fb1081593701503f7ec2825e and 35ea958185e2068eb314388c1fd40e471591fd9d and nqp commit https://github.com/perl6/nqp/commit/176960303ff1aea1a982cad6540f2573f71fcacc
