### ISSUE TITLE
nqp::readnum appears to ignore size flag

### ISSUE THREAD

**Issue by lizmat** [MoarVM/MoarVM#1020]
$ perl6 -e 'use nqp; my $b := Buf.new(1,2,3,4); say nqp::readnum($b,0,8)'
    MVMArray: read_buf out of bounds offset 0 start 0 elems 4 count 8
      in block <unit> at -e line 1

This should read a 32bit num, but appears to attempt to read a 64bit num.  Giving it a bigger buffer appears to support this hypothesis:

    # 32 bit
    $ perl6 -e 'use nqp; my $b := Buf.new(1,2,3,4,5,6,7,8); say nqp::readnum($b,0,8)'
    5.784376957523072e+17

    # 64 bit
    $ perl6 -e 'use nqp; my $b := Buf.new(1,2,3,4,5,6,7,8); say nqp::readnum($b,0,12)'
    5.784376957523072e+17

**Comment by jnthn** [comment]
Fixed this, and there are tests in https://github.com/perl6/roast/commit/77da1465dd.
