### ISSUE TITLE
JIT of nativecall int32 return value fails to extend sign

### ISSUE THREAD

**Issue by dmaestro** [MoarVM/MoarVM#1028]
Possibly related to [Issue #763](https://github.com/MoarVM/MoarVM/issues/763) , but applies to both Linux / MacOS platforms.

When calling a nativecall C routine that returns a int32 value of -1, a second call will produce 4294967295. Using MVM_JIT_DISABLE prevents the error in testing.

I've built a Makefile and test code to reproduce this bug: [nativecall-testlib
](https://github.com/dmaestro/nativecall-testlib)

@niner I modified the tentative patch you supplied to apply and compile properly with (at least) 2018.08 thru 2018.12. I was able to prove that the patched code was executed, but it did not fix this problem.

**Comment by dmaestro** [comment]
Still an issue with MoarVM 2019.03 / Rakudo 2019.03.1 -
```
dmaestro:~/nativecall-testlib$ make clean
rm -vf int32.o int64.o int_ssize.o libints.so sizes
dmaestro:~/nativecall-testlib$ make
cc -Wall -O2 -fPIC   -c -o int32.o int32.c
cc -Wall -O2 -fPIC   -c -o int64.o int64.c
cc -Wall -O2 -fPIC   -c -o int_ssize.o int_ssize.c
cc -Wall -O2 -fPIC -shared int32.o int64.o int_ssize.o -o libints.so
cc -Wall -O2 -fPIC    sizes.c   -o sizes
dmaestro:~/nativecall-testlib$ LD_LIBRARY_PATH=. perl6 decr_zero.pl6 
-1
4294967295
-1
-1
-1
-1
```

**Comment by niner** [comment]
This is fixed by https://github.com/MoarVM/MoarVM/commit/97615be0adab68fad5ab5fe89246647c989778d3

The supplied test case fails before the commit and passes after the commit on my system.
Thanks for the excellent test case!
