### ISSUE TITLE
libtommath v1.1.0 now available

### ISSUE THREAD

**Issue by MasterDuke17** [MoarVM/MoarVM#1056]
https://github.com/libtom/libtommath/tree/v1.1.0

I pulled it into 3rdparty/libtommath and nqp built ok and passed `make m-test` and rakudo built ok and passed `make m-test m-spectest`.

**Comment by MasterDuke17** [comment]
@timo I don't remember how to "officially" update a submodule. Is what I mentioned above correct?

**Comment by minad** [comment]
1.2 is now in preparation, https://www.libtom.net/news/LTM_1.2.0RC1/

**Comment by dogbert17** [comment]
Given that we're using 1.2.0 now, perhaps this issue should be closed.

**Comment by jnthn** [comment]
Yes, I think so.
