### ISSUE TITLE
Odd slowdown when opening a gzip with Compress::Zlib caused by sim_stack_find

### ISSUE THREAD

**Issue by MasterDuke17** [MoarVM/MoarVM#1060]
This is the code: `use Compress::Zlib; my $a = gzslurp("/home/dan/p6/100k.txt.gz"); say $a.lines.elems`. The file I'm using is in this gist: https://gist.github.com/MasterDuke17/5b5751301594ff1774deec55133cc65f, it's a 2mb gz file that decompresses to 6mb. Also in the gist are some metrics about values for `found_at` and `pop` in `sim_stack_find` when running the example.

A perf report of the above example shows `sim_stack_find` as the top function at 45% (next at 7% is `MVM_interp_run`). Sometime it only takes ~9s, but sometimes ~14s.

**Comment by jnthn** [comment]
With the fix, now runs in around 1.6s on my machine, while it could be 2.4s before. Verified that `sim_stack_find` no longer shows up anywhere near the top in `perf`.
