### ISSUE TITLE
Synthetic code point checking off ?

### ISSUE THREAD

**Issue by lizmat** [MoarVM/MoarVM#1115]
$ perl6 -e "\xd83cdded"
    MoarVM oops: MVM_nfg_get_synthetic_info call requested a synthetic codepoint that does not exist.
    Requested synthetic 667099667 when only 6 have been created.
       at src/Perl6/World.nqp:2934       (install/share/perl6/lib/Perl6/World.moarvm:add_constant)
    from src/Perl6/World.nqp:3014     (install/share/perl6/lib/Perl6/World.moarvm:add_string_constant)
     from gen/moar/Perl6-Actions.nqp:10602  (install/share/perl6/lib/Perl6/Actions.moarvm:nibbler)

**Comment by lizmat** [comment]
Alternately, with one character less at the end:

    $ perl6 -e '"\xd83cdde"'
    WARNINGS for -e:
    ===SORRY!===
    Error encoding UTF-8 string: could not encode codepoint 226741726 (0xD83CDDE), codepoint out of bounds. Cannot encode higher than 1114111 (0x10FFFF)

**Comment by Altai-man** [comment]
A test needed?

**Comment by jnthn** [comment]
I unfudged a todo'd spectest in https://github.com/Raku/roast/commit/c7725addae78c20acb2d0b16c44b2c09fa01757a at least.

**Comment by lizmat** [comment]
Which is why I bumped MoarVM last night, because the test was failing  :-)
