### ISSUE TITLE
REPL with ARGV

### ISSUE THREAD

**Issue by cup** [MoarVM/MoarVM#1144]
Python allows you to pass ARGV in interactive mode:

~~~
$ python3 - aa
>>> import sys
>>> sys.argv[1]
'aa'
~~~

~~~
$ python3 -- - aa
>>> import sys
>>> sys.argv[1]
'aa'
~~~

~~~
$ python3 -i - aa
>>> import sys
>>> sys.argv[1]
'aa'
~~~

as does PHP:

~~~
$ php -a -- aa
php > echo $argv[1];
aa
~~~

However Perl 6 seems to have no way to do this. These all hang:

~~~
perl6 - aa
~~~

~~~
perl6 -- - aa
~~~

~~~
perl6 --repl-mode=interactive - aa
~~~

and this errors out:

~~~
$ perl6 --repl-mode=interactive -- aa
Could not open aa. Failed to stat file: no such file or directory
~~~

**Comment by lizmat** [comment]
Don't think this is the right repo for this.  Could you please make at https://github.com/rakudo/rakudo/issues/new ?

**Comment by lizmat** [comment]
FWIW, maybe a `--repl` parameter would be handy to force the REPL?

**Comment by cup** [comment]
https://github.com/rakudo/rakudo/issues/3050
