### ISSUE TITLE
.gitmodules doesn't point to specific commits

### ISSUE THREAD

**Issue by chloekek** [MoarVM/MoarVM#1156]
This means that it's difficult to checkout old versions and build them, because you need to somehow know which corresponding commit to use for the dependencies.

**Comment by chloekek** [comment]
Nevermind, commit hashes are stored in the tree objects.

**Comment by AlexDaniel** [comment]
Actually, that seems to be a common misunderstanding. I wonder if we should doc it somehow, or something…
