### ISSUE TITLE
Segfault after repeated callframe access

### ISSUE THREAD

**Issue by hoelzro** [MoarVM/MoarVM#120]
This file (built with Rakudo = fd2b197, MoarVM = 0513b67) results in Moar trying to access a NULL string:

```perl6
use v6;
 
sub proclaim($cond) {
    unless $cond { # for some reason, commenting this out fixes things?
        my $caller = callframe(2);
        say $caller.annotations.keys;
        say($caller.file);
    }
}
 
for (1 .. 20) {
    .say;
    proclaim(0);
}
```

Output:

```
1                                                    
file line
segfault.pl
2
file line
segfault.pl
3
file line
segfault.pl
4
file line
segfault.pl
5
file line
segfault.pl
6
file line
segfault.pl
7
file line
segfault.pl
8
file line
segfault.pl
9
file line
segfault.pl
10
file line
Failed to write to filehandle: NULL string given
  in method print at src/gen/m-CORE.setting:14088
  in sub say at src/gen/m-CORE.setting:13825
  in sub proclaim at segfault.pl:7
  in block  at segfault.pl:11
```

I did a little digging, and I noticed that a GC happens shortly before the crash.

**Comment by usev6** [comment]
I run the above program today and got no segfault

$ perl6 --version
This is perl6 version 2015.03-130-gdb9bd81 built on MoarVM version 2015.03-23-g3819ea7

But if I increase the number of iterations in the for loop to 150 or above, there is a segfault at iteration 150.

It seems to be related to spesh, since the segfault doesn't occur with MVM_SPESH_DISABLE=1 (tested with 100000 iterations).

**Comment by zhuomingliang** [comment]
Hello, hoelzro.
I can't see the bug now, can you confirm it?

**Comment by hoelzro** [comment]
@zhuomingliang Looks good!

**Comment by zhuomingliang** [comment]
Hmm, it still doesn't work by change ```for (1 .. 20) {``` to ```for (1 .. 200) {```

**Comment by timo** [comment]
This code still breaks, but now it doesn't segfault any more. it's still quite probable that it's spesh-related.

**Comment by usev6** [comment]
BTW, I think this is the same problem (no sub needed, but using 'next'):

```
perl6-m -e 'for ^200 { next if $_ < 199; say callframe }'
concatenate requires a concrete string, but got null
  in block <unit> at -e:1
```

It works with less than 200 iterations or with MVM_SPESH_DISABLE=1

**Comment by jnthn** [comment]
No longer explodes after 715e39a. Added a spectest to roast to cover it.
