### ISSUE TITLE
MoarVM broken on windows

### ISSUE THREAD

**Issue by ugexe** [MoarVM/MoarVM#1200]
In https://github.com/MoarVM/MoarVM/commit/c61236f96ec6952e7c0a2f58e35c1a5b9db2b189 the following is now inside an `MVMROOT`
https://github.com/MoarVM/MoarVM/blob/c61236f96ec6952e7c0a2f58e35c1a5b9db2b189/src/spesh/plugin.c#L340-L344

This breaks windows in the following way -- https://ci.appveyor.com/project/samcv/moarvm-35u74/builds/28238735/job/ckp9y0ugrva7i42n#L368

**Comment by niner** [comment]
Does commit 0f0e6d3a27c03c6d2761e76351d56c92db80c70c fix compilation?

**Comment by ugexe** [comment]
https://ci.appveyor.com/project/samcv/moarvm-35u74/builds/28243518 shows that it is fixed in that commit
