### ISSUE TITLE
Valgrind errors when running t/spec/S32-str/encode.t

### ISSUE THREAD

**Issue by dogbert17** [MoarVM/MoarVM#1208]
I ran this with a small nursery, 32k, and MVM_GC_DEBUG=1 but I suspect that won't matter.

    dogbert@dogbert-VirtualBox ~/repos/rakudo $ ./perl6-m -v
    This is Rakudo version 2019.07.1-441-gb45d99d built on MoarVM version 2019.07.1-298 g67b6acf implementing Perl 6.d.
    dogbert@dogbert-VirtualBox ~/repos/rakudo $ ./perl6-valgrind-m -Ilib t/spec/S32-str/encode.rakudo.moar
    ================================================================================================
    This is Rakudo Perl 6 running in valgrind, a tool for debugging and profiling programs.
    Running a program in valgrind usually takes *a lot* more time than running it directly,
    so please be patient.
    Valgrind options can be added with MVM_VALGRIND_OPTS environment variable.
    
    This Rakudo version is 2019.07.1.441.gb.45.d.99.d built on MoarVM version 2019.07.1.298.g.67.b.6.acf,
    running on linuxmint (18.3.Sylvia) / linux (42.16.04.1.Ubuntu.SMP.Tue.Oct.10.16.32.20.UTC.2017)
    ------------------------------------------------------------------------------------------------
    ==23660== Memcheck, a memory error detector
    ==23660== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
    ==23660== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
    ==23660== Command: /home/dogbert/repos/rakudo/nqp/MoarVM/../../install/bin/moar --execname=/home/dogbert/repos/rakudo/perl6-valgrind-m --libpath=/home/dogbert/repos/rakudo --libpath=/home/dogbert/repos/rakudo/blib --libpath= --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib /home/dogbert/repos/rakudo/perl6.moarvm --nqp-lib=/home/dogbert/repos/rakudo/blib -Ilib t/spec/S32-str/encode.rakudo.moar
    ==23660== 
    --23660-- WARNING: unhandled amd64-linux syscall: 332
    --23660-- You may be able to write your own handler.
    --23660-- Read the file README_MISSING_SYSCALL_OR_IOCTL.
    --23660-- Nevertheless we consider this a bug.  Please report
    --23660-- it at http://valgrind.org/support/bug_reports.html.
    1..41
    ok 1 - $str.encode returns a blob8
    ok 2 - encoding to ASCII
    ok 3 - right length of Buf
    ok 4 - encoding to UTF-8
    ok 5 - right length of Buf
    ok 6 - right length of Buf with \n
    ok 7 - Non-translation of \n outside Windows
    ok 8 - indexing a utf8 gives correct value (1)
    ok 9 - indexing a utf8 gives correct value (1)
    ok 10 - cp1252 encodes most C1 substitutes
    ok 11 - cp1252 encode tolerates unassigned C1 characters
        1..3
    ==23660== Invalid read of size 1
    ==23660==    at 0x5187E71: MVM_string_utf8_decode (utf8.c:242)
    ==23660==    by 0x5188300: MVM_string_utf8_decode_strip_bom (utf8.c:320)
    ==23660==    by 0x5193DFA: MVM_string_decode_config (ops.c:1684)
    ==23660==    by 0x5194764: MVM_string_decode_from_buf_config (ops.c:1845)
    ==23660==    by 0x5053059: MVM_interp_run (interp.c:5380)
    ==23660==    by 0x51EA680: MVM_vm_run_file (moar.c:461)
    ==23660==    by 0x4016E6: main (main.c:303)
    ==23660==  Address 0xe35f637 is 0 bytes after a block of size 7 alloc'd
    ==23660==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
    ==23660==    by 0x51A403E: MVM_malloc (alloc.h:2)
    ==23660==    by 0x51A4D96: MVM_string_latin1_encode_substr (latin1.c:161)
    ==23660==    by 0x51940E0: MVM_string_encode_config (ops.c:1732)
    ==23660==    by 0x5194519: MVM_string_encode_to_buf_config (ops.c:1797)
    ==23660==    by 0x5052E52: MVM_interp_run (interp.c:5370)
    ==23660==    by 0x51EA680: MVM_vm_run_file (moar.c:461)
    ==23660==    by 0x4016E6: main (main.c:303)
    ==23660== 
    ==23660== Invalid read of size 1
    ==23660==    at 0x5187E88: MVM_string_utf8_decode (utf8.c:242)
    ==23660==    by 0x5188300: MVM_string_utf8_decode_strip_bom (utf8.c:320)
    ==23660==    by 0x5193DFA: MVM_string_decode_config (ops.c:1684)
    ==23660==    by 0x5194764: MVM_string_decode_from_buf_config (ops.c:1845)
    ==23660==    by 0x5053059: MVM_interp_run (interp.c:5380)
    ==23660==    by 0x51EA680: MVM_vm_run_file (moar.c:461)
    ==23660==    by 0x4016E6: main (main.c:303)
    ==23660==  Address 0xe35f638 is 1 bytes after a block of size 7 alloc'd
    ==23660==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
    ==23660==    by 0x51A403E: MVM_malloc (alloc.h:2)
    ==23660==    by 0x51A4D96: MVM_string_latin1_encode_substr (latin1.c:161)
    ==23660==    by 0x51940E0: MVM_string_encode_config (ops.c:1732)
    ==23660==    by 0x5194519: MVM_string_encode_to_buf_config (ops.c:1797)
    ==23660==    by 0x5052E52: MVM_interp_run (interp.c:5370)
    ==23660==    by 0x51EA680: MVM_vm_run_file (moar.c:461)
    ==23660==    by 0x4016E6: main (main.c:303)
    ==23660== 
        ok 1 - '"aouÄÖÜ".encode("latin1").decode("utf8")' died
        ok 2 - right exception type (Exception)
        ok 3 - .message matches rx:s:i/line 1 col\w* 4/
    ...

**Comment by AlexDaniel** [comment]
@dogbert17 so, is this new?

**Comment by dogbert17** [comment]
It's newer than release 2019.07.1 yes.
