### ISSUE TITLE
src/core/interp.c: 3 * bad tests ?

### ISSUE THREAD

**Issue by dcb314** [MoarVM/MoarVM#1215]
src/core/interp.c:6213:41: warning: logical 'or' of collectively exhaustive tests is always true [-Wlogical-op]

Source code is

                    MVMuint64 result = (MVMint64)ba->u.smallint.value + (MVMint64)bb->u.smallint.value;
                    if (MVM_IS_32BIT_INT(result)) {
                        if (result < -1 || result >= 15) {

It looks to me like the unsigned result compared to -1 is the problem.

src/core/interp.c:6244:41: warning: logical 'or' of collectively exhaustive tests is always true [-Wlogical-op]
src/core/interp.c:6275:41: warning: logical 'or' of collectively exhaustive tests is always true [-Wlogical-op]

Duplicates.

**Comment by niner** [comment]
Fixed in https://github.com/MoarVM/MoarVM/commit/163da25a86b7a06d5edcbeb9b7638e25d875016d
