### ISSUE TITLE
Expression JIT maybe missing GC check at backbranch

### ISSUE THREAD

**Issue by jnthn** [MoarVM/MoarVM#1230]
This works:

```
$ MVM_JIT_EXPR_DISABLE=1 perl6 -e 'Supply.interval(1).tap: { say  $^a }; loop {}'
0
1
2
3
4
5
```

Enable the expression JIT and it hangs after `2`. I'm guessing that it's not emitting the GC status check. Also, looking at the lego JIT, I see it unconditionally emits the GC status check - which is obviously much better than forgetting it, but it is only really needed on a back branch, so we're emitting several more instructions than we need per non-loop branch, which is probably a nice easy speedup.

**Comment by bdw** [comment]
Yes, the expression JIT is skipping those. (How would that lead to this issue, though?)

**Comment by jnthn** [comment]
@bdw The main thread is sat in a tight loop (actually a single machine code instruction - a jump to itself!). The other thread is allocating, and needs GC to happen. That depends on the main thread joining, but it never will because the expression JIT doesn't insert the GC check at the loop back branch.

**Comment by bdw** [comment]
Is there something going wrong in the jump-to-self code generation?

**Comment by jnthn** [comment]
@bdw Well, yes; it should emit a back branch as a GC sync check plus the back branch. There's one of two things wrong:

1. It's not emitting the GC sync check at all.
2. It's emitting it, but then the back branch is to the branch instruction itself.

I suspect it's 1, which is the more mundane problem.

**Comment by bdw** [comment]
I'm fairly sure it is 1, no question there.
I will somehow need to keep track of the emitted branches, just so we can know what is a back branch - we don't always order them nicely.
But a branch-to-itself - without any intermediate code - that would be fairly bad, for sure, almost certainly a codegen bug.
Will investigate.

**Comment by jnthn** [comment]
> But a branch-to-itself - without any intermediate code - that would be fairly bad, for sure, almost certainly a codegen bug.

Well, the code in question was `loop { }`, so in a sense the branch to itself is a perfect compilation - except that it breaks the GC contract. :)

**Comment by lizmat** [comment]
Now that the expression JIT has been disabled by default because of other issues, this can be closed as well
