### ISSUE TITLE
Various issues when gcc-10 is used on macOS

### ISSUE THREAD

**Issue by romario89** [MoarVM/MoarVM#1234]
The original title was **Error: string.h no such file when gcc-10 is used** Because further issues came up when gcc is used, the title is updated accordingly.

Steps to reproduce:

1- macOS 10.10.5 (Yosemite) with gcc-10 installed in /usr/local/gcc-10.0.0 and environment variable GCC set to it and its binary directory added to path.

2- **rakudo-2019.11** is configured with `perl Configure.pl --prefix=/usr/local/raku-2019.11 --backends=moar --gen-moar --moar-option='--compiler=gcc'`

3- The lines 200-212 commented out in `rakudo-2019.11/nqp/MoarVM/Configure.pl` to dismiss the *GNU Tools Detected* configure error

4- It compiles all files up to the ones at `rakudo-2019.11/nqp/MoarVM/src/jit/x64` namely `emit.c` and `arch.c` But as it tried to build the so-called *dyncall* it said:
```
dyncall_vector.c:29:10: fatal error: string.h: No such file or directory
   29 | #include <string.h>
      |          ^~~~~~~~~~
```

The error causing file '**string.h**' is available under `/usr/include`. I'm trying to find out why the Makefile can't find it there.

I've built some popular packages like **perl-5.22**, **nginx-1.17.x**, **openssl-1.1.x** using this gcc version and they are all built perfectly fine. So I reckon this gcc should be able to build the raku-2019.11 too.

On another macOS (OS X 10.7.5) I had built **rakudo-star-2019.03** (by nullifying the GNU Tools Detect lines) using gcc-5.0 and the resulting rakudo compiler works perfectly fine on it. So I guess any version of  GCC is suitable for building any version of rakudo on macOS.

I've tinkered with several environment variables and set **CFLAGS**to `-I/usr/include` , etc. The error persists. 

here is the complete log (trivial parts truncated)
```
tommys-Mac-mini:rakudo-2019.11 tommy$ perl Configure.pl --prefix=/usr/local/raku-2019.11 --backends=moar --gen-moar --moar-option='--compiler=gcc'
No pre-existing installed file found at /usr/local/raku-2019.11/bin/nqp-m
HEAD is now at 3e05931... [release] Bump VERSION to 2019.11
Building NQP ...
perl Configure.pl --prefix=/usr/local/raku-2019.11 --make-install --git-protocol=https --no-relocatable --no-ignore-errors --silent-build --backends=moar --gen-moar --moar-option=--compiler=gcc
M	Configure.pl
HEAD is now at 3a212c9... Update VERSION for release

Configuring and building MoarVM ...
perl Configure.pl --compiler=gcc --optimize --prefix=/usr/local/raku-2019.11 --make-install
Welcome to MoarVM!

Updating submodules .................................... OK
Configuring native build environment ...................
Binary file /usr/local/gcc-10.0.0/bin/gcc matches
Binary file /usr/local/gcc-10.0.0/bin/gcc matches
    trying to compile a simple C program ............... YES
    probing support of -Werror=* ....................... YES
did not find libzstd; will not use heap snapshot format version 3
OK

    probing whether your compiler thinks that it is gcc  YES
    probing how your compiler does static inline ....... static __inline__
    your CPU can read unaligned values for all of int32 int64 num64
    probing the size of pointers ....................... 8
    probing C type support for: _Bool, bool ............ YES: _Bool,bool
    probing computed goto support ...................... YES
    probing pthread_yield support ...................... NO
    probing existance of optional malloc_trim() ........ NO
    probing support of rdtscp intrinsic ................ NO

        make: /usr/bin/make
     compile: gcc -Werror=declaration-after-statement -Werror=pointer-arith -O3 -DNDEBUG  -D_DARWIN_USE_64_BIT_INODE=1 -fPIC -DMVM_HEAPSNAPSHOT_FORMAT=2 -I/usr/include
    includes:   -I3rdparty/libuv/include -I3rdparty/libuv/src -I3rdparty/libatomicops/src -I3rdparty/libtommath -I3rdparty/dyncall/dynload -I3rdparty/dyncall/dyncall -I3rdparty/dyncall/dyncallback
        link: gcc  -O3 -DNDEBUG -Wl,-rpath,"/@libdir@"
        libs:  -lpthread

  byte order: little endian

Configuring 3rdparty libs .............................. OK

  3rdparty: 3rdparty/cmp/libcmp.a
            3rdparty/dyncall/dyncall/libdyncall_s.a
            3rdparty/dyncall/dyncallback/libdyncallback_s.a
            3rdparty/dyncall/dynload/libdynload_s.a
            3rdparty/libatomicops/src/libatomic_ops.a
            3rdparty/libtommath/libtommath.a
            3rdparty/libuv/libuv.a
            3rdparty/sha1/libsha1.a
            3rdparty/tinymt/libtinymt.a

Generating src/gen/config.c ............................ OK
Generating src/gen/config.h ............................ OK
Generating Makefile .................................... OK
Generating tools/check.mk .............................. OK
Generating build/mk-moar-pc.pl ......................... OK

Configuration SUCCESS.

Type '/usr/bin/make' to build and '/usr/bin/make help' to see a list of
available make targets.
compiling src/main.o
compiling src/core/callsite.o
compiling src/core/args.o
<truncated>
compiling src/jit/tile.o
compiling src/jit/linear_scan.o
compiling src/jit/interface.o
gcc  3rdparty/dynasm/minilua.c -lm -o 3rdparty/dynasm/minilua
preprocessing src/jit/x64/emit.dasc
compiling src/jit/x64/emit.o
compiling src/jit/x64/arch.o
compiling 3rdparty/cmp/cmp.o
linking 3rdparty/cmp/libcmp.a
building dyncall...
Configuration written to Makefile.config
dyncall_vector.c:29:10: fatal error: string.h: No such file or directory
   29 | #include <string.h>
      |          ^~~~~~~~~~
compilation terminated.
make[2]: *** [dyncall_vector.o] Error 1
make[1]: *** [libdyncall] Error 2
make: *** [3rdparty/dyncall/dyncall/libdyncall_s.a] Error 2
```

**Comment by romario89** [comment]
To help identify the problem, I have tried to build **rakudo-2020.01** on **OS X 10.5.8** on which gcc-4.6 is installed. I have used exactly the same configure options as above and the build stopped at the same step as above i.e. during building **dyncall** but with different type of errors. Here they are (trivial parts truncated)

```
building dyncall...
Configuration written to Makefile.config
gcc: error: i386: No such file or directory
gcc: error: x86_64: No such file or directory
gcc: error: ppc: No such file or directory
gcc: error: unrecognized option '-arch'
gcc: error: unrecognized option '-arch'
gcc: error: unrecognized option '-arch'
make[2]: *** [dyncall_vector.o] Error 1
make[1]: *** [libdyncall] Error 2
make: *** [3rdparty/dyncall/dyncall/libdyncall_s.a] Error 2
```

**Comment by romario89** [comment]
When I checked the contents of the `<src-dir>/nqp/MoarVM/3rdparty/dyncall/Makefile.config`
```
# auto-generated by ./configure
PREFIX=/usr/local
AR=libtool
ARFLAGS=-static -o
CFLAGS=-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk.sdk
CXXFLAGS=-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk.sdk
```

I've noticed that CFLAGS was formed by duplicating the XCode'S SDK path. The SDK was defined in my `~/.bash_profile` . I 've changed the name *SDK* to something else and that **string.h no such file** error is gone. But the trouble continues. This time it complained about 'permission denied' error like this:

```

compiling 3rdparty/libuv/src/unix/thread.o
compiling 3rdparty/libuv/src/threadpool.o
compiling 3rdparty/libuv/src/unix/tty.o
compiling 3rdparty/libuv/src/unix/udp.o
linking 3rdparty/libuv/libuv.a
linking libmoar.so
linking moar
perl build/mk-moar-pc.pl pkgconfig/moar.pc
perl -MExtUtils::Command -e mkpath "/usr/local/raku-2019.11/bin"
mkdir /usr/local/raku-2019.11: Permission denied at /System/Library/Perl/5.18/ExtUtils/Command.pm line 288.
make: *** [install] Error 13
Command failed (status 512): perl Configure.pl --compiler=gcc --optimize --prefix=/usr/local/raku-2019.11 --make-install
 at /Users/tommy/Downloads/rakudo-2019.11/nqp/3rdparty/nqp-configure/lib/NQP/Config.pm line 35.
```
I've given sudo permission and again ended up with an error (upper sections truncated):

```
perl -MExtUtils::Command -e cp 3rdparty/dyncall/dyncall/*.h "/usr/local/raku-2019.11/include/dyncall"
perl -MExtUtils::Command -e cp 3rdparty/dyncall/dyncallback/*.h "/usr/local/raku-2019.11/include/dyncall"
dyld: Library not loaded: libmoar.so
  Referenced from: /usr/local/raku-2019.11/bin/moar
  Reason: image not found
Use of uninitialized value in quotemeta at /Users/tommy/Downloads/rakudo-2019.11/nqp/tools/lib/NQP/Config/NQP.pm line 125.
Use of uninitialized value in substitution (s///) at /Users/tommy/Downloads/rakudo-2019.11/nqp/tools/lib/NQP/Config/NQP.pm line 125.
Use of uninitialized value in substitution (s///) at /Users/tommy/Downloads/rakudo-2019.11/nqp/tools/lib/NQP/Config/NQP.pm line 125.
Use of uninitialized value in quotemeta at /Users/tommy/Downloads/rakudo-2019.11/nqp/tools/lib/NQP/Config/NQP.pm line 126.
Use of uninitialized value in concatenation (.) or string at /Users/tommy/Downloads/rakudo-2019.11/nqp/tools/lib/NQP/Config/NQP.pm line 128.
Use of uninitialized value in sprintf at /Users/tommy/Downloads/rakudo-2019.11/nqp/tools/lib/NQP/Config/NQP.pm line 152.
Cleaning up ...
+++ Preparing MOAR build directories
++++++ BUILDING MOAR BACKEND
++++++ STAGE1 ++++++
+++ Generating	gen/moar/stage1/nqpmo.nqp
+++ Compiling	gen/moar/stage1/nqpmo.moarvm
dyld: Library not loaded: libmoar.so
  Referenced from: /usr/local/raku-2019.11/bin/moar
  Reason: image not found
make: *** [gen/moar/stage1/nqpmo.moarvm] Trace/BPT trap: 5
Command failed (status 512): make
 at /Users/tommy/Downloads/rakudo-2019.11/nqp/3rdparty/nqp-configure/lib/NQP/Config.pm line 35.
```
Notice the **libmoar.so** which is the Linux's Shared Object file so it's no surprise that it says `dyld: Library not loaded: libmoar.so` and `Reason: image not found`. That **.so** file must have been a **.dylib** file.

**Comment by romario89** [comment]
Here are the `<src-dir>/MoarVM/3rdparty/dyncall/Makefile.config` files from both Macs.

This one's from the successful build on Mac OS X 10.7.5 where the libmoar.**dylib** is formed correctly
```
PREFIX=/usr/local
AR=ar
ARFLAGS=rs
ASFLAGS=-arch x86_64 -arch i386
CFLAGS=-arch x86_64 -arch i386
CXXFLAGS=-arch x86_64 -arch i386
```
This one's from the build on macOS 10.10.5, where libmoar.**so** is formed instead of libmoar.**dylib*

```
# auto-generated by ./configure
PREFIX=/usr/local
AR=libtool
ARFLAGS=-static -o
ASFLAGS=-arch x86_64 -arch i386
CFLAGS=-arch x86_64 -arch i386
CXXFLAGS=-arch x86_64 -arch i386
```
The differing lines are seen cearly.

**Comment by niner** [comment]
According to a comment in dyncall's configure script, Apple ships a libtool that's different from GNU's libtool. Apple's supports a `-V` command line option that GNU's doesn't and this is used to differ between them.
Can you check if the libtool it uses for building is indeed Apple's? It should fall back to `ar` if `-V` is not supported.

**Comment by romario89** [comment]
Thank you for the comment. On this Mac with macOS 10.10.5 no GNU libtool was installed so the Configure.pl is bound to use the Apple's libtool, i.e. wrongly producing libmoar.so instead of libmoar.dylib has happened using the Apple's libtool. But. On the other Mac with macOS 10.7.5 (on which libmoar.dylib was produced correctly), the GNU libtool was installed and Configure.pl was using it. That's why the 2 lines at `<src-dir>/MoarVM/3rdparty/dyncall/Makefile.config` were different. I have installed GNU libtool on this Mac and tried with it and the 2 lines at Makefile.config became the same as in the Mac with macOS 10.7.5 but the problem persisted. To isolate the effect of 'nqp' and 'rakudo', I have tried installing just the MoarVM-2020.01.1 using :

`perl Configure.pl --prefix=/usr/local/moarvm-2010.01.1 --compiler=gcc`
then I got:
```
linking libmoar.so
duplicate symbol _cmp_tc in:
    src/6model/reprs/MVMHash.o
    src/6model/serialization.o
ld: 1 duplicate symbol for architecture x86_64
collect2: error: ld returned 1 exit status
```

**Comment by jnthn** [comment]
> duplicate symbol _cmp_tc in:
>    src/6model/reprs/MVMHash.o
>    src/6model/serialization.o

Please try with 978480b288, which should resolve this particular problem.

**Comment by romario89** [comment]
After I applied that minor patch, MoarVM got built (using GCC) Actually, I think I solved the whole issue by downloading and installing each package **MoarVM-2020.01.1.tar.gz** (5.7MB), **nqp-2020.01.tar.gz** (3.9MB), **rakudo-2020.01.tar.gz** (4.7MB) separately. That is, by not letting the rakudo installer download and install the MoarVM and nqp. 

Here is how I configured each of packages (in their respective folders)

`perl Configure.pl --prefix=/usr/local/moarvm-gcc-2020.01.1 --compiler=gcc`

`CC=$GCC perl Configure.pl --prefix=/usr/local/nqp-gcc-2020.01 --backends=moar --with-moar=/usr/local/moarvm-gcc-2010.01.1/bin/moar`

`CC=$GCC perl Configure.pl --prefix=/usr/local/raku-gcc-2020.01 --backends=moar --with-nqp=/usr/local/nqp-gcc-2020.01/bin/nqp`

where GCC=/usr/local/gcc-10.0.0

If it is installed this way, then things go smoothly even with the GCC. 

Because I have managed to install **rakudo-2020.01**  using the configure scripts above and using **GCC** on macOS 10.10.5, I close the issue.
