### ISSUE TITLE
Failure when running S05-grammar/parse_and_parsefile-6e.t under MVM_SPESH_BLOCKING and MVM_SPESH_NODELAY

### ISSUE THREAD

**Issue by dogbert17** [MoarVM/MoarVM#1242]
It looks like this: 

    dogbert@dogbert-ubuntu:~/repos/rakudo$ ./perl6-m -v
    This is Rakudo version 2020.01-238-g58e8fb150 built on MoarVM version 2020.01.1-39-g657b536cf
    implementing Raku 6.d.
    dogbert@dogbert-ubuntu:~/repos/rakudo$ MVM_SPESH_BLOCKING=1 MVM_SPESH_NODELAY=1 ./perl6-m --ll-exception -Ilib t/spec/S05-grammar/parse_and_parsefile-6e.t
    1..24
    ok 1 - grammar is created using 6.e version of Grammar class
    ok 2 - .parse method invokes TOP rule, no match
    ok 3 - .parse method invokes TOP rule, match
    ok 4 - .parse method requires match to end
    ok 5 - .subparse method doesn't require match to end
    ok 6 - dies if no TOP rule
    ok 7 - .parsefile method invokes TOP rule, no match
    ok 8 - .parsefile method invokes TOP rule, match
    ok 9 - dies if no TOP rule
    ok 10 - dies if file not found
    ok 11 - .parse works with namespaced grammars, no match
    ok 12 - .parse works with namespaced grammars, match
      1..2
      ok 1 - '::No::Such::Grammar.parse()' died
      ok 2 - right exception type (Exception)
    ok 13 - .parse on missing grammar dies
    ok 14 - can .parse grammar named "Integer"
    Unexpected named argument 'cache' passed
     at gen/moar/stage2/NQPHLL.nqp:2463  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:lineof)
     from SETTING::src/core.e/Grammar.pm6:44  (/home/dogbert/repos/rakudo/blib/CORE.e.setting.moarvm:typed_exception)
     from SETTING::src/core.e/Grammar.pm6:57  (/home/dogbert/repos/rakudo/blib/CORE.e.setting.moarvm:SETFAIL)
     from SETTING::src/core.e/Grammar.pm6:62  (/home/dogbert/repos/rakudo/blib/CORE.e.setting.moarvm:parse)
     from t/spec/S05-grammar/parse_and_parsefile-6e.t:65  (<ephemeral file>:)
     from t/spec/S05-grammar/parse_and_parsefile-6e.t:48  (<ephemeral file>:<unit>)
     from t/spec/S05-grammar/parse_and_parsefile-6e.t:1  (<ephemeral file>:<unit-outer>)
     from gen/moar/stage2/NQPHLL.nqp:1913  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:eval)
     from gen/moar/stage2/NQPHLL.nqp:2118  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:evalfiles)
     from gen/moar/stage2/NQPHLL.nqp:2078  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
     from gen/moar/Compiler.nqp:55  (/home/dogbert/repos/rakudo/blib/Perl6/Compiler.moarvm:command_eval)
     from gen/moar/stage2/NQPHLL.nqp:2003  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:command_line)
     from gen/moar/rakudo.nqp:127  (/home/dogbert/repos/rakudo/perl6.moarvm:MAIN)
     from gen/moar/rakudo.nqp:92  (/home/dogbert/repos/rakudo/perl6.moarvm:<mainline>)
     from <unknown>:1  (/home/dogbert/repos/rakudo/perl6.moarvm:<main>)
     from <unknown>:1  (/home/dogbert/repos/rakudo/perl6.moarvm:<entry>)

**Comment by jnthn** [comment]
With every possible more advanced bit of spesh disabled, this still shows up.

```
MVM_SPESH_PEA_DISABLE=1 MVM_SPESH_OSR_DISABLE=1 MVM_SPESH_INLINE_DISABLE=1 MVM_SPESH_JIT_DISABLE=1 MVM_SPESH_BLOCKING=1 MVM_SPESH_NODELAY=1 ./rakudo-m --ll-exception -Ilib t/spec/S05-grammar/parse_and_parsefile-6e.t
```

**Comment by jnthn** [comment]
It's something wrong with args opt. We have this:

```
Spesh of 'lineof' (cuid: 182, file: gen/moar/stage2/NQPHLL.nqp:2463)
Callsite 0x30e95c0 (5 args, 3 pos)
  - cache
Positional flags: obj, obj, obj
```

That is, clearly passing a cache named argument. But then:

```
  BB 1 (0x7fa9034a1c58):
    line: 2463 (pc 0)
    Instructions:
      sp_getarg_o       r0(2), liti16(0)  # start of exprjit tree
      sp_getarg_o       r1(2), liti16(1)
      sp_getarg_o       r9(0), liti16(2)
      sp_p6oget_bi      r2(1),   r9(0), liti16(8)
      # JIT: bailed completely because of <param_on_i>
      # expr bail: Cannot get template for: param_on_i
      param_on_i        r3(1), lits(cache),   BB(3)
    Successors: 3, 2
    Predecessors: 0
    Dominance children: 2, 3

  BB 2 (0x7fa9034a1cb8):
    line: 2463 (pc 36)
    Instructions:
      const_i64_16      r3(2), liti16(0)
    Successors: 3
    Predecessors: 1
    Dominance children:

  BB 3 (0x7fa9034a1d18):
    line: 2463 (pc 48)
    Instructions:
      PHI               r3(3),   r3(1),   r3(2)
      const_i64_16      r4(2), liti16(0)
      PHI               r4(3),   r4(2)
      [Annotation: INS Deopt One (idx 0 -> pc 80; line 2463)]
      [Annotation: INS Deopt One (idx 1 -> pc 86; line 2463)]
      sp_paramnamesused sslot(0)
```

It's leaving the `param_on_i` in there. But in fact it seems like it's missing it completely, because it then goes on and inserts an instruction that always blows up 'cus a named argument is unused.
