### ISSUE TITLE
Feature request: add ops similar to setdispatcjerfor/takedispatcher for recording currently active dispatcher

### ISSUE THREAD

**Issue by vrurg** [MoarVM/MoarVM#1247]
I have completed a rewrite of dispatchers in rakudo/rakudo#3500. A key feature of their new functionality is the ability to pass information about an active dispatcher for a subsequent one to allow it pass control back when it's own candidates list is exhausted. For now this is done by setting a dynamic `$*NEXT-DISPATCHER`. But having MoarVM support similar to that of `setdispatcherfor`/`takedispatcher` would improve the performance.

Would it be possible to implement such opcodes? Name is not relevant. Besides, I don't like 'NEXT' in this context; just stuck with it and can't come up with something better.

**Comment by vrurg** [comment]
As I got some time I can spend on better explanation of what is requested.

The original implementation of dispatchers did not consider situations where an acting dispatcher can invoke a routine which would vivify a subsequent dispatcher. An example of such situation would be wrapping a method call. If the method has one of `nextsame/callsame`/etc., it would be called in the context of `WrapperDispatcher` and won't re-dispatch to the next method in MRO as expected.

To handle these cases, I introduced chaining of dispatchers. It is implemented by passing the information about  current dispatcher to the subsequent one so it knows where go next when own candidate list is exhausted. Currently this is done using a dynamic `$*NEXT-DISPATCHER`.

The downsides of this approach are clear: it's rather slow. And one cannot just call the next code object without setting the dynamic. The latter resulted in `nextcallee` returning a stub parameterized block instead of actual callee object.

It would be way more effective if I'm able to record the required piece of data into code's frame same way `nqp::setdispatcherfor` does. `nqp::p6finddispatcher` would then be able to fetch it and pass to `vivify_for` as an additional parameter. I don't even see a need for an additional dynamic in this case, contrary to `$*DISPATCHER` which is unavoidable.

Alternatively, an op similar to `nqp::takedispatcher` could be provided which would return this information. In this case dispatcher's code would be able to fetch this data without involving `nqp::p6finddispatcher` and an additional parameter for `vivify_for`. Actual solution would depend on which way is considered more effective.

Also, I'm not sure how exactly `nqp::setdispatcherfor` is implemented, but the information about about the upstream dispatcher must be discarded from the code object as soon as possible to prevent it from being used by another call stack.

**Comment by Altai-man** [comment]
I am sorry, can you please provide a more descriptive ticket name into anything giving more info about the nature of the request?

**Comment by vrurg** [comment]
@Altai-man would something like that be ok? It was too late to think of something better when I was opening the request. :)

Anyway, I'm probably going to implement it on my own today.

**Comment by vrurg** [comment]
Not relevant anymore.
