### ISSUE TITLE
Trying to use an untyped array with buffer write functions segfaults.

### ISSUE THREAD

**Issue by ShimmerFairy** [MoarVM/MoarVM#1310]
I've only tested this with `nqp::writeint`, but I would not be surprised if it affected other opcodes in the same family.

    $ nqp -e 'my @a; my int8 $b := 42; nqp::writeint(@a, 0, $b, nqp::const::BINARY_SIZE_16_BIT); say(nqp::atpos(@a, 0));'
    Segmentation fault (core dumped)

Worth noting that `writeint` on its own does not segfault, rather it's when you try to use `say` to print the result of an `atpos` afterwards.

**Comment by niner** [comment]
Looks like we're missing a check of `REPR_DATA(buf)->slot_type` to make sure we're writing to an int array.
