### ISSUE TITLE
2020.06 Compilation Fails on CentOS 7.8 & Oracle Linux 7.8 (UEK)

### ISSUE THREAD

**Issue by markldevine** [MoarVM/MoarVM#1323]
- CentOS Linux release 7.8.2003 (Core)
- Oracle Linux Server release 7.8
((( rakubrew build moar )))

.
.
.
compiling src/debug/debugserver.o
src/debug/debugserver.c: In function ‘request_context_lexicals’:
src/debug/debugserver.c:1456:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (MVMuint32 j = 0; j < num_lexicals; j++) {
         ^
src/debug/debugserver.c:1456:9: note: use option -std=c99 or -std=gnu99 to compile your code
make: *** [src/debug/debugserver.o] Error 1
Command failed (status 512): /opt/perlbrew/perls/perl-5.32.0/bin/perl Configure.pl --optimize --git-cache-dir=/opt/rakubrew/git_reference --prefix=/opt/rakubrew/versions/moar-2020.06/install --make-install
 at /opt/rakubrew/versions/moar-2020.06/nqp/3rdparty/nqp-configure/lib/NQP/Config.pm line 34.
        NQP::Config::__ANON__("Command failed (status 512): /opt/perlbrew/perls/perl-5.32.0/"...) called at /opt/rakubrew/versions/moar-2020.06/nqp/3rdparty/nqp-configure/lib/NQP/Config.pm line 1483
        NQP::Config::system_or_die("/opt/perlbrew/perls/perl-5.32.0/bin/perl", "Configure.pl", "--optimize", "--git-cache-dir=/opt/rakubrew/git_reference", "--prefix=/opt/rakubrew/versions/moar-2020.06/install", "--make-install") called at /opt/rakubrew/versions/moar-2020.06/nqp/tools/lib/NQP/Config/NQP.pm line 425
        NQP::Config::NQP::gen_moar(NQP::Config::NQP=HASH(0x18f26d0)) called at /opt/rakubrew/versions/moar-2020.06/nqp/tools/lib/NQP/Config/NQP.pm line 105
        NQP::Config::NQP::configure_moar_backend(NQP::Config::NQP=HASH(0x18f26d0)) called at /opt/rakubrew/versions/moar-2020.06/nqp/3rdparty/nqp-configure/lib/NQP/Config.pm line 660
        NQP::Config::configure_active_backends(NQP::Config::NQP=HASH(0x18f26d0)) called at Configure.pl line 93
Command failed (status 512): /opt/perlbrew/perls/perl-5.32.0/bin/perl Configure.pl --prefix=/opt/rakubrew/versions/moar-2020.06/install --make-install --git-protocol=https --no-relocatable --no-ignore-errors --silent-build --no-force-rebuild --git-cache-dir=/opt/rakubrew/git_reference --backends=moar --gen-moar
 at /opt/rakubrew/versions/moar-2020.06/3rdparty/nqp-configure/lib/NQP/Config.pm line 34.
        NQP::Config::__ANON__("Command failed (status 512): /opt/perlbrew/perls/perl-5.32.0/"...) called at /opt/rakubrew/versions/moar-2020.06/3rdparty/nqp-configure/lib/NQP/Config.pm line 1483
        NQP::Config::system_or_die("/opt/perlbrew/perls/perl-5.32.0/bin/perl", "Configure.pl", "--prefix=/opt/rakubrew/versions/moar-2020.06/install", "--make-install", "--git-protocol=https", "--no-relocatable", "--no-ignore-errors", "--silent-build", ...) called at /opt/rakubrew/versions/moar-2020.06/tools/lib/NQP/Config/Rakudo.pm line 708
        NQP::Config::Rakudo::gen_nqp(NQP::Config::Rakudo=HASH(0x26806d0)) called at Configure.pl line 101
Failed running /opt/perlbrew/perls/perl-5.32.0/bin/perl Configure.pl --backends=moar --gen-moar --make-install  --git-cache-dir="/opt/rakubrew/git_reference" at /opt/rakubrew/rakubrew line 714.

**Comment by jnthn** [comment]
I think this is a duplicate of #1309 (which is already fixed at HEAD).

**Comment by markldevine** [comment]
Thanks for the quick response.
