### ISSUE TITLE
'pthread_t' undeclared on MinGW

### ISSUE THREAD

**Issue by patrickbkr** [MoarVM/MoarVM#1345]
MoarVM fails to build on Windows with MinGW since 2020.07.

This bug was originally reported by @SqrtNegInf in [Raku/App-Rakubrew#24](https://github.com/Raku/App-Rakubrew/issues/24).

Build log: [build log](https://gist.github.com/SqrtNegInf/d98d683b52c5837514abd04a8bc741a8)

Ping @timo

**Comment by timo** [comment]
https://github.com/MoarVM/MoarVM/pull/1377

**Comment by dumarchie** [comment]
I just built MoarVM 2020.10-31-gb13f6a24c on Windows using `gcc`.  This issue can be closed.

**Comment by patrickbkr** [comment]
Sounds good. Closing.
