### ISSUE TITLE
git protocols, submodules

### ISSUE THREAD

**Issue by coke** [MoarVM/MoarVM#136]
When building rakudo or nqp, one can pass --git-protocol to control how the required projects are checked out, allowing for users behind a firewall to pick a protocol that works for them.

However, this fails at the MoarVM level, since it is using submodules instead of manually checking out the other projects.

It would be nice if we MoarVM's config process could respect nqp's --git-protocol, and allow a checkout using the same protocol as specified at the higher level.

**Comment by dod38fr** [comment]
This issue can be avoided by using this kind of lines in `~/.gitconfig`:
```
[url "git@github.com:"]
        insteadOf = "https://github.com/"
        insteadOf = "git://github.com/"
```

Hope this helps

**Comment by coke** [comment]
WFM. Thanks.
