### ISSUE TITLE
Unshift performs very badly compared to push

### ISSUE THREAD

**Issue by thibaultduponchelle** [MoarVM/MoarVM#1382]
Hello,

I noticed a big difference of performances and "stability" between `push` and `unshift` (and probably `prepend`). 

Look at these bench snippets : 

```
# Performs VERY well
my int @a = ();
for (1..4000000) -> int $item {
    @a.push($item);
}

# real  0m0.328s
# user  0m0.358s
# sys   0m0.041s


# Performs VERY bad
my int @a = ();
for (1..4000000) -> int $item {
    @a.unshift($item);
}

# real 12m51.902s
# user 12m48.184s
# sys 0m0.544s
```

Below some results, unshift for 500 000 takes 3secs and unshift for 4 000 000 iterations takes ~13mins : 

![terribleunshift](https://user-images.githubusercontent.com/580360/99266502-1e2a7f00-2823-11eb-8fbf-263f6baec4bf.png)

On the other hand, push performs very very well :)

Thibault

**Comment by thibaultduponchelle** [comment]
FWIW, Rakudo + JVM seems to have the same kind of behaviour : 

```
# Push 
# 500 000
real	0m5.690s
user	0m17.037s
sys	0m0.480s

# 1 000 000
real	0m6.852s
user	0m16.436s
sys	0m0.736s

# 2 000 000
real	0m9.048s
user	0m20.545s
sys	0m0.520s

# Unshift
# 500 000
# real 0m9.794s
# user 0m19.672s
# sys 0m0.575s

# 1 000 000
# real 0m36.576s
# user 0m48.939s
# sys 0m0.588s

# 2 000 000
# real 3m6.268s
# user 3m25.288s
# sys 0m1.115s
```

**Comment by lizmat** [comment]
I am not suprised: pretty sure that part of the internal logic was basically directly ported from Java to C.  Or vice-versa, potentially.

**Comment by thibaultduponchelle** [comment]
Great ! Thank you a lot 🙏
