### ISSUE TITLE
Apple Silicon nqp build fails unless MVM_JIT_DISABLE is set

### ISSUE THREAD

**Issue by cognominal** [MoarVM/MoarVM#1395]
When MVM_JIT_DISABLE is set. NQP passes the tests which is auspicious.
So something is wrong in the autoconfiguration.

Lldb indicates, when MVM_JIT_DISABLE is unset, and moar is run, that it crashes on jit_enter.

With MVM_JIT_DISABLE is set, rakudo just pulled from github (0d6278f329223f97e8831ce4daecb2f1026cf05e)
compiles and fails one test
t/04-nativecall/02-simple-args.t                              (Wstat: 256 Tests: 14 Failed: 1)

**Comment by MasterDuke17** [comment]
Have you tried passing the `--no-jit` flag to MoarVM's Configure.pl?

**Comment by cognominal** [comment]
Indeed. Using an environment variable is brittle. The proper way to compile nap is below.

  perl Configure.pl --gen-moar --backends=moar --moar-option='--no-jit'

It passes all the tests

  Files=145, Tests=13408, 15 wallclock secs ( 0.32 usr  0.12 sys + 12.25 cusr  0.58 csys = 13.27 CPU)
  All tests successful.

**Comment by lizmat** [comment]
Shouldn't this be set automatically for that environment?

**Comment by cognominal** [comment]
> Shouldn't this be set automatically for that environment?
yes. But that's a bigger issue : compiling a fat Apple binary. A bigger one even : jitting for M1, which is different than jitting for arm64 because Apple add specific call conventions.
I hope "fat binary" is not a double trigger for the Orwellian crowd.

**Comment by lizmat** [comment]
Well, having moved from ARM to Intel using fat binaries in an age where disk space was still more at a premium, was not an issue then, and I doubt will become an issue now.

Are the Apple call conventions sufficiently different from ARM's to warrant a complete separate project?  Or do you think it could be a "flag" in a more generic JITting on ARM project?

**Comment by cognominal** [comment]
> Are the Apple call conventions sufficiently different from ARM's to warrant a complete separate project? Or do you think it could be a "flag" in a more generic JITting on ARM project?

I am no expert in JITing. I will put a link when I will find it again. But from memory, Apple sets  aside an additional reserved register in addition to the one asked by the ARM docs.
I will 2 open specific issues : one for Apple specific configuration, one for JITing
