### ISSUE TITLE
perl6 -e 'loop { start { say "hello" } }' doesn't work 

### ISSUE THREAD

**Issue by zhuomingliang** [MoarVM/MoarVM#140]
see http://irclog.perlgeek.de/perl6/2014-09-11#i_9335568 and https://gist.github.com/zhuomingliang/135d8926a133ee680470

**Comment by zhuomingliang** [comment]
This still hangs after outputing(which is wrong too):
```
hello
hello
hellohellohellohello



hello
hello
hellohello

hello
hellohello

hello
```

**Comment by dod38fr** [comment]
Runs fine with rakudo/moarvm 2015.09 (on Debian/sid amd64 with Debian packages)

I stopped it after 15mns.

**Comment by zhuomingliang** [comment]
outputs changed, but still hangs here. on ubuntu:

```
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello 
# hangs...
```

**Comment by dod38fr** [comment]
@zhuomingliang what version of rakudo/nqp/moar do you have on your system ?

**Comment by zhuomingliang** [comment]
latest.

**Comment by timo** [comment]
see this gist for a backtrace from all threads:

https://gist.github.com/timo/e718153e22177958174b

**Comment by zhuomingliang** [comment]
This is fixed now. But I don't know how to write a test to it.

**Comment by jnthn** [comment]
Me either, for this particular case. However, another test I recently added that makes heavy use of semaphores would hang now and then due what I'm pretty sure was the very same bug. I think we can consider that to be sufficient coverage.

**Comment by samcv** [comment]
@jnthn so are we able to close this issue now? Thanks.

**Comment by duke-m** [comment]
`perl6 -e 'my int $i=0;loop { start { say "hello "~$i++;$i %= 10; } }'` seems to work now, let's close this one, if you please.

**Comment by samcv** [comment]
I'm going to close this. If anybody has any objections let me know.
