### ISSUE TITLE
Modify curcode op to make it inlinable

### ISSUE THREAD

**Issue by vrurg** [MoarVM/MoarVM#1404]
As it was discussed in rakudo/rakudo#4056, to minimize the impact the new coercions done to Rakudo performance we need `nqp::curcode` to be inlinable. According to [a note on IRC](https://colabti.org/irclogger/irclogger_log/moarvm?date=2020-11-25#l182) it should be doable.

Hope we eventually have it done. :) Considering my own less than successful endeavor into implementing `*nextdispatcher` ops, I don't feel like trying again yet.

**Comment by niner** [comment]
As requested: https://github.com/MoarVM/MoarVM/pull/1405

**Comment by niner** [comment]
#1405 is merged, so this issue is fixed.

Do you have any interesting benchmarks about this?

**Comment by vrurg** [comment]
In the opening comment of rakudo/rakudo#4056 @MasterDuke17 provided links to two scripts. Of these whitenoise is the most noteworthy as it's performance was initially cut by a factor of 10, and then I managed to improve the situation but it's still 4.5x times slower that was on 2020.10.

I tried both with #1405 merged. NQP needed a change too as it was still marking `curcode` as non-linlinable. But nothing changed if not got worse. The whitenoise script was normally running with 44fps, now it's more like 42fps.

**Comment by MasterDuke17** [comment]
With 2020.10, @dogbert17's script was ~2.8s, at HEAD (plus removing the `:!inlinable` from https://github.com/Raku/nqp/blob/master/src/vm/moar/QAST/QASTOperationsMAST.nqp#L2071 and rebuilding NQP+Rakudo) it's now 3.7s. The whitenoise script is ~56 fps, when before it was a couple hundred (don't remember exactly).

**Comment by vrurg** [comment]
@niner BTW, is it ok that JIT template for curcode is not changed? It still refers to `MVMFrame` field, if I read it correctly.

**Comment by jnthn** [comment]
The process of inlining `curcode` replaces it with an access to a register holding the code object we're calling (something that was already in place to support inlining closures, among other things), so after inlining there is no `curcode` op any more. Thus we never JIT it in this case.

**Comment by jnthn** [comment]
> Thus we never JIT it in this case.

Ah, I just realized this could maybe be read as meaning we can't JIT things that have a `curcode` replaced during inlining. We can; the replacement is the `set` instruction, so it turns into a `mov` at worst.

**Comment by niner** [comment]
> NQP needed a change too as it was still
> marking `curcode` as non-linlinable.

That's a different thing as the comment at
https://github.com/rakudo/rakudo/blob/44cc88b54ca2/src/Perl6/Actions.nqp#L4350
explains. For the HLL inliner curcode is still non-inlinable. That shouldn't 
matter as much though.

Will have to look at the benchmark for why this doesn't seem to help. Maybe 
curcode is always paired with another op that prevents inlining? What does the 
code you added which causes the slow down look like?

**Comment by MasterDuke17** [comment]
> What does the code you added which causes the slow down look like?

It was bisected to https://github.com/rakudo/rakudo/commit/1f090e04dcd4edac7682c59424cff60464ddb895 with a comment from vrurg "I think the most likely cause are changes in Actions.nqp, sub lower_signature, if/elsif pair at line 9225."

**Comment by vrurg** [comment]
The code has changed since that comment was made. Anyway, the basic idea behind is that for generic parameters where we can't do things compile-time the signature takes the parameter list using the current code object and takes care of the generic ones. The bit of fetching the parameter list is now localized in `sub signature_params` at line 9082. The ops chain is simply `nqp::getattr(nqp::getattr(nqp::getcodeobj(nqp::curcode), Code, '$!signature'), Signature, '@!params')`. It then bound to a locally scoped var and used with subsequent generic params if there any.

The code is not injected into signature binding unless a generic parameter is encountered. Hence my expectation is that inlining of simple signatures must not be affected as it's basically identical to the older code.

The coercion implementation itself winds down to invocation of `coerce` method on a parameter coercion type metaclass. Apparently, this is done for both generic and non-generic cases.

I have checked through ops involved and found no other non-inlinable ones. As my knowledge of how inlining works is limited, the only wild guess I have as to what might break it is that the overall code size became too large.
