### ISSUE TITLE
missing release artifact for moarvm 2020.12

### ISSUE THREAD

**Issue by chenrui333** [MoarVM/MoarVM#1409]
👋  it looks like the `moarvm 2020.12` is not tagged as the latest release, also the release artifact is missing as well. Thanks!

**Comment by chenrui333** [comment]
cc @Altai-man

**Comment by Altai-man** [comment]
Hi! Thanks for your report, that was a miss of me!

It is not like 2020.12 is not _tagged_, there is a proper tag around, it is just that the github-specific "release" was not created.
I just created it, so closing the issue.

Also, the release artifact can always be obtained from http://moarvm.org/ and 2020.12 was there before and is there now.

**Comment by chenrui333** [comment]
Thanks @Altai-man!!

**Comment by chenrui333** [comment]
Just curious, what is the official release portal for nqp? I can find the release site for [moarvm](https://moarvm.org/releases/MoarVM-2020.12.tar.gz) and [rakudo](https://rakudo.org/dl/rakudo/rakudo-2020.12.tar.gz), but not nqp? Thanks!

**Comment by Altai-man** [comment]
>I can find the release site for moarvm and rakudo, but not nqp?

NQP is an implementation detail meant largely for Rakudo developers, not for end users to consume, thus we do not have a separate entity for it. When building a Rakudo, which is the most common thing I believe, it knows what to do with nqp and does not involve user there, and if you need something very specific with nqp alone, the releases are published at https://github.com/Raku/nqp/releases

**Comment by chenrui333** [comment]
make sense, thank you!
