### ISSUE TITLE
Bug: VMArray's read_buf and write_buf miscalculate bounds

### ISSUE THREAD

**Issue by salortiz** [MoarVM/MoarVM#1421]
In both functions the "count" argument is simply added to "offset" when calculating if the requested operation are in the bounds of the VMArray. The elem_size ("repr_data->elem_size") should be accounted.

For a manifestation of the bug, please see https://colabti.org/irclogger/irclogger_log/raku?date=2021-01-19#l601

Analysis:
These functions now supports the OPs 'writeint', 'readint', 'readnum', etc, so the "count" argument is the size in bytes of the attempted read/write (1, 2, 4 or 8 bytes).
The "offset" argument points to an slot of "elem-size" bytes, then for any "count <= elem_size" the operation is inside the slot and valid. Nothing should be added to "offset".
Only when "count > elem_size" the operation involves "count / elem_size - 1" more slots to be accounted.

**Comment by niner** [comment]
Fixed in https://github.com/MoarVM/MoarVM/commit/79d0e3749ac2b03140e9717927a611c918b5674d
