### ISSUE TITLE
Segfault in VMArray's copy_elems

### ISSUE THREAD

**Issue by MasterDuke17** [MoarVM/MoarVM#1432]
`my @a := 1, 2, 3; my %b := nqp::hash; %b<a> := 1; nqp::splice(@a, %b, 1, 0)` causes a segfault here https://github.com/MoarVM/MoarVM/blob/master/src/6model/reprs/VMArray.c#L836 because `s_repr_data` ends up NULL here https://github.com/MoarVM/MoarVM/blob/master/src/6model/reprs/VMArray.c#L813-L814

Problematic MoarVM code found by the GCC static analyzer, example crafted by @niner.

**Comment by salortiz** [comment]
I think the following diff should fix the issue:

```diff
@@ -812,7 +812,7 @@ static void copy_elements(MVMThreadContext *tc, MVMObject *src, MVMObject *dest,
     MVMArrayBody     *d_body      = (MVMArrayBody *)OBJECT_BODY(dest);
     MVMArrayREPRData *s_repr_data = REPR(src)->ID == MVM_REPR_ID_VMArray
                                     ? (MVMArrayREPRData *)STABLE(src)->REPR_data  : NULL;
-    MVMArrayREPRData *d_repr_data = REPR(src)->ID == MVM_REPR_ID_VMArray
+    MVMArrayREPRData *d_repr_data = REPR(dest)->ID == MVM_REPR_ID_VMArray
                                     ? (MVMArrayREPRData *)STABLE(dest)->REPR_data : NULL;
 
     if (elems > 0) {
@@ -833,7 +833,7 @@ static void copy_elements(MVMThreadContext *tc, MVMObject *src, MVMObject *dest,
             );
         }
         else {
-            switch (s_repr_data->slot_type) {
+            switch (d_repr_data->slot_type) {
                 case MVM_ARRAY_OBJ:
                     kind = MVM_reg_obj;
                     break;
```
Rationale:
`copy_elements` is used only by `aslice` and `asplice` functions. In both cases `dest` is a VMArray, in `asplice` is `root` and is assumed by https://github.com/MoarVM/MoarVM/blob/master/src/6model/reprs/VMArray.c#L836, so `kind` can be determined by `dest`.

The first part of the diff fixes an ancient typo IMO.

**Comment by MasterDuke17** [comment]
@salortiz interested in creating a PR? Some additional discussion here https://colabti.org/irclogger/irclogger_log/moarvm?date=2021-02-10#l38
