### ISSUE TITLE
Running innocent Raku script invokes the oom killer

### ISSUE THREAD

**Issue by dogbert17** [MoarVM/MoarVM#1466]
This problem was found by nwc10++ yesterday when running t/spec/S32-temporal/juliandate.t, below is a golf. After some bisecting it seem as if the offending commit is https://github.com/MoarVM/MoarVM/commit/9b94bab9eb2803e19c4616a4b0d163d96e41cd1b.

    dogbert@dogbert-VirtualBox:~/repos/rakudo$ ./perl6-m -v
    Welcome to Rakudo(tm) v2021.03-140-ga26ff404f.
    Implementing the Raku(tm) programming language v6.d.
    Built on MoarVM version 2021.03-41-gfb696f18a.
    dogbert@dogbert-VirtualBox:~/repos/rakudo$ /usr/bin/time ./perl6-m -e 'my $day-frac = sprintf "%.*f", 7, 0.00000012 for ^500'
    Command terminated by signal 9
    24.89user 2.62system 0:30.92elapsed 88%CPU (0avgtext+0avgdata 11734148maxresident)k
    524792inputs+0outputs (2117major+3026585minor)pagefaults 0swaps

breaking into the 'hung' process with gdb and running

    p MVM_dump_backtrace(tc)

returns

    at <unknown>:1  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:infix_x)
    from gen/moar/stage2/NQPHLL.nqp:3389  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:normalize)
    from gen/moar/stage2/NQPHLL.nqp:3397  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:stringify-to-precision)
    from gen/moar/stage2/NQPHLL.nqp:3439  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:fixed-point)
    from gen/moar/stage2/NQPHLL.nqp:3518  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:directive:sym<f>)
    from gen/moar/stage2/QRegex.nqp:1651  (/home/dogbert/repos/rakudo/install/share/nqp/lib/QRegex.moarvm:!reduce)
    from gen/moar/stage2/QRegex.nqp:1585  (/home/dogbert/repos/rakudo/install/share/nqp/lib/QRegex.moarvm:!cursor_pass)
    from <unknown>:1  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:directive:sym<f>)
    from gen/moar/stage2/QRegex.nqp:1693  (/home/dogbert/repos/rakudo/install/share/nqp/lib/QRegex.moarvm:!protoregex)
    from <unknown>:1  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:directive)
    from <unknown>:1  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:statement)
    from <unknown>:1  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:TOP)
    from gen/moar/stage2/QRegex.nqp:2256  (/home/dogbert/repos/rakudo/install/share/nqp/lib/QRegex.moarvm:parse)
    from gen/moar/stage2/NQPHLL.nqp:3623  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:sprintf)
    from SETTING::src/core.c/Cool.pm6:511  (/home/dogbert/repos/rakudo/blib/CORE.c.setting.moarvm:sprintf)
    from t/spec/S32-temporal/juliandate.t:61  (<ephemeral file>:)
    from SETTING::src/core.c/Any-iterable-methods.pm6:671  (/home/dogbert/repos/rakudo/blib/CORE.c.setting.moarvm:sink-all)
    from SETTING::src/core.c/Seq.pm6:153  (/home/dogbert/repos/rakudo/blib/CORE.c.setting.moarvm:sink)
    from t/spec/S32-temporal/juliandate.t:33  (<ephemeral file>:)
    from t/spec/S32-temporal/juliandate.t:32  (<ephemeral file>:<unit>)
    from t/spec/S32-temporal/juliandate.t:1  (<ephemeral file>:<unit-outer>)
    from gen/moar/stage2/NQPHLL.nqp:1946  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:eval)
    from gen/moar/stage2/NQPHLL.nqp:2151  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:evalfiles)
    from gen/moar/stage2/NQPHLL.nqp:2081  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
    from gen/moar/Compiler.nqp:109  (/home/dogbert/repos/rakudo/blib/Perl6/Compiler.moarvm:command_eval)
    from gen/moar/stage2/NQPHLL.nqp:2036  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:command_line)
    from gen/moar/rakudo.nqp:127  (/home/dogbert/repos/rakudo/rakudo.moarvm:MAIN)
    from gen/moar/rakudo.nqp:1  (/home/dogbert/repos/rakudo/rakudo.moarvm:<mainline>)
    from <unknown>:1  (/home/dogbert/repos/rakudo/rakudo.moarvm:<main>)
    from <unknown>:1  (/home/dogbert/repos/rakudo/rakudo.moarvm:<entry>)

Running the golf with MVM_SPESH_DISABLE=1 seems to resolve the problem.

**Comment by dogbert17** [comment]
Fixed by https://github.com/MoarVM/MoarVM/commit/9481289950b89dabb553e63d277038518c590b92

**Comment by niner** [comment]
Reverting that commit is certainly an appropriate action. But it's not a fix for this issue. There was a reason for the change to logging deconts. Why does it cause this explosive memory growth or infinite loop or whatever is happening here? What is the real fix?

**Comment by niner** [comment]
Fixed the underlying issue in https://github.com/MoarVM/MoarVM/commit/a1cfecd6db489840500955df03a1e9ca3b5c3bac
