### ISSUE TITLE
Issues with running `await do for ^50 { start { sleep 1 } }`

### ISSUE THREAD

**Issue by tgt** [MoarVM/MoarVM#148]
I've encountered several issues when running the code below. I've seen it occur on OS X and CentOS. I can reproduce it every several runs, but the errors that occur vary. The cannot invoke object ones occur most often.

`await do for ^50 { start { sleep 1 } }`

===================================================================

Unhandled exception: Cannot invoke this object (REPR: P6opaque, cs = 0)
    at <unknown>:1  (/home/tgt/.rakudobrew/moar-HEAD/install/languages/perl6/runtime/CORE.setting.moarvm:throw:4294967295)
    from src/gen/m-CORE.setting:19885  (/home/tgt/.rakudobrew/moar-HEAD/install/languages/perl6/runtime/CORE.setting.moarvm:result:113)
    from src/gen/m-CORE.setting:21363  (/home/tgt/.rakudobrew/moar-HEAD/install/languages/perl6/runtime/CORE.setting.moarvm:await:21)
    from src/gen/m-CORE.setting:8275  (/home/tgt/.rakudobrew/moar-HEAD/install/languages/perl6/runtime/CORE.setting.moarvm::562)
    from src/gen/m-CORE.setting:8198  (/home/tgt/.rakudobrew/moar-HEAD/install/languages/perl6/runtime/CORE.setting.moarvm:reify:62)
    from src/gen/m-CORE.setting:8111  (/home/tgt/.rakudobrew/moar-HEAD/install/languages/perl6/runtime/CORE.setting.moarvm::308)
    from src/gen/m-CORE.setting:8082  (/home/tgt/.rakudobrew/moar-HEAD/install/languages/perl6/runtime/CORE.setting.moarvm:reify:53)
    from src/gen/m-CORE.setting:8594  (/home/tgt/.rakudobrew/moar-HEAD/install/languages/perl6/runtime/CORE.setting.moarvm:gimme:155)
    from src/gen/m-CORE.setting:9092  (/home/tgt/.rakudobrew/moar-HEAD/install/languages/perl6/runtime/CORE.setting.moarvm:sink:0)
    from src/gen/m-main.nqp:41  (/home/tgt/.rakudobrew/moar-HEAD/install/languages/perl6/runtime/perl6.moarvm:MAIN:40)
    from src/gen/m-main.nqp:35  (/home/tgt/.rakudobrew/moar-HEAD/install/languages/perl6/runtime/perl6.moarvm:<mainline>:197)
    from <unknown>:1  (/home/tgt/.rakudobrew/moar-HEAD/install/languages/perl6/runtime/perl6.moarvm:<main>:8)
from <unknown>:1  (/home/tgt/.rakudobrew/moar-HEAD/install/languages/perl6/runtime/perl6.moarvm:<entry>:9)
Command exited with non-zero status 1

===================================================================

Unhandled exception in code scheduled on thread 140239712528128
    Type check failed in binding exception; expected 'Any' but got 'Mu'
      in method break at src/gen/m-CORE.setting:19811
      in block  at src/gen/m-CORE.setting:19927
      in block  at src/gen/m-CORE.setting:19720
      in any  at /home/tgt/.rakudobrew/moar-HEAD/install/languages/perl6/runtime/COR
    E.setting.moarvm:1
      in sub sleep at /home/tgt/.rakudobrew/moar-HEAD/install/languages/perl6/runtim
    e/CORE.setting.moarvm:1
      in block  at -e:2
      in block  at src/gen/m-CORE.setting:19926
      in block  at src/gen/m-CORE.setting:19720
      in block  at src/gen/m-CORE.setting:19652
      in block  at src/gen/m-CORE.setting:19643
    Command exited with non-zero status 1

===================================================================

Unhandled exception: Cannot invoke this object (REPR: Null)
   at <unknown>:1  (/home/tgt/.rakudobrew/moar-HEAD/install/languages/perl6/runt
ime/CORE.setting.moarvm:throw:4294967295)
 from src/gen/m-CORE.setting:19885  (/home/tgt/.rakudobrew/moar-HEAD/install/lan
guages/perl6/runtime/CORE.setting.moarvm:result:113)
 from src/gen/m-CORE.setting:21363  (/home/tgt/.rakudobrew/moar-HEAD/install/lan
guages/perl6/runtime/CORE.setting.moarvm:await:21)
 from src/gen/m-CORE.setting:21362  (/home/tgt/.rakudobrew/moar-HEAD/install/lan
guages/perl6/runtime/CORE.setting.moarvm:await:25)
 from src/gen/m-CORE.setting:8275  (/home/tgt/.rakudobrew/moar-HEAD/install/lang
uages/perl6/runtime/CORE.setting.moarvm::562)
 from src/gen/m-CORE.setting:8198  (/home/tgt/.rakudobrew/moar-HEAD/install/lang
uages/perl6/runtime/CORE.setting.moarvm:reify:62)
 from src/gen/m-CORE.setting:8111  (/home/tgt/.rakudobrew/moar-HEAD/install/lang
uages/perl6/runtime/CORE.setting.moarvm::308)
 from src/gen/m-CORE.setting:8082  (/home/tgt/.rakudobrew/moar-HEAD/install/lang
uages/perl6/runtime/CORE.setting.moarvm:reify:53)
 from src/gen/m-CORE.setting:8594  (/home/tgt/.rakudobrew/moar-HEAD/install/lang
uages/perl6/runtime/CORE.setting.moarvm:gimme:155)
 from src/gen/m-CORE.setting:9092  (/home/tgt/.rakudobrew/moar-HEAD/install/lang
uages/perl6/runtime/CORE.setting.moarvm:sink:0)
 from src/gen/m-main.nqp:41  (/home/tgt/.rakudobrew/moar-HEAD/install/languages/
perl6/runtime/perl6.moarvm:MAIN:40)
 from src/gen/m-main.nqp:35  (/home/tgt/.rakudobrew/moar-HEAD/install/languages/
perl6/runtime/perl6.moarvm:<mainline>:197)
 from <unknown>:1  (/home/tgt/.rakudobrew/moar-HEAD/install/languages/perl6/runt
ime/perl6.moarvm:<main>:8)
 from <unknown>:1  (/home/tgt/.rakudobrew/moar-HEAD/install/languages/perl6/runt
ime/perl6.moarvm:<entry>:9)
Command exited with non-zero status 1

===================================================================

Unhandled exception: Cannot call method 'count' on a null object
   at <unknown>:1  (/Users/Tom/.rakudobrew/moar-HEAD/install/languages/perl6/runtime/CORE.setting.moarvm:throw:4294967295)
 from src/gen/m-CORE.setting:19885  (/Users/Tom/.rakudobrew/moar-HEAD/install/languages/perl6/runtime/CORE.setting.moarvm:result:113)
 from src/gen/m-CORE.setting:21363  (/Users/Tom/.rakudobrew/moar-HEAD/install/languages/perl6/runtime/CORE.setting.moarvm:await:21)
 from src/gen/m-CORE.setting:21362  (/Users/Tom/.rakudobrew/moar-HEAD/install/languages/perl6/runtime/CORE.setting.moarvm:await:25)
 from src/gen/m-CORE.setting:8275  (/Users/Tom/.rakudobrew/moar-HEAD/install/languages/perl6/runtime/CORE.setting.moarvm::562)
 from src/gen/m-CORE.setting:8198  (/Users/Tom/.rakudobrew/moar-HEAD/install/languages/perl6/runtime/CORE.setting.moarvm:reify:62)
 from src/gen/m-CORE.setting:8111  (/Users/Tom/.rakudobrew/moar-HEAD/install/languages/perl6/runtime/CORE.setting.moarvm::308)
 from src/gen/m-CORE.setting:8082  (/Users/Tom/.rakudobrew/moar-HEAD/install/languages/perl6/runtime/CORE.setting.moarvm:reify:53)
 from src/gen/m-CORE.setting:8594  (/Users/Tom/.rakudobrew/moar-HEAD/install/languages/perl6/runtime/CORE.setting.moarvm:gimme:155)
 from src/gen/m-CORE.setting:9092  (/Users/Tom/.rakudobrew/moar-HEAD/install/languages/perl6/runtime/CORE.setting.moarvm:sink:0)
 from src/gen/m-main.nqp:41  (/Users/Tom/.rakudobrew/moar-HEAD/install/languages/perl6/runtime/perl6.moarvm:MAIN:40)
 from src/gen/m-main.nqp:35  (/Users/Tom/.rakudobrew/moar-HEAD/install/languages/perl6/runtime/perl6.moarvm:<mainline>:197)
 from <unknown>:1  (/Users/Tom/.rakudobrew/moar-HEAD/install/languages/perl6/runtime/perl6.moarvm:<main>:8)
 from <unknown>:1  (/Users/Tom/.rakudobrew/moar-HEAD/install/languages/perl6/runtime/perl6.moarvm:<entry>:9)

===================================================================

I've also seen this deadlock.

**Comment by timo** [comment]
i haven't tried to reproduce this on an older version, but on the latest MoarVM, NQP and Rakudo, this no longer produces any problems. i tried it ~10 times. closing this as resolved.

**Comment by tgt** [comment]
I can still see this issue on the latest version. In 100 attempts it occurred once. Rather than the above errors occurring I now get `Cannot invoke this object (REPR: Null)`.
