### ISSUE TITLE
100% CPU core usage after using moar signal()

### ISSUE THREAD

**Issue by azawawi** [MoarVM/MoarVM#149]
timotimo++ noticed after trying out [Farabi6](https://github.com/azawawi/farabi6/) that one his CPU cores are maxed out by the "idle" perl6 moar process. After investigating it, I found out that the CTRL-C signal handler that I recently added is the culprit. Please check this example:

```Perl6
#!/usr/bin/env perl6
 
use v6;
 
signal(SIGINT).tap({
"Ctrl-C detected".say;
die
});
 
prompt("Waiting for your input...");

# vim: ft=perl6
```

Perl 6 version tested against
```
$ perl6 --version
This is perl6 version 2014.09-258-g315ec62 built on MoarVM version 2014.09-54-g03ac9a7
```

Maybe related to the libuv implementation in https://github.com/MoarVM/MoarVM/blob/master/src/io/signals.c

Thanks for your time

**Comment by jnthn** [comment]
This was fixed in the 2015.06 release.

**Comment by azawawi** [comment]
Thanks for the fix. It is true that it does not cause 100% CPU usage **but no a Ctrl-C does not cause any exit from ```die```.**

**Comment by timo** [comment]
there is a RT ticket about taps silently swallowing exceptions like that. this is no longer a MoarVM issue.

**Comment by azawawi** [comment]
@timo  Could you guide me to that RT ticket please?

**Comment by timo** [comment]
https://rt.perl.org/Public/Bug/Display.html?id=125621 is the one

**Comment by azawawi** [comment]
@timo Thanks
