### ISSUE TITLE
Random tests are failing with `No plan found in TAP output`

### ISSUE THREAD

**Issue by Altai-man** [MoarVM/MoarVM#1500]
On various CI jobs different tests files are failing with the mentioned error, apparently being some MoarVM level failure.

Recent examples are:

https://dev.azure.com/MoarVM/MoarVM/_build/results?buildId=578&view=logs&j=d36c29d8-9236-5cd5-d848-768a0b8a3eb3&t=159b5397-e4a5-5784-febd-35f9e657944a

```
t/02-rakudo/06-is.t                                           (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
Files=112, Tests=1835, 188 wallclock secs ( 0.77 usr +  0.33 sys =  1.09 CPU)
Result: FAIL

```

https://dev.azure.com/MoarVM/MoarVM/_build/results?buildId=578&view=logs&j=d0f6403b-d137-5ae0-a533-f4bebafcc251&t=608d3b9b-a763-5670-6013-39559d8f7fdf

```
t/04-nativecall/13-cpp-mangling.t                             (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
Files=112, Tests=1816, 110 wallclock secs ( 0.48 usr  0.12 sys + 194.46 cusr 18.49 csys = 213.55 CPU)
Result: FAIL
```

https://dev.azure.com/MoarVM/MoarVM/_build/results?buildId=576&view=logs&j=4def8e43-62b3-5cca-1c32-fbd5a1f0442a&t=6f17dd53-63e8-5611-e660-0bfbef84498f

```
t/02-rakudo/10-nqp-ops.t                                      (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
Files=112, Tests=1839, 155 wallclock secs ( 0.77 usr +  0.25 sys =  1.02 CPU)
Result: FAIL
```

https://dev.azure.com/MoarVM/MoarVM/_build/results?buildId=565&view=logs&j=70f6b8a1-f3cf-5727-bd79-d08ddb1caf67&t=f59a17df-92a9-5d7f-18bb-7f81f1c720a8

```
t/05-messages/moar/01-errors.t                                (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
Files=112, Tests=1840, 212 wallclock secs ( 1.06 usr +  0.25 sys =  1.31 CPU)
Result: FAIL
```

**Comment by MasterDuke17** [comment]
The first, second, and fourth errors are "just" the known problem running tests in parallel on Windows. It's not related to those specific tests.

Second one `t/04-nativecall/13-cpp-mangling.t` looks like a legit problem.
```
ok 28 - b.byte must be the same
ok
Unhandled exception in code scheduled on thread 4
push_o requires a concrete object (got a ThreadPoolScheduler::Queue type object instead)

t/04-nativecall/13-cpp-mangling.t ............................... 
Dubious, test returned 1 (wstat 256, 0x100)
No subtests run
```

**Comment by niner** [comment]
The "push_o requires a concrete object (got a ThreadPoolScheduler::Queue type object instead)" has been a long standing issue and I've seen it plenty of times on OBS builds. In fact I believe it's the most common random build failure. Alas despite looking at the code several times already, I have no idea how that could happen. And so far I have not managed to reproduce it locally even once.

**Comment by Altai-man** [comment]
Thanks for the heads up!

>The first, second, and fourth errors are "just" the known problem running tests in parallel on Windows

Can we help it somehow / investigate how to help it somehow?

**Comment by niner** [comment]
> Can we help it somehow / investigate how to help it somehow?

Apparently the generally accepted "solution" for this is to just retry after 
waiting briefly. Those errors are all about inability to replace a repo-id 
file. These files are frequently read, but are very small and get closed 
immediately after reading. Giving it a few tries after waiting for a random 
time should get us around implicit locking on Windows.

**Comment by niner** [comment]
Note that this retry would be implemented in CompUnit::PrecompilationStore::File's store-repo-id method and could be done even by a novice Raku programmer.
