### ISSUE TITLE
Flapper in t/spec/S32-num/complex.t

### ISSUE THREAD

**Issue by dogbert17** [MoarVM/MoarVM#1607]
This test sometimes fails when run under MVM_SPESH_NODELAY=1 and a small nursery. To reproduce run:

    while MVM_SPESH_NODELAY=1 ./rakudo-m -Ilib t/spec/S32-num/complex.t; do :; done

with a nursery size set to ~50k, I ran with (52 * 1024) and MVM_GC_DEBUG=1

    dogbert@dogbert-VirtualBox:~/repos/rakudo$ ./rakudo-m -v
    Welcome to Rakudo™ v2021.10-104-g5f8441024.
    Implementing the Raku® Programming Language v6.d.
    Built on MoarVM version 2021.10-71-gc779c6320.
    dogbert@dogbert-VirtualBox:~/repos/rakudo$ while MVM_SPESH_NODELAY=1 ./rakudo-m -Ilib t/spec/S32-num/complex.t; do :; done
    1..555
    ok 1 - Complex.new() gives 0+0i
    ok 2 - postfix:<i> creates a Complex number
    ...
    ok 445 - -33.92400126841632-21.193445636339735i + 0 = -33.92400126841632-21.193445636339735i
    ok 446 - 0 + -33.92400126841632-21.193445636339735i = -33.92400126841632-21.193445636339735i
    MoarVM panic: Invalid owner in item added to GC worklist

more often another message shows up, i.e. 
   
    MoarVM panic: Memory allocation failed; could not allocate 16260172448 bytes

and then it looks like this under gdb

    ok 201 - -2+0i - 2.5.Num = -2+0i
    ok 202 - 2.5.Num - -2+0i = -2+0i
    [Switching to Thread 0x7ffff720e700 (LWP 96014)]
    
    Thread 2 "spesh optimizer" hit Breakpoint 1, MVM_panic (exitCode=0, messageFormat=0x0) at src/core/exceptions.c:840
    840	MVM_NO_RETURN void MVM_panic(MVMint32 exitCode, const char *messageFormat, ...) {
    (gdb) bt
    #0  MVM_panic (exitCode=0, messageFormat=0x0) at src/core/exceptions.c:840
    #1  0x00007ffff77da132 in MVM_panic_allocation_failed (len=16351373024) at src/core/exceptions.c:854
    #2  0x00007ffff7846b0d in MVM_calloc (num=1, size=16351373024) at src/core/alloc.h:14
    #3  0x00007ffff7846cf4 in MVM_region_alloc (tc=0x555555622460, al=0x7ffff2eef978, bytes=16351373024) at src/core/regionalloc.c:22
    #4  0x00007ffff792207e in MVM_spesh_alloc (tc=0x555555622460, g=0x7ffff2eef920, bytes=16351373024) at src/spesh/graph.c:41
    #5  0x00007ffff793c483 in analyze_phi (tc=0x555555622460, g=0x7ffff2eef920, ins=0x7fffe851605e) at src/spesh/optimize.c:2021
    #6  0x00007ffff793c6f1 in optimize_bb_switch (tc=0x555555622460, g=0x7ffff2eef920, bb=0x7fffe8512aa8, p=0x0) at src/spesh/optimize.c:2045
    #7  0x00007ffff793ce7d in optimize_bb (tc=0x555555622460, g=0x7ffff2eef920, bb=0x7fffe8512aa8, p=0x0) at src/spesh/optimize.c:2355
    #8  0x00007ffff793b189 in optimize_runbytecode (tc=0x555555622460, g=0x7ffff2eef920, bb=0x7ffff1521260, ins=0x7ffff320f170, p=0x7ffff322fe00) at src/spesh/optimize.c:1617
    #9  0x00007ffff793cc66 in optimize_bb_switch (tc=0x555555622460, g=0x7ffff2eef920, bb=0x7ffff1521260, p=0x7ffff322fe00) at src/spesh/optimize.c:2290
    #10 0x00007ffff793ce7d in optimize_bb (tc=0x555555622460, g=0x7ffff2eef920, bb=0x7ffff1521260, p=0x7ffff322fe00) at src/spesh/optimize.c:2355
    #11 0x00007ffff793ceb7 in optimize_bb (tc=0x555555622460, g=0x7ffff2eef920, bb=0x7fffe8534f20, p=0x7ffff322fe00) at src/spesh/optimize.c:2359
    #12 0x00007ffff793ceb7 in optimize_bb (tc=0x555555622460, g=0x7ffff2eef920, bb=0x7fffe8534e98, p=0x7ffff322fe00) at src/spesh/optimize.c:2359
    #13 0x00007ffff793e745 in MVM_spesh_optimize (tc=0x555555622460, g=0x7ffff2eef920, p=0x7ffff322fe00) at src/spesh/optimize.c:2793
    #14 0x00007ffff7958b46 in MVM_spesh_candidate_add (tc=0x555555622460, p=0x7ffff322fe00) at src/6model/reprs/MVMSpeshCandidate.c:249
    #15 0x00007ffff7949b1c in worker (tc=0x555555622460, arg_info=...) at src/spesh/worker.c:29
    #16 0x00007ffff782f11b in thread_initial_invoke (tc=0x555555622460, data=0x555555630a60) at src/core/threads.c:68
    #17 0x00007ffff77dc336 in MVM_interp_run (tc=0x555555622460, initial_invoke=0x7ffff782f056 <thread_initial_invoke>, invoke_data=0x555555630a60, outer_runloop=0x0) at src/core/interp.c:177
    #18 0x00007ffff782f1ef in start_thread (data=0x555555630a60) at src/core/threads.c:101
    #19 0x00007ffff7262609 in start_thread (arg=<optimized out>) at pthread_create.c:477
    #20 0x00007ffff74ed293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
    (gdb) info threads
      Id   Target Id                                           Frame 
      1    Thread 0x7ffff7252440 (LWP 96013) "moar"            futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55555555a380) at ../sysdeps/nptl/futex-internal.h:183
    * 2    Thread 0x7ffff720e700 (LWP 96014) "spesh optimizer" MVM_panic (exitCode=0, messageFormat=0x0) at src/core/exceptions.c:840
    (gdb) f 5
    #5  0x00007ffff793c483 in analyze_phi (tc=0x555555622460, g=0x7ffff2eef920, ins=0x7fffe851605e) at src/spesh/optimize.c:2021
    2021	            target_facts->log_guards = MVM_spesh_alloc(tc, g, total_log_guards * sizeof(MVMint32));
    (gdb) l
    2016	        /*fprintf(stderr, "\n");*/
    2017	
    2018	        if (total_log_guards) {
    2019	            MVMuint32 insert_pos = 0;
    2020	            target_facts->num_log_guards = total_log_guards;
    2021	            target_facts->log_guards = MVM_spesh_alloc(tc, g, total_log_guards * sizeof(MVMint32));
    2022	            for (operand = 1; operand < ins->info->num_operands; operand++) {
    2023	                cur_operand_facts = get_facts_direct(tc, g, ins->operands[operand]);
    2024	                if (cur_operand_facts->num_log_guards) {
    2025	                    memcpy(target_facts->log_guards + insert_pos, cur_operand_facts->log_guards,
    (gdb) p total_log_guards
    $1 = 4087843256
    (gdb) 

the commit which caused/revealed this problem seems to be 4310520f0e. jnthn suspects that the change, which enables more optimizations to take place, might simply have revealed a problem which has gone unnoticed until now.

**Comment by MasterDuke17** [comment]
The backtrace for the invalid owner version looks like this for me:
```
ok 554 - distinct Complex literals do not compare the same
[Switching to Thread 0x7ffff7196640 (LWP 147675)]

Thread 2 "spesh optimizer" hit Breakpoint 1, MVM_panic (exitCode=exitCode@entry=1, messageFormat=messageFormat@entry=0x7ffff79ec058 "Invalid owner in item added to GC worklist") at src/core/exceptions.c:840
840     MVM_NO_RETURN void MVM_panic(MVMint32 exitCode, const char *messageFormat, ...) {
(gdb) bt
#0  MVM_panic (exitCode=exitCode@entry=1, messageFormat=messageFormat@entry=0x7ffff79ec058 "Invalid owner in item added to GC worklist") at src/core/exceptions.c:840
#1  0x00007ffff792156b in MVM_spesh_graph_mark (tc=tc@entry=0x555555621660, g=0x7ffff01456c0, worklist=worklist@entry=0x7ffff0c3eae0) at src/spesh/graph.c:1510
#2  0x00007ffff78a42f1 in MVM_gc_root_add_tc_roots_to_worklist (tc=tc@entry=0x555555621660, worklist=worklist@entry=0x7ffff0c3eae0, snapshot=snapshot@entry=0x0) at src/gc/roots.c:222
#3  0x00007ffff78a67cb in MVM_gc_collect (tc=0x555555621660, what_to_do=<optimized out>, gen=<optimized out>) at src/gc/collect.c:121
#4  0x00007ffff78a034a in run_gc (tc=tc@entry=0x555555621660, what_to_do=what_to_do@entry=1 '\001') at src/gc/orchestrate.c:444
#5  0x00007ffff78a0b9a in MVM_gc_enter_from_interrupt (tc=0x555555621660) at src/gc/orchestrate.c:734
#6  0x00007ffff79422f8 in spesh_gc_point (tc=0x555555621660) at src/6model/reprs/MVMSpeshCandidate.c:191
#7  MVM_spesh_candidate_add (tc=tc@entry=0x555555621660, p=0x7fffe8b650b0) at src/6model/reprs/MVMSpeshCandidate.c:250
#8  0x00007ffff79389b9 in worker (tc=0x555555621660, arg_info=...) at src/spesh/worker.c:29
#9  0x00007ffff788215d in thread_initial_invoke (tc=0x555555621660, data=<optimized out>) at src/core/threads.c:68
#10 0x00007ffff78550bb in MVM_interp_run (tc=0x1, tc@entry=0x555555621660, initial_invoke=0x7ffff79ec058, initial_invoke@entry=0x7ffff7882100 <thread_initial_invoke>, invoke_data=0x7ffff79ec058, 
    invoke_data@entry=0x7ffff7882100 <thread_initial_invoke>, outer_runloop=0x360, outer_runloop@entry=0x0) at src/core/interp.c:177
#11 0x00007ffff7882229 in start_thread (data=0x55555562fc60) at src/core/threads.c:101
#12 0x00007ffff72e7259 in start_thread () from /usr/lib/libpthread.so.0
#13 0x00007ffff75415e3 in clone () from /usr/lib/libc.so.6
(gdb)
```

**Comment by niner** [comment]
Fixed by merge of https://github.com/MoarVM/MoarVM/pull/1610
