### ISSUE TITLE
We should consider bundling+using mimalloc (and maybe even getting rid of the FSA)

### ISSUE THREAD

**Issue by MasterDuke17** [MoarVM/MoarVM#1623]
I just ran some benchmarks of two different conditions, and each of those conditions at stock and with mimalloc 2.0.3 (https://github.com/microsoft/mimalloc) LD_PRELOADed. For each combination I ran five times and included all the numbers in the table below. These weren't done in a 100% rigorous manner, but I tried to keep the execution environment pretty similar across the various runs. For the `*_fsa_debug_*` runs I used this patch https://gist.github.com/MasterDuke17/e91e9d6d37ec09d110972d39e8c41545 to roughly see what would happen if we got rid of the FSA altogether and just relied on mimalloc. A quick tl;dr is that mimalloc pretty much beats stock everywhere, and in fact, it looks like mimalloc+fsa_debug (i.e., the FSA just punting to the regular MMV_* functions) might even be the fastest.

  | CORE.c stage parse | m-test | m-spectest | MVM_SPESH_BLOCKING=1 raku -e ''
-- | -- | -- | -- | --
stock | 40.786<br>40.499<br>40.747<br>40.696<br>40.575 | 21<br>19<br>19<br>19<br>19 | 172<br>165<br>165<br>165<br>165 | 9572921783 instructions (10 iterations)<br>1833 (100 iterations)
stock+fsa_debug | 43.452<br>44.879<br>44.019<br>44.043<br>44.212 | 22<br>19<br>19<br>20<br>20 | 179<br>173<br>175<br>173<br>174 | 9597148610 instructions (10 iterations)<br>1775 (100 iterations)
mimalloc | 39.413<br>38.799<br>38.787<br>39.159<br>38.787 | 20<br>18<br>18<br>18<br>18 | 160<br>154<br>153<br>154<br>154 | 8677884655 instructions (10 iterations)<br>1657 (100 iterations)
mimalloc+fsa_debug | 38.746<br>38.542<br>39.499<br>39.251<br>38.943 | 20<br>17<br>17<br>18<br>17 | 159<br>154<br>153<br>154<br>154 | 8604038353 instructions (10 iterations)<br>1616 (100 iterations)

**Comment by jnthn** [comment]
This looks promising. If you have time and interest, a benchmark of how this does in producer/consumer situations where memory is allocated on one thread and freed on another (anything that heavily uses the `ThreadPool` probably does) could be interesting too.

If it lets us discard the FSA, the win is probably bigger than shown here, since the debug mode does checks and in places we probably pay for tracking the size.

The license seems fine; how is portability?

**Comment by MasterDuke17** [comment]
> If it lets us discard the FSA, the win is probably bigger than shown here, since the debug mode does checks and in places we probably pay for tracking the size.

I tried to remove the checks and not use the struct with the size in my patch, so the debug mode as I was using it pretty much just calls the corresponding non-FSA function with the same arguments.

> The license seems fine; how is portability?

I'm not sure. It's from Microsoft, so I'm going to assume it works fine on Windows. https://github.com/microsoft/mimalloc/issues/482 has some more info, here are some selected quotes:
"Currently, there are 2 tiers: the 'official' supported ones that are always tested and used widely (e.g. Windows x64, Linux x64/arm64, and macOS x64/M1), and the rest"
"Mimalloc has robust support on Windows, and recently the macOS zone based overriding is also getting more robust. Linux/FreeBSD works well with LD_PRELOAD."

**Comment by MasterDuke17** [comment]
> This looks promising. If you have time and interest, a benchmark of how this does in producer/consumer situations where memory is allocated on one thread and freed on another (anything that heavily uses the `ThreadPool` probably does) could be interesting too.

Do you have anything I could try or is there something in the ecosystem I can use? I don't have any code like that at hand that I've written.

**Comment by MasterDuke17** [comment]
Realized I hadn't done any max mem measurements, so just did some for the CORE.c compile. So there is a downside to mimalloc, slightly increased memory use.

<table>
<tr>
	<td>
	<td>Max resident for CORE.c
<tr>
	<td>stock
	<td>1664736<br>1651636<br>1657592
<tr>
	<td>stock+fsa_debug
	<td>1661864<br>1673336<br>1673488
<tr>
	<td>mimalloc
	<td>1684504<br>1685644<br>1684676
<tr>
	<td>mimalloc+fsa_debug
	<td>1681764<br>1679736<br>1680976
</table>

**Comment by MasterDuke17** [comment]
Implemented with the merge of https://github.com/MoarVM/MoarVM/pull/1638
