### ISSUE TITLE
MoarVM panic when running t/05-messages/03-errors.t with MVM_GC_DEBUG=3 and MVM_SPESH_NODELAY=1

### ISSUE THREAD

**Issue by dogbert17** [MoarVM/MoarVM#1628]
dogbert@dogbert-VirtualBox:~/repos/rakudo$ MVM_SPESH_NODELAY=1 ./rakudo-gdb-m -Ilib t/05-messages/03-errors.t
    ================================================================================================
    This is Rakudo running in the  debugger, which often allows the user to generate useful back-
    traces to debug or report issues in Rakudo, the MoarVM backend or the currently running code.
    
    This Rakudo version is 2021.12.25.g.560868695 built on MoarVM version 2021.12,
    running on linuxmint (20.Ulyana) / linux
    
    Type `bt full` to generate a backtrace if applicable, type `q` to quit or `help` for help.
    ------------------------------------------------------------------------------------------------
    Reading symbols from /home/dogbert/repos/rakudo/nqp/MoarVM/../../install/bin/moar...
    Starting program: /home/dogbert/repos/rakudo/install/bin/moar --execname=/home/dogbert/repos/rakudo/rakudo-gdb-m --libpath=/home/dogbert/repos/rakudo --libpath=/home/dogbert/repos/rakudo/blib --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib /home/dogbert/repos/rakudo/perl6.moarvm -Ilib t/05-messages/03-errors.t
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
    [New Thread 0x7ffff71fe700 (LWP 715419)]
    ^C
    Thread 1 "moar" received signal SIGINT, Interrupt.
    futex_wake (private=<optimized out>, processes_to_wake=2147483647, futex_word=<optimized out>) at ../sysdeps/nptl/futex-internal.h:364
    364	../sysdeps/nptl/futex-internal.h: No such file or directory.
    (gdb) b MVM_panic
    Breakpoint 1 at 0x7ffff77caffb: file src/core/exceptions.c, line 840.
    (gdb) c
    Continuing.
    1..25
    # Subtest: using substr instead of subst
        1..3
        ok 1 - ''x'.substr: /x/, 'x'' died
        ok 2 - right exception type (Exception)
        ok 3 - .message matches /｢did you mean 'subst'｣/
    ok 1 - using substr instead of subst
    
    ... [output from several tests removed]
    
    # Subtest: X::TypeCheck does not prematurely chop off the .raku
        1..3
        ok 1 - '
        #     my class Supercalifragilisticexpialidocious {};
        #     (my $x := my class {}.new).^set_name: <Supercalifragilisticexpialidocious>;
        #     -> Supercalifragilisticexpialidocious {}($x)
        # ' died
        ok 2 - right exception type (X::TypeCheck)
    
    Thread 1 "moar" hit Breakpoint 1, MVM_panic (exitCode=0, messageFormat=0x0) at src/core/exceptions.c:840
    840	MVM_NO_RETURN void MVM_panic(MVMint32 exitCode, const char *messageFormat, ...) {
    (gdb) bt
    #0  MVM_panic (exitCode=0, messageFormat=0x0) at src/core/exceptions.c:840
    #1  0x00007ffff7869e72 in MVM_gc_root_add_frame_registers_to_worklist (tc=0x55555555ae30, worklist=0x55555e07f9d0, frame=0x7ffff72272d8) at src/gc/roots.c:456
    #2  0x00007ffff7869cc3 in MVM_gc_root_add_frame_roots_to_worklist (tc=0x55555555ae30, worklist=0x55555e07f9d0, cur_frame=0x7ffff72272d8) at src/gc/roots.c:429
    #3  0x00007ffff78278fd in mark (tc=0x55555555ae30, from_record=0x7ffff7228240, worklist=0x55555e07f9d0, snapshot=0x0) at src/core/callstack.c:915
    #4  0x00007ffff78297c8 in MVM_callstack_mark_current_thread (tc=0x55555555ae30, worklist=0x55555e07f9d0, snapshot=0x0) at src/core/callstack.c:1046
    #5  0x00007ffff7865e9a in MVM_gc_root_add_tc_roots_to_worklist (tc=0x55555555ae30, worklist=0x55555e07f9d0, snapshot=0x0) at src/gc/roots.c:155
    #6  0x00007ffff786aa6f in MVM_gc_collect (tc=0x55555555ae30, what_to_do=0 '\000', gen=0 '\000') at src/gc/collect.c:121
    #7  0x00007ffff786022e in run_gc (tc=0x55555555ae30, what_to_do=0 '\000') at src/gc/orchestrate.c:444
    #8  0x00007ffff7860908 in MVM_gc_enter_from_allocator (tc=0x55555555ae30) at src/gc/orchestrate.c:599
    #9  0x00007ffff7861463 in MVM_gc_allocate_nursery (tc=0x55555555ae30, size=40) at src/gc/allocation.c:37
    #10 0x00007ffff7861233 in MVM_gc_allocate (tc=0x55555555ae30, size=40) at src/gc/allocation.h:15
    #11 0x00007ffff7861258 in MVM_gc_allocate_zeroed (tc=0x55555555ae30, size=40) at src/gc/allocation.h:21
    #12 0x00007ffff786181e in MVM_gc_allocate_object (tc=0x55555555ae30, st=0x5555555c43a0) at src/gc/allocation.c:86
    #13 0x00007ffff788bd46 in MVM_repr_alloc (tc=0x55555555ae30, type=0x5555555cdd10) at src/6model/reprconv.c:13
    #14 0x00007ffff78ea4a0 in MVM_capture_from_args (tc=0x55555555ae30, arg_info=...) at src/6model/reprs/MVMCapture.c:121
    #15 0x00007ffff79086d6 in MVM_disp_program_run_dispatch (tc=0x55555555ae30, disp=0x555557a54ea0, arg_info=..., ic_entry_ptr=0x55555dcca518, ic_entry=0x55555dcd1b40, update_sf=0x555557675170)
        at src/disp/program.c:571
    #16 0x00007ffff7905cbb in dispatch_initial (tc=0x55555555ae30, entry_ptr=0x55555dcca518, seen=0x55555dcd1b40, id=0x555557fe48b0, callsite=0x7ffff7e50a20 <obj_callsite>, arg_indices=0x7ffff59d87d8, 
        source=0x7ffff72282f8, sf=0x555557675170, bytecode_offset=94) at src/disp/inline_cache.c:79
    #17 0x00007ffff7905e8b in dispatch_monomorphic (tc=0x55555555ae30, entry_ptr=0x55555dcca518, seen=0x55555dcd1b40, id=0x555557fe48b0, callsite=0x7ffff7e50a20 <obj_callsite>, arg_indices=0x7ffff59d87d8, 
        source=0x7ffff72282f8, sf=0x555557675170, bytecode_offset=94) at src/disp/inline_cache.c:114
    #18 0x00007ffff78045f4 in MVM_interp_run (tc=0x55555555ae30, initial_invoke=0x7ffff79b8749 <toplevel_initial_invoke>, invoke_data=0x5555556183d0, outer_runloop=0x0) at src/core/interp.c:5345
    #19 0x00007ffff79b88af in MVM_vm_run_file (instance=0x55555555a2a0, filename=0x7fffffffe215 "/home/dogbert/repos/rakudo/perl6.moarvm") at src/moar.c:505
    #20 0x0000555555555c97 in main (argc=8, argv=0x7fffffffdd98) at src/main.c:307
    (gdb) f 1
    #1  0x00007ffff7869e72 in MVM_gc_root_add_frame_registers_to_worklist (tc=0x55555555ae30, worklist=0x55555e07f9d0, frame=0x7ffff72272d8) at src/gc/roots.c:456
    456	                MVM_gc_worklist_add(tc, worklist, &frame->work[i].o);
    (gdb) l
    451	            type_map = frame->static_info->body.local_types;
    452	            count    = frame->static_info->body.num_locals;
    453	        }
    454	        for (i = 0; i < count; i++)
    455	            if (type_map[i] == MVM_reg_str || type_map[i] == MVM_reg_obj)
    456	                MVM_gc_worklist_add(tc, worklist, &frame->work[i].o);
    457	    }
    458	}
    459	
    460	/* Takes a frame, scans its lexicals and adds them to the roots. */
    (gdb) info threads
      Id   Target Id                                            Frame 
    * 1    Thread 0x7ffff7242440 (LWP 715415) "moar"            0x00007ffff7869e72 in MVM_gc_root_add_frame_registers_to_worklist (tc=0x55555555ae30, worklist=0x55555e07f9d0, frame=0x7ffff72272d8)
        at src/gc/roots.c:456
      2    Thread 0x7ffff71fe700 (LWP 715419) "spesh optimizer" futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55555555a3bc) at ../sysdeps/nptl/futex-internal.h:183
      3    Thread 0x7fffecb8c700 (LWP 715438) "moar"            futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x555555611e88) at ../sysdeps/nptl/futex-internal.h:183
      4    Thread 0x7fffe7fff700 (LWP 715439) "moar"            0x00007ffff749b3bf in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=0x7fffe7ffd110, rem=0x7fffe7ffd110)
        at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
      5    Thread 0x7fffe77fe700 (LWP 715440) "async io thread" futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55555555a3bc) at ../sysdeps/nptl/futex-internal.h:183
      6    Thread 0x7fffe6ffd700 (LWP 715450) "moar"            futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x5555556120e8) at ../sysdeps/nptl/futex-internal.h:183
      7    Thread 0x7fffe67fc700 (LWP 715473) "moar"            futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x5555556120e8) at ../sysdeps/nptl/futex-internal.h:183
    (gdb) c
    Continuing.
    MoarVM panic: Invalid owner in item added to GC worklist
    [Thread 0x7fffe67fc700 (LWP 715473) exited]
    [Thread 0x7fffe77fe700 (LWP 715440) exited]
    [Thread 0x7fffe7fff700 (LWP 715439) exited]
    [Thread 0x7fffecb8c700 (LWP 715438) exited]
    [Thread 0x7ffff71fe700 (LWP 715419) exited]
    [Thread 0x7ffff7242440 (LWP 715415) exited]
    [Inferior 1 (process 715415) exited with code 01]

**Comment by niner** [comment]
@dogbert17 this should be fixed by https://github.com/MoarVM/MoarVM/commit/2883ba7547833222962a0a57bb7d921817924dc0
Can you confirm?

**Comment by dogbert17** [comment]
@niner yes it works perfectly now
