### ISSUE TITLE
Unable to use sockets from thread other than creating thread

### ISSUE THREAD

**Issue by hoelzro** [MoarVM/MoarVM#165]
If you try to use a socket from a thread other than the thread in which that socket was created, the `read` method will always return an empty buffer:

``` perl6
use v6;

# run this script with the following running in a separate termainal
# (using OpenBSD netcat):
#
#     nc -l localhost 9000 </dev/zero

my $sock = IO::Socket::INET.new(
    :host<localhost>,
    :port(9000),
);

my $p = start {
    # this read will always be empty unless the socket creation is
    # moved inside of the start block
    say $sock.read(8);
    42;
}

$p.result;
```

I should also note that in the program in which I found this behavior, `read` just blocks forever.

**Comment by tony-o** [comment]
Was this merged into moar?

**Comment by hoelzro** [comment]
@tony-o I don't think so; it seems like there are outstanding issues with it.

**Comment by tony-o** [comment]
Interesting. I wonder if this would affect pipes in general, there is a similar issue with opening a proc::asynchronous and that sub process not being able to read from stdin unless it's in the main thread

Sent from a phone




On Wed, May 27, 2015 at 9:27 AM -0700, "Rob Hoelz" <notifications@github.com<mailto:notifications@github.com>> wrote:


@tony-o<https://github.com/tony-o> I don't think so; it seems like there are outstanding issues with it.

-

**Comment by hoelzro** [comment]
I just encountered this again while writing a script that shells out to `pandoc` to render some text.  @jnthn Any hopes for a fix?

**Comment by hoelzro** [comment]
When using files, the bug (for me, anyway) is *not* the same as the socket issue; it's that I have an exception that `Supply.tap` is ignoring.  Here's some sample code:

```perl6
my $fh = open('numbers', :w);
my $timer = Supply.interval(1);
$timer.tap(-> $n {
  $fh.write: ($n ~ "\n");
});
sleep 3;
close $fh;
```

`numbers` ends up empty, but it's because I didn't encode `$n ~ "\n"` when writing to the file.  Doing that fixes the issue for files.  @tony-o Is that the issue you were seeing?  I can't seem to find the RT ticket for this =/

**Comment by hoelzro** [comment]
Ah, here we are: https://rt.perl.org/Ticket/Display.html?id=125230

**Comment by tony-o** [comment]
@hoelzro nah, my problem isn't related to swallowing errors although I experienced that too with some other stuff and didn't think it was actually a bug.

**Comment by hoelzro** [comment]
The more I look at this and RT #125230 the more I think they are separate issues...

**Comment by MadcapJake** [comment]
I've run into this problem myself when trying to use channels in a shakespeare character counter https://gist.github.com/MadcapJake/c29b76d7eccf5af86e973c5da7c7f7a3#file-workers-pl6

Not quite sure this is relevant to the issue but this is the error I get:
```
Tried to read() on a socket from outside its originating thread
```

**Comment by hoelzro** [comment]
@MadcapJake That's an error I added to MoarVM so that users would see a hard failure instead of scratching their heads for an hour trying to figure out why their reads were always short. =)

**Comment by scovit** [comment]
I've been running into this error message when trying to do `my $stdinput = $*IN.Supply;` and then use it into an async socket connection. Workarounded by using something better:
```perl6
my $stdinput = {my $insupplier=Supplier.new;use Readline;start {my $rl = Readline.new;while my $msg = $rl.readline("") {$insupplier.emit($msg);}}; $insupplier.Supply; }();
```

**Comment by zoffixznet** [comment]
Here's another place this presents an issue. Trying to read from STDOUT from another thread:

```
$ perl6 -e 'await start get'
Tried to read() on a socket from outside its originating thread
  in block <unit> at -e line 1
dsdsds
```

**Comment by jnthn** [comment]
https://rt.perl.org/Ticket/Display.html?id=129787 also golfs to this issue.

**Comment by jnthn** [comment]
This is now fixed for the case of sockets; file handles are still to come. The socket part of the fix is [covered by an added spectest](https://github.com/perl6/roast/commit/a5a46acfd4).

**Comment by jnthn** [comment]
In MoarVM HEAD, it is now addressed for file handles too, and TTYs and pipes now use the code in `syncfile.c`.

**Comment by jnthn** [comment]
All process handling in Rakudo is now done in terms of the async process API, which makes sense in that MoarVM was supporting two APIs that were both backed with the libuv async API anyway, but with one of them having the trouble discussed in this issue.

I've just removed the synchronous process bits from MoarVM, and therefore I believe this issue can be counted as fully resolved. We could with a little further effort also eliminate the `tc->loop` except for in the case of the event loop thread, but I don't believe any of the current remaining uses are problematic.
