### ISSUE TITLE
Various threading exceptions

### ISSUE THREAD

**Issue by tgt** [MoarVM/MoarVM#166]
```
my $n = 5;

my @locks = Lock.new xx $n;
                     
await do for ^$n -> $i {
    start {
        @locks[$i].lock;
        my $j = @locks[($i + 1) % $n];
    }
}
```

The above code causes a variety of exceptions to be thrown:

    Unhandled exception: No such method 'lock' for invocant of type 'Any'
    Unhandled exception: MVMArray: Can't shift from an empty array
    Unhandled exception in code scheduled on thread 4474798080

I've also seen it segfault, although this is much rarer than he above exceptions. Sometimes it runs to completion.

I'm running on OS X 10.10.1 and "This is perl6 version 2014.12-142-g8f447f8 built on MoarVM version 2014.12-4-g7e95c05"

**Comment by timo** [comment]
I've been able to run this many times now without a problem. Likely fixed when jnthn found and fixed a few race conditions and other such problems in moar a few months ago. closing as resolved.

**Comment by tgt** [comment]
I can still see this issue. In 100 attempts it occurred three times. Rather than the above errors occurring I now get `Cannot invoke this object (REPR: Null)`.
