### ISSUE TITLE
Please update 3rdparty/dyncall to get AArch64 support

### ISSUE THREAD

**Issue by hrw** [MoarVM/MoarVM#170]
Dyncall upstream has aarch64 (64-bit armv8) architecture support which is needed to get MoarVM built for AArch64.

I managed to get MoarVM built for this architecture with just replacing dyncall dir with latest upstream.

Failed Fedora build: http://arm.koji.fedoraproject.org/koji/taskinfo?taskID=2861153

**Comment by zhuomingliang** [comment]
Hello,
I bumped dyncall version. Please try again, thanks.

**Comment by FROGGS** [comment]
@zhuomingliang How did you do that? I tried to figure it out yesterday without luck.

**Comment by hrw** [comment]
Builds fine. Time for new release so distributions have something to update to?

**Comment by zhuomingliang** [comment]
@FROGGS https://github.com/MoarVM/dyncall/wiki

**Comment by jnthn** [comment]
@hrw We do time-based releases; there'a  new one each month. So it'll be in the next monthly in February.
