### ISSUE TITLE
src/io/syncsocket.c:287:38: error: 'AI_NUMERICSERV' undeclared (first use in this function)

### ISSUE THREAD

**Issue by barracuda156** [MoarVM/MoarVM#1704]
`MoarVM` fails to update to 2022.04 on 10.6 (build for `ppc`):
```
src/io/syncsocket.c: In function 'MVM_io_resolve_host_name':
src/io/syncsocket.c:287:38: error: 'AI_NUMERICSERV' undeclared (first use in this function); did you mean 'NI_NUMERICSERV'?
  287 |     hints.ai_flags = AI_ADDRCONFIG | AI_NUMERICSERV | AI_PASSIVE;
      |                                      ^~~~~~~~~~~~~~
      |                                      NI_NUMERICSERV
src/io/syncsocket.c:287:38: note: each undeclared identifier is reported only once for each function it appears in
src/io/syncsocket.c: At top level:
cc1: note: unrecognized command-line option '-Wno-logical-op-parentheses' may have been intended to silence earlier diagnostics
make: *** [src/io/syncsocket.o] Error 1
```
Config line:
```
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_lang_MoarVM/MoarVM/work/MoarVM-2022.04" && /opt/local/bin/perl Configure.pl --prefix=/opt/local --cc=/opt/local/bin/gcc-mp-11 --has-dyncall --has-libatomic_ops --has-libtommath --has-libuv --no-mimalloc
```

**Comment by niner** [comment]
Is this about Mac OS X 10.6? According to Wikipedia that has been out of support from Apple for more than 8 years already.

**Comment by barracuda156** [comment]
Yes, but this error is probably fixable for 10.6. The previous version of MoarVM has built fine.
```
36-111% port -v installed moarvm
The following ports are currently installed:
  MoarVM @2022.02_0 requested_variants='' platform='darwin 10' archs='ppc' date='2022-03-22T08:10:05+0800'
  MoarVM @2022.02_1 (active) requested_variants='' platform='darwin 10' archs='ppc' date='2022-04-16T16:01:15+0800'
```
P. S. I was going to update the port in Macports, but ran into this problem. We need to fix it for PPC systems, they are supported by Macports.

**Comment by niner** [comment]
We have used AI_NUMERICSERV since 2019, so it looks like a build tool chain issue. Maybe it's using the wrong compiler or libc or something like that?

**Comment by barracuda156** [comment]
> We have used AI_NUMERICSERV since 2019, so it looks like a build tool chain issue. Maybe it's using the wrong compiler or libc or something like that?

It might be that I had `gcc11` updated from 11.2.0 to 11.3.0 since then, but I use it on a daily basis and it works fine.

**Comment by patrickbkr** [comment]
I bet this is somehow related to https://github.com/rakudo/rakudo/pull/4045#issuecomment-1117545582. That issue was on Windows, but it's the exact same constant that was missing.

**Comment by barracuda156** [comment]
> I bet this is somehow related to [rakudo/rakudo#4045 (comment)](https://github.com/rakudo/rakudo/pull/4045#issuecomment-1117545582). That issue was on Windows, but it's the exact same constant that was missing.

@patrickbkr Thank you, yes, it is perhaps related.

**Comment by barracuda156** [comment]
Hopefully the PR gets accepted, and I close the issue as resolved.
