### ISSUE TITLE
`return` in `LEAVE` misses handler in directly surounding scope

### ISSUE THREAD

**Issue by patrickbkr** [MoarVM/MoarVM#1784]
```
sub s() {
    LEAVE return 5;
    return 7;
}
s()
```
gives

> Attempt to return outside of any Routine
>   in sub s at leave-bug.raku line 2
>   in block <unit> at leave-bug.raku line 5

I've dug into this a bit.
From what I've understood, the `return 7` starts an unwind. The exit handler of `s()` is found and called via `MVM_frame_dispatch_from_c`. That in turn sets `cur_frame->return_address` to `*(tc->interp_cur_op)` which still points to someplace in `&return`. The `return 5` then searches for an applicable handler in the call stack, but misses the one of `s()` because `cur_frame->return_address` is then usually outside of the handlers corresponding area.

The best idea I could come up with to fix this is setting a sane `cur_frame->return_address` before calling the exit handler. But I don't know what a sane value could be. The value will not be used to return to (we already have a handler we are unwinding to), but needs to meet  `pc >= fh->start_offset && pc <= fh->end_offset` (that's in [exceptions.c search_frame_handlers_lex](https://github.com/MoarVM/MoarVM/blob/main/src/core/exceptions.c#L251)). I think the `LEAVE` doesn't  even have a representation in the bytecode.

Hm. It's hacky, but something like the following could do the trick:
```
if (cur_frame == fh->frame) {
    cur_frame->return_address = fh->start_offset;
}
```
I do hope for a better idea though.

**Comment by lizmat** [comment]
Is this PR obsolete now?

**Comment by patrickbkr** [comment]
@lizmat This is an issue, not a PR. ;-)

**Comment by lizmat** [comment]
Duh  :-)
