### ISSUE TITLE
Blocking on `ConcBlockingQueue` blocks signals

### ISSUE THREAD

**Issue by lizmat** [MoarVM/MoarVM#1814]
The following code:
```raku
use nqp;
my class P is repr("ConcBlockingQueue") { }
my $p := nqp::create(P);
nqp::shift($p);
```
blocks forever, as there's nothing being pushed on the queue.  That is to be expected.

However, this **also** blocks any signals, which manifests itself with the above program not being interruptable by pressing Control-C.

Adding a signal handler:
```raku
signal(SIGINT).tap: { say "Thank you for your attention"; exit 0 } 
```
does **not** change the situation.

One would expect any signals to be handled.

**Comment by lizmat** [comment]
@Leont does this ring a bell?

**Comment by Leont** [comment]
I don't know anything about `ConcBlockingQueue`, but my educated guess would be: the signal is arriving in a different thread from the one that's blocking. It's not wrong that it doesn't get interrupted.

I'm not sure why the tap wouldn't trigger though. Possibly Rakudo is trying to exit but that single thread is waiting on its queue even though all other threads have ended already?

**Comment by lizmat** [comment]
> I'm not sure why the tap wouldn't trigger though. Possibly Rakudo is trying to exit but that single thread is waiting on its queue even though all other threads have ended already?

The `say` in the example, also doesn't show.  So I'd guess it's not blocking on that.

Also, if this block happens outside of the main thread, normal mainline exit does just that: exit.

**Comment by lizmat** [comment]
Turns out some of my Terminal windows and/or ssh connections got in a weird state.

I cannot reproduce these on fresh Terminal windows / ssh connections, so closing this.
