### ISSUE TITLE
JIT issue with new version of .flat

### ISSUE THREAD

**Issue by lizmat** [MoarVM/MoarVM#1817]
Steps to reproduce (on Intel boxes):

1. checkout rakudo 2024.06
2. revert 739559906a6409f1e88301fdf92c0e227f8d0752
3. build rakudo  (it *may* already crash when installing modules)
4. run `raku t/spec/S17-promise/start.t`

For me, it reliably fails with:
```
...
ok 59 - No data races on closure interpolation in strings
An operation first awaited:
  in block <unit> at t/spec/S17-promise/start.t line 261

Died with the exception:
    Can only specify Awaitable objects to await (got a List)
      in block <unit> at t/spec/S17-promise/start.t line 261
```

5. run `MVM_JIT_DISABLE=1 raku t/spec/S17-promise/start.t`

Tests complete ok.

**Comment by lizmat** [comment]
I've been able to golf this to:
```raku
my %h = :1a,:2b,:3c,:4d;
while (1,2,3,4,"a","b","c","d") eq (%h{*}:kv).sort {
    say ++$
}
```
This generally stops after 17 iterations for me.  Runs forever with `MVM_SPESH_DISABLE=1`.

Mind you, it is **STRANGE** that on Apple Silicon (M1) this runs without any problems, while I *do* think that spesh is enabled on non-Intel hardware, is it not?

Or is `MVM_SPESH_DISABLE=1` also disabling JIT?  I forgot  :-(

**Comment by MasterDuke17** [comment]
Yeah, I think disabling spesh also disables the jit.Sent from my iPhoneOn Jun 29, 2024, at 2:11 PM, Elizabeth Mattijsen ***@***.***> wrote:﻿
I've been able to golf this to:
my %h = :1a,:2b,:3c,:4d;
while (1,2,3,4,"a","b","c","d") eq (%h{*}:kv).sort {
    say ++$
}
This generally stops after 17 iterations for me.  Runs forever with MVM_SPESH_DISABLE=1.
Mind you, it is STRANGE that on Apple Silicon (M1) this runs without any problems, while I do think that spesh is enabled on non-Intel hardware, is it not?
Or is MVM_SPESH_DISABLE=1 also disabling JIT?  I forgot  :-(

**Comment by lizmat** [comment]
Looking at the code I wrote and trying a few changes, I wonder whether it could be the use of `nqp::decont` in a numerical, rather than a boolean way.

**Comment by patrickbkr** [comment]
Honest question:
Should we perspectively move away from our JIT? It's a complex beast, there is currently no one able to maintain it and it has known bugs, one of which nine deems so ugly he actively refrains from looking at (ISTR the code the exprJIT generates is in some constellations racy).

Also the performance gains it gives us are not tremendous. The tremendous gains we can absolutely not do without lie in spesh. Of note: There is no JIT on Arm, including the latest Apple devices. As of yet I didn't notice complaints about unusable perf there.

Long term we can consider getting an "off the shelf" JIT library in place. That won't give us the best possible performance, but does help a bit and is a lot more maintainable (libgccjit was once proposed as a candidate).

I think it's a bad idea to disable the JIT by default, as that will speed up its bit rot. I believe that large parts of the infrastructure surrounding the JIT are valuable to keep (e.g. deopt).

So maybe we can keep it running but be honest about the "not maintained" part and in case of a JIT issue just out right recommend "MVM_JIT_DISABLE=1".

Question to those more versed in our JIT (@bdw, @jnthn, @niner, @MasterDuke17 - bdw & jnthn: Please feel free to ignore this question if it is an annoyance to you.): Would it alternatively make more sense to rip out the ExprJIT and keep the LegoJIT? I.e. How reliable is the LegoJIT? How maintainable is it? Is there supporting infrastructure we'd want to keep, tied to the ExprJIT exclusively?

**Comment by lizmat** [comment]
> There is no JIT on Arm, including the latest Apple devices. As of yet I didn't notice complaints about unusable perf there.

For reference: an M1 without JIT outperforms a 2.4GHz Intel i9 (with JIT) by a factor of **1.6**.

**Comment by niner** [comment]
Well to be honest I have given up hope on the expression JIT. While it's a fascinating bit of technology, truth is that @bdw is the only one who really understands it. While in principle it's again just yet more compilery things with the only really new concept to learn being the register allocator, the implementation was done with compilation speed as a priority. Sadly that makes it nigh impossible for me to debug. When investigating the bug you mentioned, I failed to achieve enough of a mental model to make sense of those arrays of arrays of numbers that are the expr JIT compiler's state. The bus factor is practically 0 and we have to deal with this at some point.

The same is not true for the lego JIT. While the problem with it is that it's comparatively primitive, that's also its strength. Several people have managed to learn enough about it to extend it and debug issues with some lego blocks. While it's not the greatest solution and I'd be skeptical about building on it and porting it to other architectures, it does provide a decent benefit at relatively low maintenance cost. As to benchmarking the benefits, I'd like to point out that it's possible that the benefit is larger for NativeCall heavy code than it is for normal Raku code.

Ideally I would like to see both JITs replaced with some off-the-shelf component as that would probably give use both better performance and solve the maintenance problem. However, finding one that fits our needs is all but straight forward. In general you don't just want your JIT to produce fast code, but also to compiler reasonably quickly. This all but rules out the big ones like GCC or LLVM. Even if you are lenient with that requirement, an absolute must is for it to support a way to deoptimize. I.e. you need a way to jump out of byte code and be able to determine where exactly that happened and possibly also recover some state (i.e. contents of VM registers with writes that the JIT compiler optimized out). 

My personal prime candidate (suggested by @jnthn) is https://github.com/vnmakarov/mir?tab=readme-ov-file and I've kept checking in on it for a while. It ticks a lot of boxes and has been in active development for years. However it still has a rather low bus factor, so it's not a slam dunk. Of course if someone picks up MIR for MoarVM and inevitably starts contributing that alone may be enough to invigorate that project and set it on a conquer the world trajectory. Or it may not. The MIR page also lists several competitors that may be worth checking out.

All in all replacing the JIT would be a project that's not for the faint of heart, but certainly highly interesting and rewarding (even if it should ultimately fail). Until that happens I don't think the expr JIT survives an honest cost/benefit analysis, but the lego JIT does.

**Comment by bdw** [comment]
While it would pain me, I think ripping out the expression JIT might be a reasonable way forwards.
I second the point about the bus factor of 0 - that's on me, entirely, but it's also something I don't think will change, at least in the short term.

To be 100% frank, if I were to retire tomorrow - fat chance - I'm not even sure how much time I would spend on the expression JIT still.

It was at some point a goal of mine to extract the expression JIT into it's own library, with tests and a clear contract. That also never happened.

Regarding the topic of drop-in replacements in general, the challenge - as I see it - it will be very challenging to integrate it into the existing JIT infrastructure, which likely means you'll have to start from scratch, and this will be challenging without the ability to lay out the stack and code directly. For example it's never been obvious to me how to implement things like current-instruction-range detection, on which things like lexical variables and exception handling tend to depend, in a library like libgcc.

So, I would sanction disabling or removing the expression JIT.

**Comment by patrickbkr** [comment]
> My personal prime candidate (suggested by @jnthn) is https://github.com/vnmakarov/mir?tab=readme-ov-file and I've kept checking in on it for a while. It ticks a lot of boxes and has been in active development for years. However it still has a rather low bus factor, so it's not a slam dunk. Of course if someone picks up MIR for MoarVM and inevitably starts contributing that alone may be enough to invigorate that project and set it on a conquer the world trajectory. Or it may not. The MIR page also lists several competitors that may be worth checking out.

While the author has continued working on MIR itself, the original purpose of MIR is gone. Quoting [the 2023-10-09 plog post](https://developers.redhat.com/articles/2023/10/09/mir-based-jit-prototype-ruby) by the MIR author:

> The success of YJIT led to a pivotal decision by my management team and me: to discontinue work on the MIR-based JIT for CRuby.

AFAIK there currently is no project building on MIR. So while not dead, MIR is a project with an uncertain future currently.

**Comment by patrickbkr** [comment]
> For reference: an M1 without JIT outperforms a 2.4GHz Intel i9 (with JIT) by a factor of **1.6**.

Given that M1 really is really fast, that's not a fair comparison. Better would be to compare the same setup with and without the JIT disabled.

**Comment by patrickbkr** [comment]
Looking at the comments by nine and bdw, people seem to agree, that removing the exprJIT should be the way to go. I didn't expect such a clear answer to be honest.

**Comment by lizmat** [comment]
Apparently the [test-t canary](https://irclogs.raku.org/raku-dev/2024-07-10.html#07:42-0010) runs about 10% faster with the expression JIT disabled.  I have no explanation for this.  But I guess this could potentially be another factor on why rakudo on Apple Silicon is so much faster.

**Comment by MasterDuke17** [comment]
FWIW, on my Ryzen 3700x (8-core Zen 2), a normal spectest is ~200s and disabling the exprJIT drops that to ~195s. A normal compile of CORE.c takes ~63s and disabling the exprJIT drops that to ~60s. All tests are slower disabling the jit completely.

**Comment by patrickbkr** [comment]
I think the interpretation of the fact that ExprJIT slows runtime down at least in some cases must not be that ExprJIT is inherently bad. During the implementation measurements have been made and a perf improvement has at that time been verified. Also I believe in general the ExprJIT has the potential to improve the runtime. We've probably just over time changed stuff in a way that turned ExprJIT suboptimal and no one noticed. I'm pretty sure we could, in principle, find the issue and reclaim that performance.

That said, given the comments of bdw and nine, and the current perf situation, I propose the following way forward:

- Wait for @lizmat s test with the IRC server and disabled ExprJIT.
- Make `MVM_JIT_EXPR_DISABLE=1` the default.
- Wait for a release or two to collect feedback.
- Do the sad thing and remove the ExprJIT.
- We'll keep the LegoJIT.

**Comment by lizmat** [comment]
> Wait for @lizmat s test with the IRC server and disabled ExprJIT.

It'll be days if not weeks before anything conclusive.  Also, I'm more looking at memory usage rather than performance, as the IRC logs server keeps all logs in RAM, more or less  :-)
