### ISSUE TITLE
Allow ENV override of CFLAGS/LDFLAGS

### ISSUE THREAD

**Issue by coke** [MoarVM/MoarVM#182]
While working with the macports team to get the moarvm Portfile accepted, we had some trouble getting the universal variant to work, and this was brought up:

```
14:26 < Ionic> [Coke]: it would probably be nice to make cflags and ldflags
               customizable via the environment, though
14:27 < Ionic> we can try to re-enable universal then
```

**Comment by FROGGS** [comment]
What are the environment vars named exactly?

**Comment by coke** [comment]
Literally:

```
CFLAGS
```

and

```
LDFLAGS
```

**Comment by Ionic** [comment]
The flags we pass to configure are (for example):

Compilers:
`CC`, `CXX`, `OBJC`, `OBJCXX`,

Flags:
`CFLAGS`, `LDFLAGS`, `OBJCFLAGS`, `OBJCXXFLAGS`, `F77FLAGS`, `F90FLAGS`, `FCFLAGS`, `FFLAGS`

Misc (OS X specific or not widely known):
`MACOSX_DEPLOYMENT_TARGET`, `LIBRARY_PATH`

Of course, not all have to be respected. MoarVM does not use Fortran or ObjC, so those can be safely ignored.

**Comment by Ionic** [comment]
NB: not only to configure, but set as environment in all phases, including configure and build.
