### ISSUE TITLE
Add support for libffi (in addition to dyncall) for additional platform support (eg MIPS/IRIX, Power/AIX)

### ISSUE THREAD

**Issue by Ugator** [MoarVM/MoarVM#183]
7 Mar 2015 19:39Z &lt;nwc10> Ugator: I have tried building it on AIX. IIRC one or two of the dependecy libraries are a pain (not libuv). I don't think that dyncall supports AIX. IIRC libffi does - unless you know PPC assembler, I'd guess that the route of least resistance is actually to abstract the dynamic call stuff to be able to use dyncall or libffi. I think that would get us most of HP/UX too.

**Comment by FROGGS** [comment]
This is resolved via cfdd2455914d198a787a08533ce43d27d5a1a8ac
