### ISSUE TITLE
(should have been for rakudo instead ? , sorry ) make package asks for install-dist.p6,  rename  from *.raku may have not been working correctly,

### ISSUE THREAD

**Issue by makoto-fujiwara** [MoarVM/MoarVM#1854]
NetBSD/amd64, 10.99.12, pkgsrc environment:

mef20@makoto 14:54:40/241027(..lang/rakudo)% make package
=> Bootstrap dependency digest>=20211023: found digest-20220214
===> Skipping vulnerability checks.
WARNING: No /usr/pkg/pkgdb/pkg-vulnerabilities file found.
WARNING: To fix run: `/usr/pkg/sbin/pkg_admin -K /usr/pkg/pkgdb fetch-pkg-vulnerabilities'.
===> Installing for rakudo-2024.10
=> Generating pre-install file lists
=> Creating installation directories
+++ Creating installation directories
+++ Removing old files
+++ Installing files
+++ Preparing installation
    Installed 24 core modules in 38.25948764 seconds!
+++ MOAR BACKEND INSTALLED
+++ Installing MOAR launchers
+++ Creating Raku executable alias
+++ Rakudo installed successfully!
/bin/rm -rf /tmp/lang/rakudo/work/.destdir/usr/pkg/share/perl6/core/precomp/*
/bin/rm -rf /tmp/lang/rakudo/work/.destdir/usr/pkg/share/perl6/precomp/*
/usr/bin/install -c -o makoto -g wheel -m 755 /tmp/lang/rakudo/work/rakudo-2024.10/tools/install-dist.p6 /tmp/lang/rakudo/work/.destdir/usr/pkg/share/perl6/bin/
install: /tmp/lang/rakudo/work/rakudo-2024.10/tools/install-dist.p6: stat: No such file or directory
*** Error code 1

Stop.
make[1]: stopped making "package" in /export/CHROOT/usr/pkgsrc/lang/rakudo
*** Error code 1

Stop.
make: stopped making "package" in /export/CHROOT/usr/pkgsrc/lang/rakudo
mef20@makoto 14:55:36/241027(..lang/rakudo)%

**Comment by patrickbkr** [comment]
It's hardcoded into that pkgsrc package: http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/lang/rakudo/Makefile?rev=1.36;content-type=text%2Fplain
Do you by any chance know the maintainer?

**Comment by makoto-fujiwara** [comment]
Shame on me, our fault. I've fixed it. Really thanks.
(no dedicated maintainer exists, but I'm always updating)

**Comment by patrickbkr** [comment]
No worries. You're welcome! Thanks for working on the BSD packages.
(I'm closing this issue.)
