### ISSUE TITLE
Provide a GPG signature of releases

### ISSUE THREAD

**Issue by baby-gnu** [MoarVM/MoarVM#186]
Hello,

Is it possible to sign the releases provided in http://moarvm.org/releases/

Regards.

**Comment by duke-m** [comment]
hehe, yeah, but it's a [one time signing pad](http://moarvm.org/releases/MoarVM-2015.05.tar.gz.asc). :) scnr

**Comment by dod38fr** [comment]
I see that Moarvm 2018.02 is [signed](http://moarvm.org/releases/MoarVM-2018.02.tar.gz.sig) by @samcv . 

@samcv I'm going to configure your [key]((https://pgp.mit.edu/pks/lookup?op=vindex&search=0xA68DF012C3881D62) to check Moarvm downloads for Debian.  Please get back to me if it's not the right one.

All the best

**Comment by samcv** [comment]
@dod38fr yes, that is the correct key. While the last 4 or so releases tags are signed, I decided it would be a good idea to also sign the releases tar.gz's as well.

**Comment by AlexDaniel** [comment]
@samcv can it have .asc extension just for consistency because that's what we do for [other stuff](https://rakudo.perl6.org/downloads/nqp/)?

@dod38fr, by the way, what should be done if the key is changed one day (e.g. if someone else starts doing releases)? What would be the way to do it?

**Comment by samcv** [comment]
@AlexDaniel I just pushed a .asc file to moarvm.org. I will use .asc from now on.

**Comment by dod38fr** [comment]
@AlexDaniel in case of key change or signer change, you should:

1. announce it on an "officilal" low-verbosity channel (could be a blog, or an announce mailing list ) mentioning the new key fingerprint
2. make sure the keys are published, preferably on a key server like pgp.mit.edu

On my side, I will have to add the new key to the keyring used to verify the tarball before downloading the new release. Even if I miss the announce of point 1, I'll notice the change and looks for the new key.

All the best

All the best

**Comment by dod38fr** [comment]
BTW, I think this issue can now be closed. @baby-gnu , do you agree ?

**Comment by baby-gnu** [comment]
I completely agree :-D

**Comment by dod38fr** [comment]
BTW, @samcv thanks for checking the correctness of the key. :-)
