### ISSUE TITLE
Segfault when passing an empty string to uni* subs

### ISSUE THREAD

**Issue by tgt** [MoarVM/MoarVM#194]
Passing an empty string to uniname and uniprop causes MoarVM to segfault.

Rakudo version: This is perl6 version 2015.03-59-gfb991be built on MoarVM version 2015.03-16-ga752064

**Comment by timo** [comment]
This currently gives "cannot unbox a type object"; that's an LTA error, but at least from MoarVM's perspective this bug is fixed. thanks!
