### ISSUE TITLE
SEGV with "say callframe(1)" within block after empty for loop with 200 iterations

### ISSUE THREAD

**Issue by usev6** [MoarVM/MoarVM#196]
I found the following command to segfault reproducible (cmp. http://irclog.perlgeek.de/perl6/2015-04-02#i_10380691)

```
$ perl6-m -e 'for 1 .. 200 { }; { say callframe(1) }'
Segmentation fault
```

Setting MVM_SPESH_DISABLE=1 makes the segfault go away. Setting MVM_SPESH_INLINE_DISABLE=1 does not help.

I don't know if this is related to https://github.com/MoarVM/MoarVM/issues/120 or https://rt.perl.org/Ticket/Display.html?id=124191. If so, I'll gladly add the information there.

**Comment by zhuomingliang** [comment]
Hello, Christian. 
I can't see the bug now, can you confirm it?

**Comment by usev6** [comment]
Hi Jimmy, yeah, the segfault is gone for me as well.
