### ISSUE TITLE
Dyncall upstream repository changed

### ISSUE THREAD

**Issue by patzim** [MoarVM/MoarVM#261]
Dyncall changed its repository location and type. Its Mercurial and resides here:
<http://hg.dyncall.org/pub/dyncall/dyncall>

<http://repo.or.cz/w/fast-export.git> might be of interest to turn the Mercurial repository into a Git one.

**Comment by Benabik** [comment]
I tend to use [git-remote-hg](https://github.com/felipec/git-remote-hg) to interact with Mercurial via git.

**Comment by FROGGS** [comment]
JimmyZ++ already updated the wiki and the repository:
https://github.com/MoarVM/dyncall/wiki
https://github.com/MoarVM/dyncall/commit/e9337ce639206a908e2b10d07fe905956b0229a1
