### ISSUE TITLE
Increase listen backlog size for sync sockets

### ISSUE THREAD

**Issue by tokuhirom** [MoarVM/MoarVM#278]
listen backlog is hard coded to 1 for sync sockets.
https://github.com/MoarVM/MoarVM/blob/master/src/io/syncsocket.c#L137

I suggest to increase this value to 128(Same as asyncsocket https://github.com/MoarVM/MoarVM/blob/master/src/io/asyncsocket.c#L741)

**Comment by zhuomingliang** [comment]
Fixed.
