### ISSUE TITLE
getsockopt support

### ISSUE THREAD

**Issue by tokuhirom** [MoarVM/MoarVM#281]
I want to get socket information from TCP socket.

**Comment by zhuomingliang** [comment]
I don't think MoarVM will add getsockopt.

But I think we should expose the socket/file fd to Perl 6, so many system function that wants fd arg could be used. :)

@jnthn How do you think?

**Comment by zhuomingliang** [comment]
Now we have fd, so I close it. see https://github.com/rakudo/rakudo/commit/a81923164688b13451d70d4855305b7987208d45
