### ISSUE TITLE
build failure; error: macro "fileno" passed 2 arguments, but takes just 1

### ISSUE THREAD

**Issue by carbin** [MoarVM/MoarVM#311]
OpenBSD (gcc):

    src/io/io.c:53:74: error: macro "fileno" passed 2 arguments, but takes just 1

FreeBSD (clang):

    src/io/io.c:53:68: error: too many arguments provided to function-like macro invocation
        MVMint64 ret = handle->body.ops->introspection->fileno(tc, handle);
                                                                   ^
    /usr/include/stdio.h:494:9: note: macro 'fileno' defined here
    #define fileno(p)       (!__isthreaded ? __sfileno(p) : (fileno)(p))
            ^

**Comment by usev6** [comment]
If I understand correctly, at least on FreeBSD there is a macro 'fileno' in addition to the function 'fileno'. From 'man 3 stdio':

     The following are defined as macros; these	names may not be re-used with-
     out first removing	their current definitions with #undef: BUFSIZ, EOF,
     FILENAME_MAX, FOPEN_MAX, L_ctermid, L_cuserid, L_tmpnam, NULL, P_tmpdir,
     SEEK_CUR, SEEK_END, SEEK_SET, TMP_MAX, clearerr, clearerr_unlocked, feof,
     feof_unlocked, ferror, ferror_unlocked, fileno, fileno_unlocked, fropen,
     fwopen, getc, getc_unlocked, getchar, getchar_unlocked, putc,
     putc_unlocked, putchar, putchar_unlocked, stderr, stdin and stdout.
     Function versions of the macro functions clearerr,	clearerr_unlocked,
     feof, feof_unlocked, ferror, ferror_unlocked, fileno, fileno_unlocked,
     getc, getc_unlocked, getchar, getchar_unlocked, putc, putc_unlocked,
     putchar, and putchar_unlocked exist and will be used if the macro defini-
     tions are explicitly removed.

So, would the following patch make sense?

```
diff --git a/src/io/io.c b/src/io/io.c
index 85b755c..f14fad9 100644
--- a/src/io/io.c
+++ b/src/io/io.c
@@ -47,6 +47,11 @@ MVMint64 MVM_io_is_tty(MVMThreadContext *tc, MVMObject *oshandle) {
 }
 
 MVMint64 MVM_io_fileno(MVMThreadContext *tc, MVMObject *oshandle) {
+
+#if defined __FreeBSD__ || defined __OpenBSD__ || defined __NetBSD__ || defined __DragonFly__
+#undef fileno
+#endif
+
     MVMOSHandle *handle = verify_is_handle(tc, oshandle, "fileno");
     if (handle->body.ops->introspection) {
         uv_mutex_t *mutex = acquire_mutex(tc, handle);
```

**Comment by usev6** [comment]
BTW: In case it is helpful, I could happily provide shell access to a FreeBSD box (10.2).

**Comment by cygx** [comment]
Parenthesizing the expression should also work, ie

     MVMint64 ret = (handle->body.ops->introspection->fileno)(tc, handle);

Personally, I'd go with renaming the `fileno` member.

**Comment by stmuk** [comment]
+1 for #undef fileno (since it's suggested in the FreeBSD man page)

**Comment by bdw** [comment]
-1 for undef fileno, because this will also break on any number of other BSD's, perhaps OS X, who knows about solaris / illumos. I'd prefer to rename the function, and would suggest any of:

* file_no
* file_nr
* _fileno
* native_fileno
* native_filenr
* native_file_handle

or something like that....

**Comment by stmuk** [comment]
Fixed by jnthn++ in https://github.com/MoarVM/MoarVM/commit/1a896ff0835dd07935c220511452febf40811b76

**Comment by carbin** [comment]
Confirmed, the fix works. Thanks :-)
