### ISSUE TITLE
'.'.IO.watch; loop {1+1}; #eats all the memory

### ISSUE THREAD

**Issue by xaduha** [MoarVM/MoarVM#315]
https://rt.perl.org/Ticket/Display.html?id=126956

Tested on linux with rakudo-star-2015.11

**Comment by lizmat** [comment]
> On 18 Dec 2015, at 10:30, xaduha <notifications@github.com> wrote:
> 
> https://rt.perl.org/Ticket/Display.html?id=126956
> 
> Tested on linux with rakudo-star-2015.11

Confirmed on OS X with nom.

Additional datapoints:

signal(SIGINT).tap: { exit }; loop { 1 + 1 }   # does the same

signal(SIGINT).tap: { exit }; loop { 1 }  # also eats CPU, but doesn’t leak memory



Questions: isn’t the "1 + 1” supposed to be constant folded at compile time?  It looks like it is not.


Anything not using a live supply before the loop, does not exhibit this behaviour.



Liz

**Comment by xaduha** [comment]
@lizmat 

signal(SIGINT).tap: { exit }; loop { 1 + 1 }; # still leaks in 2016.02 

'.'.IO.watch; loop {1+1} ; # but this one is more or less fixed

**Comment by xaduha** [comment]
Seems to be fixed.
