### ISSUE TITLE
Makefile installs bundled libraries' headers even when the libraries aren't used

### ISSUE THREAD

**Issue by flussence** [MoarVM/MoarVM#323]
I've been [informed on IRC](https://irclog.perlgeek.de/perl6/2015-12-29#i_11794162) that moar's `make install` installs a little more than one might bargain for: it turns out the Gentoo package I'd written creates dyncall, libtommath, libuv, msinttypes, sha1 and tinymt directories and contents in **/usr/include/**, because moar's Makefile.in is hardcoded to do that regardless of Configure switches.

Fortunately having things in subdirectories prevented them overwriting legitimate copies of the headers and trashing my system, but this is really iffy all the same.

**Comment by FROGGS** [comment]
It is not quite true that it installs all headers when you supply a --has-* option.
Look at this for example:
https://github.com/MoarVM/MoarVM/blob/master/Configure.pl#L248-L251

**Comment by flussence** [comment]
Okay, that made me realise I wasn't passing `--has-libffi` when I should've. Now I've got a much smaller problem, at least...

**Comment by flussence** [comment]
Have done some prolonged code reading today, here's some useful findings:

* tinymt and sha1 can be removed from `make install` (and rakudo's `CFLAGS`) unconditionally, because they're statically compiled.
* msinttypes... just defines C99 int types for MSVC — it really doesn't need to grace any other OS with its presence. ☺
