### ISSUE TITLE
JIT is enabled by default on i386-darwin (and leads to bus errors)

### ISSUE THREAD

**Issue by mojca** [MoarVM/MoarVM#324]
Configuration that checks whether JIT should be enabled does the following:
```perl
if ($args{'jit'}) {
    if ($Config{archname} =~ m/^x86_64|^amd64|^darwin(-thread)?(-multi)?-2level/) {
        $config{jit} = '$(JIT_POSIX_X64)';
    } elsif ($Config{archname} =~ /^MSWin32-x64/) {
        $config{jit} = '$(JIT_WIN32_X64)';
    } else {
        say "JIT isn't supported on $Config{archname} yet.";
    }
}
```

On `i386-darwin` (or universal builds) that turns JIT on, compiles successfully, but then nqp build results in bus errors.

See https://trac.macports.org/ticket/50169

**Comment by bdw** [comment]
There are two problems here, as far as I can tell.
First problem: this check is known to be unreliable, because it doesn't actually check the architecture of the platform you're building for, just the platform your perl was built on.
Second problem: we choose whether or not to enable JIT at configuration time, so we build the 'universal' binary configured for (at least) OSX/x64, and just assume (at build time) that this was correct.

The first problem is not so easy to fix; or rather, fixing it would benefit from a large overhaul of the configuration system. The second problem may be easier to fix; the function MVM_jit_support(void) will return 1 if jit is supported, 0 if not, and is checked at runtime. For x64, the compiled-in version is defined in src/jit/emit_x64.dasc.

You would have to add a compiler-and-platform specific check for 32-bit x86 in there to catch the fact that we'd be running on x86 rather than x64. I'm not so familiar with OSX (and don't have a test version anyway), so maybe it might help if you try something out and pass us a pull request.

**Comment by bdw** [comment]
@mojca I would be very grateful it if you could test the fix in the abovementioned commit, so we can close this issue.

**Comment by mojca** [comment]
I'll take a look, but I would also like to ask @coke with deeper insight for more extensive testing.

If that approach turns out to work fine, could you perhaps also "comment out" (using the same `#ifdef`) larger portions of that file to avoid numerous warnings like the following one? (Maybe it's enough to keep just a single function or two; everything else could go under "if this is 64-bit" section.)

~~~~~
src/jit/emit_x64.dasc:274:86: warning: shift count >= width of type [-Wshift-count-overflow]
    dasm_put(Dst, 94, (unsigned int)((uintptr_t)obj), (unsigned int)(((uintptr_t)obj)>>32), Dt1E([reg]));
                                                                                     ^ ~~
src/jit/emit_x64.dasc:408:144: warning: shift count >= width of type [-Wshift-count-overflow]
            dasm_put(Dst, 191, idx, (unsigned int)((uintptr_t)&MVM_frame_vivify_lexical), (unsigned int)(((uintptr_t)&MVM_frame_vivify_lexical)>>32));
                                                                                                                                               ^ ~~
src/jit/emit_x64.dasc:428:195: warning: shift count >= width of type [-Wshift-count-overflow]
        dasm_put(Dst, 222, Dt20(->body.strings), Dt12([idx]), MVM_reg_obj, (unsigned int)((uintptr_t)&MVM_frame_find_lexical_by_name), (unsigned int)(((uintptr_t)&MVM_frame_find_lexical_by_name)>>32), Dt1E([dst]));
                                                                                                                                                                                                  ^ ~~
~~~~~

**Comment by bdw** [comment]
Well, preferably, this file should never be compiled for i386 platforms at all, because the i386 platform would require its own implementation. But for the time being that might be a decent solution.

**Comment by mojca** [comment]
One of the tricky parts with OS X is compilation with `$CC -arch i386 -arch x86_64 filename.c`. Not that this is too relevant nowadays and it will keep loosing its relevance in the future. In those cases you cannot even hope that any test could tell i386 apart from x86_64, but the patch you provided above might work (and in case it does, extra ifdefs could make it work "better"/safer). Let's see the results of the testing first.

**Comment by mojca** [comment]
Some very very primitive testing worked for me, but I'm on a 64-bit system and I hardly know what to test.

The first user of a 32-bit system reported success (not counting lots of warnings during compilation which I still believe would be nice to avoid): https://trac.macports.org/ticket/50169#comment:11

It might be helpful to get at least some feedback from @coke as well.

Assuming that users of 32-bit systems get to compile `emit_x64.das` (on purpose or by accident): which functions from there are needed and which ones could be safely `#ifdef`-ed out (commented out)?

**Comment by coke** [comment]
Based on a conversation on IRC earlier today, I would even consider letting moarvm config die if asked to do a multi-arch compilation. If it's going away, and we're not doing anything special on the non-current architecture... I'm OK with the patch for i386 that works with warnings.

In general, we're targeting recent hardware/OS versions. If it works elsewhere, that's awesome, but we have limited cycles and probably aren't going to spend time prettying it up for older systems. (but will probably take patches to that effect if there's a champion for an older system).

**Comment by mojca** [comment]
Just to make it clear: I believe that the patch works also for universal builds.
