### ISSUE TITLE
VS2015 on Windows 10:  Cannot open include file: 'msinttypes/inttypes.h'

### ISSUE THREAD

**Issue by nanis** [MoarVM/MoarVM#335]
I am trying to build from a fresh git clone (last commit is 775271df). I get this when I run `nmake test` after `perl Configure.pl ...`

Looking at:

    #include <msinttypes/inttypes.h>

the angle-bracket seems to indicate this file is presumed to be either bundled by some VC version, or it should be in the include paths added by the rakudo build process.

AFAIK, full `inttypes.h` support was added in VS2013. Therefore, it seems to me, unless there is some other reason for the gymnastics, the `#ifdef` in `/include/moar\platform/inttypes.h` needs to be replaced with a version check.

If I can figure out the original reason for this, I'll put together a patch, but, in the mean time, FYI.

I am confused by the fact that this does not seem to be a recent addition, but it never caused problems with my previous VS2015 builds.

On the other hand, now I have found why I am getting warnings for using `int` formats to print `size_t` values when building a 64-bit version on Windows.

**Comment by nanis** [comment]
As far as I can see, the only relevant change is in 940850e6 -- which may or may not have something to do with some of the *unrecognized option* messages that scrolled by during the build. It would be nice if the build process took advantage of `File::Spec`.

**Comment by FROGGS** [comment]
I bet your clone is not up to date, since that revision is unkown to git. Also, the referenced commit is supposed to fix what you are experiencing now, so I think your codebase does not include that commit.

**Comment by FROGGS** [comment]
Umm, actually, I'm not sure what the problem report is about. :o)

you say " I get this when I run nmake test after perl Configure.pl ...", but what *do* you get?

**Comment by nanis** [comment]
Actually ... I was confused and pasted the commit hash from rakudo, not MoarVM. You are right, the fresh rakudo clone had pulled in 8079ca54aa.

So, I guess that takes care of the install problem. However, the unconditional delegation to `msinttypes` and definition of the `size_t` format are still wrong for VS2013 and later. I hope my PR fixes this.

**Comment by nanis** [comment]
I did a fresh clone of `rakudo`, ran `perl Configure.pl ...`, and then did an `nmake test` which gave me *** Cannot open include file: 'msinttypes/inttypes.h'*** At that point, looking around in the MoarVM that was pulled in by the rakudo build process, I did not realize I was not looking at the most recent MoarVM source, and, to make matters worse, ran `git log` in the wrong subdirectory.

However, putting that aside, VS2013 supply `inttypes.h` and `stdint.h` and the corresponding checks should look at the value of `_MSC_VER`, and that is what I am trying to fix with the associated PR#336.

**Comment by nanis** [comment]
I am going to close this issue so as to minimize further confusion.
