### ISSUE TITLE
Dynamic register allocation

### ISSUE THREAD

**Issue by drbo** [MoarVM/MoarVM#338]
This should be a performance boost.  DynASM has full support for this as of [this commit][1] and a bug in this support was fixed [here][2].

[1]: /LuaJIT/LuaJIT/commit/a687a60eaac9bd700f821415eaa50393c2fea18a
[2]: /LuaJIT/LuaJIT/commit/22e7b00ddbc2adcc351f9d3656956c5937fc8ee8

**Comment by timo** [comment]
Thanks for the heads-up. brrt has already been working on a "new" jit that will be utilizing full register allocation. The "old" JIT will not likely get support for dynamic register allocation, though, as far as I understand.

I think this issue can be closed?
