### ISSUE TITLE
"Attempt to read past end of string heap when reading string" for NativeCall

### ISSUE THREAD

**Issue by nyaapa** [MoarVM/MoarVM#373]
`
nyaapa@nyaapa-nb-nx ~> perl6 -e 'use NativeCall;'              
===SORRY!===
Attempt to read past end of string heap when reading string
`
moarvm == rakudo == nqp == 2016.05
arch, x64

**Comment by coke** [comment]
What is "2016.05-1" ? (Looks like the only version that matches is "2016.05"

**Comment by nyaapa** [comment]
yep, it's first of 2016.05
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=moarvm

**Comment by nyaapa** [comment]
```
nyaapa@nyaapa-nb-nx ~> /usr/bin/perl6 '-e' 'use NativeCall;' 
===SORRY!===
Annotation segment overflows end of stream
nyaapa@nyaapa-nb-nx ~> /usr/bin/perl6 --version             
This is Rakudo version 2016.06 built on MoarVM version 2016.06
implementing Perl 6.c.
```

**Comment by nyaapa** [comment]
ok in This is Rakudo version 2016.07.1 built on MoarVM version 2016.07
