### ISSUE TITLE
Numification fails with non-ascii strings.

### ISSUE THREAD

**Issue by LemonBoy** [MoarVM/MoarVM#391]
As shown by [RT#127075](https://rt.perl.org/Public/Bug/Display.html?id=127075) a non-ASCII codepoint reaches [this point in Actions.nqp](https://github.com/perl6/nqp/blob/master/src/QRegex/P6Regex/Actions.nqp#L890) and when the second condition of the `||` is executed `$_` is automagically numified.
On the MoarVM level, the call chain is roughly like this:
- smrt_numify
- MVM_coerce_smart_numify
- MVM_coerce_s_n
- MVM_string_ascii_encode

It is the last item in the chain that throws an exception when encountering a non-ASCII codepoint.

**Comment by MasterDuke17** [comment]
I just submitted an NQP PR (https://github.com/perl6/nqp/pull/307) that fixes the RT.
