### ISSUE TITLE
 [CORE.setting.moarvm] Error 137

### ISSUE THREAD

**Issue by renatolrr** [MoarVM/MoarVM#404]
I try install rakudo https://github.com/rakudo/rakudo

Debian 8
MemTotal:         552960 kB
MemFree:          534784 kB

The following step can take a long time, please be patient.
/home/renatolrr/.rakudo/install/bin/moar --libpath="/home/renatolrr/.rakudo/install/share/nqp/lib" perl6.moarvm --setting=NULL --ll-exception --optimize=3 --target=mbc --stagestats --output=CORE.setting.moarvm gen/moar/m-CORE.setting
Stage start      :   0.000
Stage parse      : Killed
Makefile:447: recipe for target 'CORE.setting.moarvm' failed
make: *** [CORE.setting.moarvm] Error 137

**Comment by jnthn** [comment]
Building Rakudo is known to use at least 1GB of memory. Error 137 mostly often shows up during this phase when the OS out of memory killer kills a process, so I suspect that's what has happened here.

**Comment by renatolrr** [comment]
Yes, i need more memory.
Thank
