### ISSUE TITLE
SPESH bug

### ISSUE THREAD

**Issue by coke** [MoarVM/MoarVM#426]
The following rakudo code dies on my OS X box after 200 iterations, unless MVM_SPESH_DISABLE is set, in which case it loops forever. Seems to require the .lines call, and the negation in the ok conditional

```
$cat barf.t 
use v6;
use Test;

loop {
    my $fixer = run('cat', 'barf.t', :out);

    my $count = +$fixer.out.lines;

    ok !$count, "file has so-many spelling errors";
}
```

note that MVM_SPESH_INLINE_DISABLE=1 nor MVM_SPESH_OSR_DISABLE=1 avoid the error.

**Comment by jnthn** [comment]
In the end it golfed all the way down to this test case:

```
lives-ok {
    sub foo() { callframe(1).file.ends-with('x') }
    for ^300 { foo() }
}, 'No crash when using callframe(1).file many times in a loop';
```

Which passes as of 715e39a.
