### ISSUE TITLE
Some sort of SPESH issue

### ISSUE THREAD

**Issue by zoffixznet** [MoarVM/MoarVM#446]
It was revealed by this PR: https://github.com/rakudo/rakudo/pull/934#issuecomment-264913801

and the issue occurs when running `t/spec/S03-operators/mix.t` test file.

---------

**UPDATE:** the PR talked about below has now been merged into Rakudo and `t/spec/S03-operators/mix.t` restructured to avoid the bug. It should still be present if you check out [commit 0f3e1f4e8bdf0dec65b126514b4ce5319d167fa9](https://github.com/perl6/roast/commit/0f3e1f4e8bdf0dec65b126514b4ce5319d167fa9) of the roast repo.

---------

To get the code:
```
git clone https://github.com/ab5tract/rakudo;
git checkout ab5tract/sym-diff-bag-mix;
perl Configure.pl --gen-moar --gen-nqp --backends=moar
make
make install
make t/spec/S03-operators/mix.t; # generate the rakudo.moar file
```

And I narrowed down the issue to a spesh problem:

```
Passes: MVM_SPESH_DISABLE prove -e './perl6' -vlr t/spec/S03-operators/mix.rakudo.moar
Passes: MVM_SPESH_LIMIT=863 prove -e './perl6' -vlr t/spec/S03-operators/mix.rakudo.moar
Fails: MVM_SPESH_LIMIT=864 prove -e './perl6' -vlr t/spec/S03-operators/mix.rakudo.moar
```

This is the spesh log for when MVM_SPESH_LIMIT=864: http://temp.perl6.party/spesh.log.txt

**Comment by MasterDuke17** [comment]
Closing because I can't repro any difference between running that test at that commit of roast with a current MoarVM/Rakudo for MVM_SPESH_DISABLE=1 and not.
