### ISSUE TITLE
Unicode short name property's return the wrong property

### ISSUE THREAD

**Issue by samcv** [MoarVM/MoarVM#448]
http://irclog.perlgeek.de/moarvm/2016-09-28#i_13300929
http://irclog.perlgeek.de/moarvm/2016-12-10#i_13714259

<samcv> m: 'a'.uniprop('Case_folding').say
<camelia> rakudo-moar 5476d6: OUTPUT«0␤»
<samcv> m: 'a'.uniprop('cf').say
<camelia> rakudo-moar 5476d6: OUTPUT«Ll␤»

I have a pull for Rakudo which fixes it by mapping short property names to the full name, but this should ultamitely be fixed in MoarVM.

rakudo/rakudo#944

**Comment by lizmat** [comment]
Can this ticket be closed?  And associated code from src/core/Cool.pm removed?

**Comment by samcv** [comment]
@lizmat thanks for reminding me. I've now updated Cool.pm6 as of https://github.com/rakudo/rakudo/commit/a9e844a8a7a131ebf62c8ec468878d6a4e06a576
