### ISSUE TITLE
MoarVM build fails on WSL (Bash on Windows)

### ISSUE THREAD

**Issue by yorickdowne** [MoarVM/MoarVM#470]
Building MoarVM currently fails out of the box on WSL. Tested with Rakudo * 2016.11 and Windows 10 build 14986, Ubuntu 16.04 LTS. Output from ``perl Configure.pl --backend=moar --gen-moar`` attached as configure-rakudo-txt.

This is due to a missing feature in WSL: It does not implement execstack. See discussion at https://github.com/Microsoft/BashOnWindows/issues/286. MS may, at some future point, implement execstack, and this issue will go away.

MoarVM can be built by manually clearing execstack after the first attempt via ``execstack -c /path/to/libmoar.so``, then attempting the build again. See second attached file configure-rakudo-no-execstack-pass2.txt .

The two instances of libmoar.so are:
./MoarVM/libmoar.so
./install/lib/libmoar.so

Edit 2017-01-04: This can likely be solved upstream at dyncall, see next comment.

There are four ways to handle this issue that come to mind:
1) Do nothing, wait for MS to implement execstack. They will do so eventually. I've asked for roadmap and don't currently have an answer.
2) Do nothing much, document the execstack -c workaround at http://rakudo.org/how-to-get-rakudo/#Installing-Rakudo-Star-Source-Prerequisites-Debian. Though, on second thought: This might be iffy. This just clears the execstack p_flag. Does libmoar.so actually require execstack?
3) Detect WSL and link libmoar.so with ``-Wl,-z,noexecstack``, see also https://github.com/Microsoft/BashOnWindows/issues/283. This would avoid the build error. This workaround for MS' missing feature would then, likely, be removed again when MS releases execstack support in a production version of Windows 10 / WSL. Same concern as 2).

3a: To detect WSL, this code snippet that was considered for a "perl 5 on WSL" issue (since fixed) could be adapted in some form. Test for "Microsoft" or "WSL" in /proc/version:

```
if ($^O eq 'linux') {
    if (open my $pv, '<', '/proc/version') {
        my $lv = <$pv>;
        if (index($lv,'Microsoft') != -1 || index($lv,'WSL') != -1) {
            // Special-case the build here
        }
    }
}
```
4) Investigate why libmoar.so has execstack set. The files that cause it are in dyncall. As per https://linux.die.net/man/8/execstack , GCC "trampoline" code, an example being nested functions, requires execstack. Compiling without should be instructive. See also https://www.win.tue.nl/~aeb/linux/hh/protection.html. 
However, linking without execstack is successful, see 4a. Testing fails on spectests, although it shows 0 Failed tests (see below). I am not sure whether that's expected.
See also https://wiki.gentoo.org/wiki/Hardened/GNU_stack_quickstart for finding the .o files that require execstack. It turns out it's in dyncall, see 4b.

4a: I've tested disabling execstack during compile/link. MoarVM builds, rakudo builds, make test (mostly) succeeds. Which leaves me a little confused as to why GCC is setting the execstack flag. Is there a seldom-used code path that requires it? Or is this a fluke, and MoarVM does not need execstack after all?
This is how I tested:

Edit MoarVM/build/Makefile.in

Append ``-Wl,-z,noexecstack`` to LDFLAGS

These succeed:

perl Configure.pl --backend=moar --gen-moar 
make
make rakudo-test

This fails, but succeeds "mostly":
make rakudo-spectest

```
Test Summary Report
-------------------
t/spec/S03-metaops/hyper.rakudo.moar                        (Wstat: 0 Tests: 402 Failed: 0)
  TODO passed:   115
t/spec/S05-modifier/counted-match.rakudo.moar               (Wstat: 0 Tests: 29 Failed: 0)
  TODO passed:   19-20, 25-27
t/spec/S05-substitution/subst.rakudo.moar                   (Wstat: 0 Tests: 179 Failed: 0)
  TODO passed:   63
t/spec/S15-nfg/regex.rakudo.moar                            (Wstat: 0 Tests: 12 Failed: 0)
  TODO passed:   10
t/spec/S26-documentation/09-configuration.rakudo.moar       (Wstat: 0 Tests: 17 Failed: 0)
  TODO passed:   8-10
t/spec/S32-io/pipe.t                                        (Wstat: 65280 Tests: 10 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 14 tests but ran 10.
t/spec/S32-str/substr.rakudo.moar                           (Wstat: 0 Tests: 56 Failed: 0)
  TODO passed:   56
t/spec/integration/advent2012-day15.rakudo.moar             (Wstat: 0 Tests: 11 Failed: 0)
  TODO passed:   9
Files=1092, Tests=51351, 1090 wallclock secs ( 5.69 usr 11.26 sys + 637.14 cusr 241.83 csys = 895.92 CPU)
Result: FAIL
Makefile:514: recipe for target 'm-spectest5' failed
make[1]: *** [m-spectest5] Error 1
```

This succeeds:
make modules-test

4b: Using scanelf on MoarVM after a failed build (Makefile.in not modified), dyncall is the reason stackexec is set. I've reached out to D. Adler to see whether he can spare cycles to shed light on when (or whether) dyncall executes code on the stack.

tbehrens@WSL-Insider-Test:~/rakudo/rakudo-star-2016.11/MoarVM$ scanelf -qeR .
!WX --- ---  ./3rdparty/dyncall/dyncall/dyncall_call.o
!WX --- ---  ./3rdparty/dyncall/dyncallback/dyncall_callback_arch.o
RWX --- ---  ./libmoar.so

[configure-rakudo.txt](https://github.com/MoarVM/MoarVM/files/675432/configure-rakudo.txt)
[configure-rakudo-no-execstack-pass2.txt](https://github.com/MoarVM/MoarVM/files/675440/configure-rakudo-no-execstack-pass2.txt)

**Comment by yorickdowne** [comment]
Progress and a suggested solution.

1), 2) and 3): All reasonable, and they all miss the mark a little bit.

4): I have been in touch with the dyncall devs. They do not require an executable stack. That two .o files are built with the execstack flag is an artifact of their make environment. 
Suggested solution: Wait for dyncall to resolve this, then incorporate into MoarVM from upstream.

The fix, for reference, would likely be to specify ASFLAGS in "configure" in the dyncall root directory:

```
case ${TARGET:=`uname`} in
  Linux)
    if [ -z "${CFLAGS}" ]; then
      printf "CFLAGS=-fPIC\n" >>$C
    fi
    printf "ASFLAGS=${ASFLAGS} -Wa,--noexecstack\n" >>$C
    printf "LDLIBS=-lm -ldl\n" >>$C
    ;;
```

This is the statement by one of the dyncall devs:


> I haven’t done anything with the execstack and we do not need an executable C stack (if that’s whats behind execstack).
> The dyncallback library (for closures) allocates memory chunks that are written and then made executable. But these chunks come from mmap or VirtualAlloc on Win32.
> The only thing that dyncall(back) does with the stack is to copy buffered argument data from heap to stack (for dyncalls) and the reverse (for dyncallbacks).
>

**Comment by ryanerwin** [comment]
Any luck with a MoarVM update for this, perhaps a change in Configure.pl to check for /proc/version for Microsoft, or even update the default LDFLAGS to clear execstack since it's an extra dependency that doesn't actually seem to be required?

I've tried building new releases of MoarVM each month (2017.01 02 03 04) but this still needs to be manually patched each time, making `rakudobrew` unusable...

**Comment by yorickdowne** [comment]
This was the one that's in dyncall, right? The authors of dyncall are looking at it. It's not trivial. Unfortunately the behavior of these flags varies widely from OS to OS, and noexecstack is not a valid flag everywhere.

It'll get fixed and it'll be a mess of #ifdef. To fix it takes testing on a lot of build environments, and that's why this is taking a while.

A fix on x86 is trivial, but dyncall runs on much more than x86.

Once that's been fixed upstream, then MoarVM can pull in the upstream fix and will build without manual intervention on WSL.

Yours

Thorsten Behrens
(Sent from mobile)
________________________________

**Comment by BenGoldberg1** [comment]
The execstack flag is misnamed, it really means make all readable memory executable.

If your program doesn't have execstack enabled, and you attempt to be able to malloc a buffer, stick executable bytes into it, then immediately call the function in the buffer, you will fail.

The prefered solutions are either use mprotect to make the page containing the buffer executable, or use mmap instead of malloc, and of course use the PROT_EXEC flag when you do so.

See: http://stackoverflow.com/questions/23276488/why-is-execstack-required-to-execute-code-on-the-heap

It would not surprise me in the slightest if dyncall mallocs memory for trampoline functions.

**Comment by yorickdowne** [comment]
>

It would not surprise me in the slightest if dyncall mallocs memory for trampoline functions.

>


That's a reasonable hypothesis, but It doesn't. The dyncall devs were clear that dyncall does not require the execstack flag to function. That it is there is an artifact of the tool chain on certain architectures: The GNU tools default to execstack for assembly files.

Unfortunately that behavior is not uniform across architectures, how to turn off execstack is not uniform, and to top it all off there may be tool chain version dependencies as well.

All of which is to say: it'll get fixed upstream, but not in a hurry.

If an enterprising soul has the ability to build on all architectures supported by dyncall and wants to help with this part, get in touch please and I'll loop you into the ongoing discussion with the dyncall devs.


Thorsten

**Comment by yorickdowne** [comment]
A fix for dyncall's use of execstack has been committed upstream, in the current dyncall dev version. Kudos for the devs to keep at it, that rabbit hole went deep across different architectures.

dyncall 1.0 is still "a good while out". I'm optimistic though and hope we'll see it in 2017. Once dyncall 1.0 is available upstream, I'll update here again, and then MoarVM devs can take a look at using that instead of 0.9. At which point this bug can be laid to rest.

**Comment by FelipeMartin** [comment]
Hi guys.

I came here because of a segmentation fault error trying to run the following line:

gcc -Wall -Wa,--execstack -o myprogram myprogram.c

While in a Fedora redhat VM it works fine, in Bash on Windows I have this error.

Someone on **https://github.com/Microsoft/BashOnWindows/issues/286** told that this pack would solve:

**apt-get install execstack**

Has Anyone tried it ?

**Comment by yorickdowne** [comment]
@FelipeMartin Does your code need execstack? And if so, why?
PROT_GROWSDOWN has not been implemented in WSL, and given the security issues with executable stack, there's no consensus right now that it needs to be implemented.
As per @BenGoldberg1 's link above, there are better ways to execute code on the heap than setting execstack (mmap and mprotect are mentioned). And you really shouldn't rely on code that needs to execute on the stack.

**Comment by FelipeMartin** [comment]
@yorickdowne Actually this is a example just for studying purpose (to understand how machine code works). 
The following is my program and its debug:

```#include <stdio.h>

typedef int (*funcp) (int x);

int main(void) {
	int i;
	unsigned char codigo[] = {0x55,0x89,0xe5,0x8b,0x45,0x08,0x83,0xc0,0x01,0x89,0xec,0x5d,0xc3};
	funcp f = (funcp)codigo;
	i = (*f)(10);
	printf("%d\n", i);
	return 0;
}
```

```Breakpoint 1, main () at ex3.c:5
5       int main(void) {
(gdb) s
7               unsigned char codigo[] = {0x55,0x89,0xe5,0x8b,0x45,0x08,0x83,0xc0,0x01,0x89,0xec,0x5d,0xc3};
(gdb)
8               funcp f = (funcp)codigo;
(gdb)
9               i = (*f)(10);
(gdb)

Program received signal SIGSEGV, Segmentation fault.
0x00007ffffffde4d0 in ?? ()
```

Could I do something similar (compiling in a different way with mmap or mprotect) to have the same idea ?

**Comment by yorickdowne** [comment]
dyncall 1.0 is out and includes the change to avoid execstack, among a lot of great improvements. http://www.dyncall.org/changelog#dc10

Using dyncall 1.0 will resolve this issue and, it looks like, might resolve a few others, see https://github.com/MoarVM/MoarVM/issues/794

**Comment by deven** [comment]
Until MoarVM incorporates dyncall 1.0, a workaround that seems to work for me is to first download and install dyncall 1.0 into /usr/local, then build MoarVM with the --has-dyncall option so it will use it.

**Comment by deven** [comment]
This issue wasn't completely fixed by https://github.com/MoarVM/dyncall/pull/5, because MoarVM wasn't actually using the fix.  This pull request applies those fixes to MoarVM's default build:

     https://github.com/MoarVM/MoarVM/pull/1157
