### ISSUE TITLE
MoarVM panic: Internal error: zeroed target thread ID in work pass #93

### ISSUE THREAD

**Issue by nige123** [MoarVM/MoarVM#473]
I'm intermittently seeing this occur while running Bailador:

MoarVM panic: Internal error: zeroed target thread ID in work pass

The result is the server comes to a complete halt - ouch!

Here is the current Perl 6 version I'm using:

This is Rakudo version 2016.12-95-ga6c37a7 built on MoarVM version 2016.12-6-g65acd55
implementing Perl 6.c.

**Comment by jnthn** [comment]
Are you seeing this at all? We've fixed many issues since this was filed that could have potentially produced that error.

**Comment by nige123** [comment]
Hi Jonathan
Thanks for the email. This error is no longer happening - thanks for fixing the probable cause
Cheers
Nige
