### ISSUE TITLE
Must not GC when in the specializer/JIT while running code example from RT #127987

### ISSUE THREAD

**Issue by dogbert17** [MoarVM/MoarVM#478]
Running the code example from https://rt.perl.org/Public/Bug/Display.html?id=127987 with a small nursery, i.e. 64k and MVM_GC_DEBUG 2 the above message appears most of the time.

dogbert@dogbert-VirtualBox ~/repos/rakudo $ cat ~/scratch.pl6 
for (^100).race(batch=>1) { {1 + $^a}.assuming(10)() }

dogbert@dogbert-VirtualBox ~/repos/rakudo $ gdb --args /home/dogbert/repos/rakudo/install/bin/moar --libpath="/home/dogbert/repos/rakudo/install/share/nqp/lib" --libpath="." /home/dogbert/repos/rakudo/perl6.moarvm -I lib ~/scratch.pl6
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/dogbert/repos/rakudo/install/bin/moar...done.
(gdb) break MVM_panic
Function "MVM_panic" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (MVM_panic) pending.
(gdb) r
Starting program: /home/dogbert/repos/rakudo/install/bin/moar --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib --libpath=. /home/dogbert/repos/rakudo/perl6.moarvm -I lib /home/dogbert/scratch.pl6
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
[New Thread 0xb657eb40 (LWP 27134)]
[New Thread 0xb5bffb40 (LWP 27135)]
[New Thread 0xb51ffb40 (LWP 27136)]
[New Thread 0xb47ffb40 (LWP 27137)]
[Switching to Thread 0xb47ffb40 (LWP 27137)]

Breakpoint 1, MVM_panic (exitCode=1, messageFormat=0xb7d5a6bc "Must not GC when in the specializer/JIT\n") at src/core/exceptions.c:781
781	    fprintf(stderr, "MoarVM panic: ");
(gdb) bt
\#0  MVM_panic (exitCode=1, messageFormat=0xb7d5a6bc "Must not GC when in the specializer/JIT\n") at src/core/exceptions.c:781
\#1  0xb7c715b5 in run_gc (tc=0x9b869a0, what_to_do=1 '\001') at src/gc/orchestrate.c:310
\#2  0xb7c71b87 in MVM_gc_enter_from_interrupt (tc=0x9b869a0) at src/gc/orchestrate.c:505
\#3  0xb7c7144b in MVM_gc_mark_thread_blocked (tc=0x9b869a0) at src/gc/orchestrate.c:254
\#4  0xb7cc0de3 in MVM_reentrantmutex_lock (tc=0x9b869a0, rm=0x82e9878) at src/6model/reprs/ReentrantMutex.c:126
\#5  0xb7c4a8a8 in MVM_cu_string_add (tc=0x9b869a0, cu=0x80a2260, str=0x80f6150) at src/core/compunit.c:131
\#6  0xb7cf8699 in fix_str (tc=0x9b869a0, inliner=0xb0e99d68, inlinee=0xac80f68, to_fix=0xad724c8) at src/spesh/inline.c:161
\#7  0xb7cf8b46 in merge_graph (tc=0x9b869a0, inliner=0xb0e99d68, inlinee=0xac80f68, inlinee_code=0x8107ed8, invoke_ins=0xb0ec6ed8) at src/spesh/inline.c:280
\#8  0xb7cfa63e in MVM_spesh_inline (tc=0x9b869a0, inliner=0xb0e99d68, call_info=0xb47fc93c, invoke_bb=0xb0ed6184, invoke_ins=0xb0ec6ed8, inlinee=0xac80f68, inlinee_code=0x8107ed8) at src/spesh/inline.c:867
\#9  0xb7cf50bd in optimize_call (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed6184, ins=0xb0ec6ed8, callee_idx=1, arg_info=0xb47fc93c) at src/spesh/optimize.c:1188
\#10 0xb7cf607a in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed6184) at src/spesh/optimize.c:1519
\#11 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed6150) at src/spesh/optimize.c:1677
\#12 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed60b4) at src/spesh/optimize.c:1677
\#13 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed6018) at src/spesh/optimize.c:1677
\#14 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed5fe4) at src/spesh/optimize.c:1677
\#15 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed5ddc) at src/spesh/optimize.c:1677
\#16 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed5da8) at src/spesh/optimize.c:1677
\#17 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed56f4) at src/spesh/optimize.c:1677
\#18 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed56c0) at src/spesh/optimize.c:1677
\#19 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed4fd8) at src/spesh/optimize.c:1677
\#20 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed4fa4) at src/spesh/optimize.c:1677
\#21 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed4d9c) at src/spesh/optimize.c:1677
\#22 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed4d00) at src/spesh/optimize.c:1677
\#23 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed4c64) at src/spesh/optimize.c:1677
\#24 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed4bc8) at src/spesh/optimize.c:1677
\#25 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed4b2c) at src/spesh/optimize.c:1677
\#26 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed4a90) at src/spesh/optimize.c:1677
\#27 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed49f4) at src/spesh/optimize.c:1677
\#28 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed49c0) at src/spesh/optimize.c:1677
\#29 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed4888) at src/spesh/optimize.c:1677
\#30 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed4854) at src/spesh/optimize.c:1677
\#31 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed4784) at src/spesh/optimize.c:1677
\#32 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed26f8) at src/spesh/optimize.c:1677
\#33 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed26c4) at src/spesh/optimize.c:1677
\#34 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed2690) at src/spesh/optimize.c:1677
\#35 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed25f4) at src/spesh/optimize.c:1677
\#36 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed1f0c) at src/spesh/optimize.c:1677
\#37 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed1ea4) at src/spesh/optimize.c:1677
\#38 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed1e08) at src/spesh/optimize.c:1677
\#39 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed1dd4) at src/spesh/optimize.c:1677
\#40 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed1d6c) at src/spesh/optimize.c:1677
\#41 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed1d04) at src/spesh/optimize.c:1677
\#42 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed1cd0) at src/spesh/optimize.c:1677
\#43 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed1c68) at src/spesh/optimize.c:1677
\#44 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed1c34) at src/spesh/optimize.c:1677
\#45 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed1bcc) at src/spesh/optimize.c:1677
\#46 0xb7cf640e in optimize_bb (tc=0x9b869a0, g=0xb0e99d68, bb=0xb0ed1b84) at src/spesh/optimize.c:1677
\#47 0xb7cf6cb9 in MVM_spesh_optimize (tc=0x9b869a0, g=0xb0e99d68) at src/spesh/optimize.c:1878
\#48 0xb7cebdaf in MVM_spesh_candidate_specialize (tc=0x9b869a0, static_frame=0x8301ba8, candidate=0xb0e9e2c8) at src/spesh/candidate.c:180
\#49 0xb7c50de6 in remove_one_frame (tc=0x9b869a0, unwind=0 '\000') at src/core/frame.c:771
\#50 0xb7c51213 in MVM_frame_try_return (tc=0x9b869a0) at src/core/frame.c:891
\#51 0xb7c17fed in MVM_interp_run (tc=0x9b869a0, initial_invoke=0xb7c59347 <thread_initial_invoke>, invoke_data=0x9612a28) at src/core/interp.c:459
\#52 0xb7c59489 in start_thread (data=0x9612a28) at src/core/threads.c:77
\#53 0xb7d4af47 in uv.thread_start () from //home/dogbert/repos/rakudo/install/lib/libmoar.so
\#54 0xb7966f72 in start_thread (arg=0xb47ffb40) at pthread_create.c:312
---Type <return> to continue, or q <return> to quit---
\#55 0xb7aaef8e in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:129
(gdb) frame 1
\#1  0xb7c715b5 in run_gc (tc=0x9b869a0, what_to_do=1 '\001') at src/gc/orchestrate.c:310
310	        MVM_panic(1, "Must not GC when in the specializer/JIT\n");
(gdb) p MVM_dump_backtrace(tc)
   at <unknown>:1  (./blib/Perl6/Actions.moarvm:unwanted)
 from gen/moar/Perl6-Actions.nqp:90  (./blib/Perl6/Actions.moarvm:wanted)
 from gen/moar/Perl6-Actions.nqp:212  (./blib/Perl6/Actions.moarvm:WANTED)
 from gen/moar/Perl6-Actions.nqp:116  (./blib/Perl6/Actions.moarvm:wanted)
 from gen/moar/Perl6-Actions.nqp:78  (./blib/Perl6/Actions.moarvm:wanted)
 from gen/moar/Perl6-Actions.nqp:78  (./blib/Perl6/Actions.moarvm:wanted)
 from gen/moar/Perl6-Actions.nqp:212  (./blib/Perl6/Actions.moarvm:WANTED)
 from gen/moar/Perl6-Actions.nqp:85  (./blib/Perl6/Actions.moarvm:)
 from gen/moar/Perl6-Actions.nqp:78  (./blib/Perl6/Actions.moarvm:wanted)
 from gen/moar/Perl6-Actions.nqp:212  (./blib/Perl6/Actions.moarvm:WANTED)
 from gen/moar/Perl6-Actions.nqp:3376  (./blib/Perl6/Actions.moarvm:routine_def)
 from gen/moar/stage2/QRegex.nqp:1341  (/home/dogbert/repos/rakudo/install/share/nqp/lib/QRegex.moarvm:!reduce)
 from gen/moar/stage2/QRegex.nqp:1302  (/home/dogbert/repos/rakudo/install/share/nqp/lib/QRegex.moarvm:!cursor_pass)
 from src/Perl6/Grammar.nqp:2654  (./blib/Perl6/Grammar.moarvm:routine_def)
 from src/Perl6/Grammar.nqp:2447  (./blib/Perl6/Grammar.moarvm:multi_declarator:sym<proto>)
 from gen/moar/stage2/QRegex.nqp:1378  (/home/dogbert/repos/rakudo/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (./blib/Perl6/Grammar.moarvm:multi_declarator)
 from src/Perl6/Grammar.nqp:2511  (./blib/Perl6/Grammar.moarvm:scoped)
 from <unknown>:1  (./blib/Perl6/Grammar.moarvm:scope_declarator:sym<my>)
 from gen/moar/stage2/QRegex.nqp:1378  (/home/dogbert/repos/rakudo/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (./blib/Perl6/Grammar.moarvm:scope_declarator)
 from <unknown>:1  (./blib/Perl6/Grammar.moarvm:term:sym<scope_declarator>)
 from gen/moar/stage2/QRegex.nqp:1378  (/home/dogbert/repos/rakudo/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (./blib/Perl6/Grammar.moarvm:term)
 from src/Perl6/Grammar.nqp:3831  (./blib/Perl6/Grammar.moarvm:termish)
 from gen/moar/stage2/NQPHLL.nqp:932  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:EXPR)
 from src/Perl6/Grammar.nqp:3871  (./blib/Perl6/Grammar.moarvm:EXPR)
 from src/Perl6/Grammar.nqp:1251  (./blib/Perl6/Grammar.moarvm:statement)
 from <unknown>:1  (./blib/Perl6/Grammar.moarvm:semilist)
 from <unknown>:1  (./blib/Perl6/Grammar.moarvm:circumfix:sym<( )>)
 from gen/moar/stage2/QRegex.nqp:1378  (/home/dogbert/repos/rakudo/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:circumfix)
 from <unknown>:1  (./blib/Perl6/Grammar.moarvm:term:sym<circumfix>)
 from gen/moar/stage2/QRegex.nqp:1378  (/home/dogbert/repos/rakudo/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (./blib/Perl6/Grammar.moarvm:term)
 from src/Perl6/Grammar.nqp:3831  (./blib/Perl6/Grammar.moarvm:termish)
 from gen/moar/stage2/NQPHLL.nqp:932  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:EXPR)
 from src/Perl6/Grammar.nqp:3871  (./blib/Perl6/Grammar.moarvm:EXPR)
 from src/Perl6/Grammar.nqp:3155  (./blib/Perl6/Grammar.moarvm:initializer:sym<=>)
 from gen/moar/stage2/QRegex.nqp:1378  (/home/dogbert/repos/rakudo/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (./blib/Perl6/Grammar.moarvm:initializer)
 from src/Perl6/Grammar.nqp:2427  (./blib/Perl6/Grammar.moarvm:declarator)
 from src/Perl6/Grammar.nqp:2498  (./blib/Perl6/Grammar.moarvm:scoped)
 from <unknown>:1  (./blib/Perl6/Grammar.moarvm:scope_declarator:sym<my>)
 from gen/moar/stage2/QRegex.nqp:1378  (/home/dogbert/repos/rakudo/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (./blib/Perl6/Grammar.moarvm:scope_declarator)
 from <unknown>:1  (./blib/Perl6/Grammar.moarvm:term:sym<scope_declarator>)
 from gen/moar/stage2/QRegex.nqp:1378  (/home/dogbert/repos/rakudo/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (./blib/Perl6/Grammar.moarvm:term)
 from src/Perl6/Grammar.nqp:3831  (./blib/Perl6/Grammar.moarvm:termish)
 from gen/moar/stage2/NQPHLL.nqp:932  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:EXPR)
 from src/Perl6/Grammar.nqp:3871  (./blib/Perl6/Grammar.moarvm:EXPR)
 from src/Perl6/Grammar.nqp:1251  (./blib/Perl6/Grammar.moarvm:statement)
 from src/Perl6/Grammar.nqp:1180  (./blib/Perl6/Grammar.moarvm:statementlist)
 from src/Perl6/Grammar.nqp:1353  (./blib/Perl6/Grammar.moarvm:blockoid)
 from src/Perl6/Grammar.nqp:1316  (./blib/Perl6/Grammar.moarvm:pblock)
 from src/Perl6/Grammar.nqp:3783  (./blib/Perl6/Grammar.moarvm:circumfix:sym<{ }>)
 from gen/moar/stage2/QRegex.nqp:1378  (/home/dogbert/repos/rakudo/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:circumfix)
 from <unknown>:1  (./blib/Perl6/Grammar.moarvm:term:sym<circumfix>)
 from gen/moar/stage2/QRegex.nqp:1378  (/home/dogbert/repos/rakudo/install/share/nqp/lib/QRegex.moarvm:!protoregex)
 from <unknown>:1  (./blib/Perl6/Grammar.moarvm:term)
 from src/Perl6/Grammar.nqp:3831  (./blib/Perl6/Grammar.moarvm:termish)
 from gen/moar/stage2/NQPHLL.nqp:932  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:EXPR)
 from src/Perl6/Grammar.nqp:3871  (./blib/Perl6/Grammar.moarvm:EXPR)
 from src/Perl6/Grammar.nqp:1251  (./blib/Perl6/Grammar.moarvm:statement)
 from src/Perl6/Grammar.nqp:1180  (./blib/Perl6/Grammar.moarvm:statementlist)
 from gen/moar/stage2/NQPHLL.nqp:1160  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:LANG)
 from src/Perl6/Grammar.nqp:1595  (./blib/Perl6/Grammar.moarvm:FOREIGN_LANG)
 from src/Perl6/Grammar.nqp:1164  (./blib/Perl6/Grammar.moarvm:comp_unit)
 from src/Perl6/Grammar.nqp:467  (./blib/Perl6/Grammar.moarvm:TOP)
 from gen/moar/stage2/QRegex.nqp:2102  (/home/dogbert/repos/rakudo/install/share/nqp/lib/QRegex.moarvm:parse)
 from gen/moar/stage2/NQPHLL.nqp:1880  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:parse)
 from gen/moar/stage2/NQPHLL.nqp:1830  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:run)
 from gen/moar/stage2/NQPHLL.nqp:1840  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:)
 from gen/moar/stage2/NQPHLL.nqp:1818  (/home/dogbert/repos/rakudo/install/share/nqp/lib/NQPHLL.moarvm:compile)
 from SETTING::src/core/control.pm:213  (./CORE.setting.moarvm:EVAL)
 from SETTING::src/core/Block.pm:294  (./CORE.setting.moarvm:assuming)
 from /home/dogbert/scratch.pl6:1  (<ephemeral file>:)
 from SETTING::src/core/Any-iterable-methods.pm:417  (./CORE.setting.moarvm:push-all)
 from SETTING::src/core/Any-iterable-methods.pm:48  (./CORE.setting.moarvm:process-buffer)
 from SETTING::src/core/HyperSeq.pm:140  (./CORE.setting.moarvm:)
 from SETTING::src/core/HyperSeq.pm:139  (./CORE.setting.moarvm:)
 from SETTING::src/core/HyperSeq.pm:116  (./CORE.setting.moarvm:)
 from SETTING::src/core/Promise.pm:175  (./CORE.setting.moarvm:)
 from SETTING::src/core/ThreadPoolScheduler.pm:162  (./CORE.setting.moarvm:)
 from SETTING::src/core/ThreadPoolScheduler.pm:51  (./CORE.setting.moarvm:)
 from SETTING::src/core/ThreadPoolScheduler.pm:44  (./CORE.setting.moarvm:)
 from SETTING::src/core/ThreadPoolScheduler.pm:41  (./CORE.setting.moarvm:)
 from SETTING::src/core/Thread.pm:30  (./CORE.setting.moarvm:THREAD-ENTRY)
$1 = void

If the nursery is set to its normal size the program aborts with one of several messages, e.g.

*** Error in `/home/dogbert/repos/rakudo/install/bin/moar': double free or corruption (fasttop): 0xb12ad3c0 ***

or

*** Error in `/home/dogbert/repos/rakudo/install/bin/moar': realloc(): invalid old size: 0xb3e25d28 ***

or

Parameter '$a' requires a type object of type Mu, but an object instance was passed.  Did you forget a 'multi'?
  in block  at /home/dogbert/scratch.pl6 line 1

etc

I get the impression that the code example exposes more than one problem although I could be wrong here

**Comment by jnthn** [comment]
Fixed in work merged as PR #495.
