### ISSUE TITLE
utf8-c8 accepts invalid sequences as UTF-8

### ISSUE THREAD

**Issue by arnsholt** [MoarVM/MoarVM#481]
See https://irclog.perlgeek.de/perl6-dev/2017-01-03#i_13843920 for IRC discussion.

UTF-8 requires that codepoints be represented using the *shortest* possible representation; thus codepoint U+0020 can only be encoded as `0b00100000`, and not, say, `0b11000000 0b10100000`. The utf8-c8 decoder doesn't check this constraint, giving the failures seen in the IRC discussion.

I pretty sure a leader of `0b11000000` can be rejected out of hand, but `0b11100000` and `0b11110000` can not. If a codepoint is *exactly* 12 bits wide, it's too wide for a two-byte sequence (having only 11 bits for the codepoint), but will give the encoding `0b11100000 0b10xxxxxx 0b10xxxxxx`. Similarly for a leader of `0b11110000` and codepoints 17 and 18 bits wide, etc.

I guess one way to handle this would be to keep track of how many bytes we read, and make sure the decoded codepoint needs that many bytes before calling `utf8_c8.c:process_ok_codepoint`.

I note that the [UTF-8 reference implementation](http://unicode.org/resources/utf8.html) only disallows the leaders `0xc0`, `0xc1`, `0xf5` and `0xff` explicitly, so I'm not sure how that handles cases like `0xE0 0x00 0x00` being an invalid encoding of U+0000.

**Comment by jnthn** [comment]
Fixed in fe110d6.
