### ISSUE TITLE
On Windows, improve handling of Unicode in command line arguments and environment strings

### ISSUE THREAD

**Issue by nanis** [MoarVM/MoarVM#527]
For a while, the discussion on this issue was taking place on [nqp/#346][2], but pointers by @timo and my subsequent work established that the fix belongs in MoarVM.

I've made some progress and [explained my process on my blog][1]. I still need to touch the code that sets up the environment, but once I do that, I'll have a pull request. Hope it works on others' machines, too ;-)

See also [perl #127925][3].

[1]: https://www.nu42.com/2017/02/unicode-windows-command-line.html
[2]: https://github.com/perl6/nqp/issues/346
[3]: https://rt.perl.org/Public/Bug/Display.html?id=127925

**Comment by nanis** [comment]
@timo I think #528 has progressed up to the point where it should build fine with both MinGW and Visual Studio 2015 tools.

@zoffixznet can you try #528 with MinGW again.

**Comment by zoffixznet** [comment]
@nanis [commented on the PR](https://github.com/MoarVM/MoarVM/pull/528#issuecomment-279092393)

**Comment by nanis** [comment]
#528 was merged. Thank you.
