### ISSUE TITLE
extend hash to traverse trees

### ISSUE THREAD

**Issue by diakopter** [MoarVM/MoarVM#53]
note this also has a dependency on fixing the tree strings so they don't need flattening after every creation op too :)

22:17 < diakopter> oh, another todo :)
22:17 < diakopter> extend the hash algorithm to be smart enough to traverse tree strings instead of requiring all strings to be flattened before used as
                   hash keys
22:18 < diakopter> the machinery to make the traversal modular enough should already mostly be there
22:18 < diakopter> should I add it as an issue?
22:18 < not_gerd> does it make sense to cache the hash value?
22:19 < diakopter> yes
22:19 < not_gerd> having it around is also useful for eq
22:19 < not_gerd> do we already do it?
22:19 < diakopter> don't think so
22:19 < diakopter> though I might've put a slot in for it

**Comment by timo** [comment]
hash values for strings are calculated using the grapheme iterator API since one or two years ago. closing this bug.
