### ISSUE TITLE
cache immutable created runtime things

### ISSUE THREAD

**Issue by diakopter** [MoarVM/MoarVM#54]
22:19 < diakopter> another todo:
22:20 < diakopter> all the string literals in the moarvm source where we construct MVMStrings from C literal strings (without format)... should be cached in a struct that hangs off MVMInstance
22:20 < diakopter> (and all rooted)
22:21 < diakopter> (and their constructor calls obviously set to lookup in the cache)
22:21 < diakopter> parrot has a convenience function for this
22:22 < diakopter> there are already a few strings cached on Instance like that ->Str , ->Num, ->Empty I think
22:22 < diakopter> but it needs generalized
22:22 < diakopter> further generalized would be to find any unchanging/immutable things created by runtime code and make those cached too
22:24 < diakopter> could even make the .h that stores their slots generated if you use a macro sneakily

**Comment by jnthn** [comment]
There is such a `struct` hanging off `MVMInstance` today (`MVMStringConsts`) and it's been there for a while, so guess we can close this.
