### ISSUE TITLE
Missing error/exception message when running unknown command with Proc::Async

### ISSUE THREAD

**Issue by dogbert17** [MoarVM/MoarVM#547]
Running the following program should exit with an exception but it does not

    my $prog = Proc::Async.new(:w, 'hexdump17', '-C');  # hexdump17 does not exist
    my $promise = $prog.start;
    await $prog.write(Buf.new(12, 42));
    $prog.close-stdin;
    await $promise;

Running the script (let's call it scratch.pl6) in gdb shows that an exception is in fact generated:

    dogbert@dogbert-VirtualBox ~ $ perl6-gdb-m scratch.pl6 
    ================================================================================================
    This is Rakudo Perl 6 running in the GNU debugger, which often allows the user to generate useful back-
    traces to debug or report issues in Rakudo, the MoarVM backend or the currently running code.
    
    This Rakudo version is 2017.02.167.ge.114.d.5204 built on MoarVM version 2017.02.18.g.5.f.9.d.6985,
    running on ubuntu (14.04.3.LTS.Trusty.Tahr) / linux (3.19.0.32.generic)
    
    Type `bt full` to generate a backtrace if applicable, type `q` to quit or `help` for help.
    ------------------------------------------------------------------------------------------------
    Reading symbols from /home/dogbert/.rakudobrew/moar-nom/install/bin/moar...(no debugging symbols found)...done.
    Starting program: /home/dogbert/.rakudobrew/moar-nom/install/bin/moar --execname=/home/dogbert/.rakudobrew/bin/../moar-nom/install/bin/perl6-gdb-m --libpath=/home/dogbert/.rakudobrew/moar-nom/install/share/nqp/lib --libpath=/home/dogbert/.rakudobrew/moar-nom/install/share/perl6/lib --libpath=/home/dogbert/.rakudobrew/moar-nom/install/share/perl6/runtime /home/dogbert/.rakudobrew/moar-nom/install/share/perl6/runtime/perl6.moarvm scratch.pl6
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
    [New Thread 0xb5dd5b40 (LWP 22530)]
    [New Thread 0xb4ffeb40 (LWP 22531)]
    [New Thread 0xb3ffeb40 (LWP 22533)]
    
    Program received signal SIGPIPE, Broken pipe.
    [Switching to Thread 0xb4ffeb40 (LWP 22531)]
    0xb7fdccb0 in ?? ()
    (gdb) c
    Continuing.
    Tried to get the result of a broken Promise
      in block <unit> at scratch.pl6 line 3
    
    Original exception:
        Died with X::AdHoc+{X::Promise::Broken}
          in block <unit> at scratch.pl6 line 3
    
    [Thread 0xb3ffeb40 (LWP 22533) exited]
    [Thread 0xb4ffeb40 (LWP 22531) exited]
    [Thread 0xb5dd5b40 (LWP 22530) exited]
    [Inferior 1 (process 22526) exited with code 01]

A discussion about this issue can be found here:

https://irclog.perlgeek.de/moarvm/2017-03-05#i_14209351

There are at least two RT's referring to this problem, i.e.

https://rt.perl.org/Public/Bug/Display.html?id=125651
https://rt.perl.org/Public/Bug/Display.html?id=128526

**Comment by jnthn** [comment]
Confirmed this fixes the issue on both Linux and Windows; tests are in `S17-procasync/nonexistent.t` and that file will be added to spectest.data soon (looking at #538 first).
