### ISSUE TITLE
`expmod(1, -1, 1)` gets stuck into an infinite loop

### ISSUE THREAD

**Issue by trizen** [MoarVM/MoarVM#549]
The following Perl 6 code gets stuck into an infinite loop:
```perl6
say expmod(1, -1, 1);
```

This seems to happen for every odd positive number `$n` in the expression:

```perl6
say expmod($n, -1, $n);
```

**Comment by trizen** [comment]
Update: `expmod(1, -1, 1)` seems to be fixed in version `2017.03`, but `expmod(-5, -5, 5)` still hangs.

**Comment by duke-m** [comment]
btw, a pity perl6 doesn't feel "more natural" using modulo like
![](https://latex.codecogs.com/gif.latex?a%20%5Cbmod%20m%3A%3D%20a%20-%20%5Cleft%20%5Clfloor%20%5Cfrac%7Ba%7D%7Bm%7D%20%5Cright%20%5Crfloor%20%5Ccdot%20m.)
instead it expects Ints: https://docs.perl6.org/routine/mod

So shouldn't expmod throw an exception when it will clearly fail when `$x gcd $z != 1`?

**Comment by zoffixznet** [comment]
libtommath made an [updated fix](https://github.com/libtom/libtommath/issues/67#issuecomment-336654018) to the expmod routine.

Would be nice if someone could pull the change into our fork and try it out.

IRC: https://irclog.perlgeek.de/moarvm/2017-10-14#i_15303194

**Comment by coke** [comment]
With v2021.10-23-gc50bc9985, now get:

```
$ raku -e 'expmod(1,-1,1).say'
Error in mp_exptmod: Value out of range
  in block <unit> at -e line 1
```

**Comment by MasterDuke17** [comment]
Closing because this has been fixed and there are tests: https://github.com/Raku/roast/blob/master/S32-num/expmod.t#L25-L36
