### ISSUE TITLE
Release 2017.04 doesn't include 3rd party libs (dynasm, dyncall, libtommath, libuv)

### ISSUE THREAD

**Issue by ryanerwin** [MoarVM/MoarVM#584]
Inside of the 2017.04.tar.gz release, there is a ".gitmodules" that can't be used to grab the 3rd party libs since the release tarball isn't a git repository. You can see here the 3rd party libs that were not included in the release: dynasm, dyncall, libtommath, libuv

```
% du -hs 3rdparty/*
0       3rdparty/dynasm
0       3rdparty/dyncall
16K     3rdparty/freebsd
2.1M    3rdparty/libatomic_ops
0       3rdparty/libtommath
0       3rdparty/libuv
16K     3rdparty/msinttypes
4.0K    3rdparty/README.md
12K     3rdparty/sha1
8.0K    3rdparty/tinymt
80K     3rdparty/uthash.h
```

For a temporary workaround, people can check out the release branch, and then grab the submodules themselves:

```
$ git clone --branch 2017.04 https://github.com/MoarVM/MoarVM.git
$ cd MoarVM
$ git submodule init
$ git submodule update --init --recursive
$ sudo perl Configure.pl --prefix=/opt/rakudo-2017.04 --make-install
```

**Comment by timo** [comment]
sorry, we've been trying for ages to remove the releases thing from github because it just doesn't work. it seems like it creates all of the releases over again when a new one gets pushed, ruining my work of clicking through to every single delete button.

meanwhile, you can get the releases from https://moarvm.org

**Comment by ryanerwin** [comment]
May I make three suggestions then...

1) Try the "remove all github releases" script https://github.com/stevemao/github-remove-all-releases

2) Please consider a workflow that keeps moarvm.org and github more closely in sync... In spite of the 2017.04 tagged release in github, moarvm.org only lists the 2017.03 release. Similar problems for Rakudo Star (last release was 2017.01). As a side note, seems like having the inevitable Perl6 version CPAN built directly on top of github could be a big win to simplify these sorts of synchronization issues....

3) Please include the https://moarvm.org link prominently on the README.markdown. I think that MoarVM contributors are not going to spend much time reading the default README.markdown... Most of those readers will be people that want to write/run perl6 code. Especially considering that Rakudo Star seems to be dying, many people wanting to write in perl6 has to come here and download MoarVM. 

# Download Source (.tar.gz)

Each new Release of MoarVM is available from https://moarvm.org/, please head over to MoarVM.org to download the latest release

# Download Source (git)

You can download the released branch via github with:

```
$ git clone --branch 2017.04 https://github.com/MoarVM/MoarVM.git
$ cd MoarVM
$ git submodule init
$ git submodule update --init --recursive
$ sudo perl Configure.pl --prefix=/opt/rakudo-2017.04 --make-install
```

# Building/Updating Perl 6

The Rakudo implementation of Perl 6 is the recommended implementation at this time. To install the Rakudo version of Perl 6. Each Rakudo release is synchronized with a release of NQP (not quite perl) and the MoarVM.

For example, to build the 2017.04 release, you'll need to download the 2017.04 .tar.gz for MoarVM, NQP and Rakudo.

The build order always must be:

1. MoarVM
2. NQP
3. Rakudo

# MoarVM under WSL

Windows 10's Windows Subsystem for Linux doesn't yet support _execstack_ which is enabled on _dyncall_ (part of MoarVM's 3rd party components) causing MoarVM to fail to build under WSL. 

Before building MoarVM just edit the `build/Makefile.in` and search for LDFLAGS

Change: 
 ```
LDFLAGS   = @ldflags@
```

To:
```
LDFLAGS   = @ldflags@ -Wl,-z,noexecstack
```
