### ISSUE TITLE
Consistent naming for REPRs

### ISSUE THREAD

**Issue by gerdr** [MoarVM/MoarVM#59]
The REPR name occurs in various places, among those the prefix of C structures and functions, file names, the `MVM_REPR_ID_*` constant and the actual user-exposed `name` member of the `MVMREPROps` structure.

Some names have a `VM` prefix for vm-specific but multi-backend types and some purely MoarVM-specific types have a `MVM` prefix.

For readability, both C prefixes `MVMVM` and `MVMMVM` get shortened to `MVM`. However, we also lost the distinction between `VM` and `MVM` REPRs where we need not do so, in particular the file names and REPR-ID constants.

For consistency, these should match their authorative, user-exposed names - eg `MVMString` should be kept as-is, but `MVMArray.c`, `MVMArray.h` and `MVM_REPR_ID_MVMArray` should be renamed to `VMArray*`.

**Comment by jnthn** [comment]
Trouble with this is that we'd then be exposing a bunch of symbols to the world without the MVM prefix, which doesn't seem desirable. I think we can live with the public REPR-name mismatch with the type name in the C code as the lesser evil.
