### ISSUE TITLE
can_be_smallint always returns false

### ISSUE THREAD

**Issue by zoffixznet** [MoarVM/MoarVM#594]
The [`can_be_smallint`](https://github.com/MoarVM/MoarVM/blob/957759c84be2cdf0f68da05d080828fd31fcdb5d/src/math/bigintops.c#L135-L139) routine always appears to return false.

It seems it needs a cast from `DIGIT` or something, but I don't know to what type...

When `i` is `15`, this prints `0`:
```
printf("%d\n", MVM_IS_32BIT_INT(DIGIT(i, 0)));
```

This prints `1`:
```
printf("%d\n", MVM_IS_32BIT_INT((uint32_t)DIGIT(i, 0)));
```

And this prints `1` too:
```
printf("%d\n", MVM_IS_32BIT_INT((long long)DIGIT(i, 0)));
```

The `DIGIT` is `mp_digit` that's defined to be `uint*_t` and `MVM_IS_32BIT_INT` macro is
```
MVM_IS_32BIT_INT(i)     (i >= -2147483648LL && i <= 2147483647LL)
```

**Comment by duke-m** [comment]
Hi, what do you mean with
> When i is 15

?

DIGIT:
```C
#define DIGIT(m,k) ((m)->dp[(k)])
```

see also [libtommath](https://github.com/libtom/libtommath/blob/develop/tommath.h#L162)

**Comment by zoffixznet** [comment]
There's an `i` variable in the quoted code:

    printf("%d\n", MVM_IS_32BIT_INT(DIGIT(i, 0)));

When it's set to 15, the described output is observed.

**Comment by duke-m** [comment]
but `i` is of type `mp_int`, isn't it? was just confused, because `MVM_IS_32BIT_INT(i)` DOES take a scalar but `DIGIT(m,k)` doesn't. can you post your whole test code? thanks

**Comment by zoffixznet** [comment]
>  can you post your whole test code

It's been three months and unfortunately, I don't remember how I came across this.

If there's no obvious issue with the code in question, we can just close this Issue.

**Comment by duke-m** [comment]
hello,

`MVM_IS_32BIT_INT((uint32_t)DIGIT(&number, 0)))` and `MVM_IS_32BIT_INT((unsigned long long)DIGIT(&number, 0)))` will always be true.

Okay, let's see...
```
printf("MVM_IS_32BIT_INT(-1): %i\n", MVM_IS_32BIT_INT(-1));
printf("MVM_IS_32BIT_INT(0): %i\n", MVM_IS_32BIT_INT(0));
printf("MVM_IS_32BIT_INT(2147483649): %i\n", MVM_IS_32BIT_INT(2147483649));
```
That will result in saying the first two are true (correct) and the last one is false (correct).

Now using variables with unknown types and sizes (see DIGIT_BIT and mp_digit) might not get the desired results.

Solution:
Either changing can_be_smallint:

```
static int can_be_smallint(const mp_int *i) {
    if (USED(i) != 1)
        return 0;
    return MVM_IS_32BIT_INT((long long)DIGIT(i, 0));
}
```

or (might be better) MVM_IS_32BIT_INT:

```
#define MVM_IS_32BIT_INT(i)  ((long long)i >= -2147483648LL && (long long)i <= 2147483647LL)
```

**Comment by duke-m** [comment]
@jnthn, I think we can close this one now, if you please :)
