### ISSUE TITLE
This is not initialized

### ISSUE THREAD

**Issue by bdw** [MoarVM/MoarVM#636]
https://github.com/MoarVM/MoarVM/blob/0ee9103236df139e3d75d0bc0bf7e26f7600e8b9/src/spesh/optimize.c#L1272

And it is in fact never written to.
So I'm not sure how this worked or is supposed to work and how to fix it.

**Comment by duke-m** [comment]
as I see it gets pointed to the static frame if (and only if) ic->count > 0 [some lines later](https://github.com/MoarVM/MoarVM/blob/0ee9103236df139e3d75d0bc0bf7e26f7600e8b9/src/spesh/optimize.c#L1277)

**Comment by coke** [comment]
Closing based on @duke-m's comments (code has moved to line 1824)
