### ISSUE TITLE
MVM_io_resolve_host_name should accept an optional sa_family argument

### ISSUE THREAD

**Issue by book** [MoarVM/MoarVM#683]
In `MVM_io_resolve_host_name`, the `result` struct in [the call to `getaddrinfo`](https://github.com/MoarVM/MoarVM/blob/0441e075b4f89f029492e156a54b02c8b3af8114/src/io/syncsocket.c#L242) is an [`addrinfo`](https://en.wikipedia.org/wiki/Getaddrinfo#struct_addrinfo), which is in fact a linked list, with the next item in the list is in `ai_next`.

Right now, `MVM_io_resolve_host_name` returns the first socket in the list. [The comment above the definition](https://github.com/MoarVM/MoarVM/blob/master/src/io/syncsocket.c#L231-L233) claims it's not an issue, however in Perl 6 [IO::Socket::INET](https://docs.perl6.org/type/IO::Socket::INET#method_new) accepts a `:$family` argument which defaults to 2 (i.e. IPv4).

This behaviour means that on a machine where `localhost` can be resolved in both IPv4 and IPv6,

    $ getent ahosts localhost
    ::1             STREAM localhost
    ::1             DGRAM  
    ::1             RAW    
    127.0.0.1       STREAM 
    127.0.0.1       DGRAM  
    127.0.0.1       RAW    

this code:

    my $server = IO::Socket::INET.new(:localhost<localhost>, :localport(4444), :listen);

will return an IPv6 socket (listening), even though, according to [the documentation](https://docs.perl6.org/type/IO::Socket::INET#method_new) and [the](https://github.com/rakudo/rakudo/blob/f1464e22f01bf03c67592eb3199d2a2d67cb564e/src/core/IO/Socket/INET.pm#L66) [code](https://github.com/rakudo/rakudo/blob/f1464e22f01bf03c67592eb3199d2a2d67cb564e/src/core/IO/Socket/INET.pm#L91), it should be IPv4.

I don't think it's actually necessary to iterate over the list, because [`getaddrinfo`](https://en.wikipedia.org/wiki/Getaddrinfo#getaddrinfo.28.29)'s third argument is a *hints* structure which can be either `NULL` (like it is at the moment in `MVM_io_resolve_host_name`) or an `addrinfo` structure with the type of service requested.

So, `MVM_io_resolve_host_name` should accept an **additional** (optional?) arguments, which could be  the *hints* structure to be passed to `getaddrinfo`, or at least a `ai_family` value that could be used to create the hints to be passed.

This way, the first item in the linked list would be an IPv4 or IPv6 socket depending on what was required on the Perl 6 side.

**Comment by duke-m** [comment]
with
```
::1               localhost
127.0.0.1         localhost
```

the family used/returned with your code above is 2 (IPv4), FreeBSD 11.1-RELEASE-p1, Rakudo version 2017.07 built on MoarVM version 2017.07.

**Comment by duke-m** [comment]
@samcv since you've just did some builds on FreeBSD, too, can you also check, if you please? thanks

**Comment by samcv** [comment]
I get family => 2 on FreeBSD 1.1. Localhost is pingable with ::1 or 127.0.0.1

**Comment by duke-m** [comment]
@book can you re-check and tell us what versions you are using? I always get family => 2 on all tested environments.
