### ISSUE TITLE
Regression: "Unable to allocate an array of 8 elements" exception on Windows

### ISSUE THREAD

**Issue by lefth** [MoarVM/MoarVM#686]
Since commit f9b65a9e37979ab39fd1283a65ad4e1351ca6058, building is successful but doing anything with moarvm gives the following error:

Unhandled exception: Unable to allocate an array of 8 elements
   at <unknown>:1  (src/vm/moar/stage0/ModuleLoader.moarvm:)
 from <unknown>:1  (src/vm/moar/stage0/ModuleLoader.moarvm:<dependencies+deserialize>)
 from <unknown>:1  (src/vm/moar/stage0/nqp.moarvm:<dependencies+deserialize>)

I'm using the build executables provided by Strawberry Perl. An example operation that shows the problem is running Configure.pl in a NQP project and using `--with-moar` to reference the built moarvm. This problem does not occur on Linux.

**Comment by niner** [comment]
Can you please test again with the fix from commit d78c370?

**Comment by lefth** [comment]
@niner d78c370 fixed it. Thanks!
