### ISSUE TITLE
⚠ AppVeyor does not run any tests

### ISSUE THREAD

**Issue by AlexDaniel** [MoarVM/MoarVM#697]
https://github.com/MoarVM/MoarVM/issues/693 is kinda resolved, but I can't see even a single time it passed without issues.

I think it should be consistently green in order to be useful.

**Comment by ugexe** [comment]
The irony.

**Comment by AlexDaniel** [comment]
bump.

**Comment by AlexDaniel** [comment]
We should have green status after https://github.com/MoarVM/MoarVM/pull/717 (and after JIT issues are resolved), but note that it won't be running any tests, just showing if it's possible to compile moar on windows.

**Comment by MasterDuke17** [comment]
We now use Azure pipelines and build+pass tests on Ubuntu, MacOS, and Windows.
