### ISSUE TITLE
JIT of NativeCall breaks some return values on Mac OS X

### ISSUE THREAD

**Issue by dmaestro** [MoarVM/MoarVM#763]
See https://github.com/niner/Inline-Perl5/issues/106

Rakudo commit a06ebaf21 enabled "Use the new nativeinvoke for calling JITed NC code directly" and also caused failure of the following test code (using Inline::Perl5) on MacOSX:
```
/usr/local/bin/perl6 -MInline::Perl5 -e 'my $a = EVAL "[]", :lang<Perl5>; my $b = EVAL "[]", :lang<Perl5>; say [ $a.elems, $b.elems ];'
```
Tested with Rakudo* 2017.10 on linux and Mac OS X.
Linux output:
`[0 0]`
Mac output:
`[0 4294967296]`

Running with `MVM_JIT_DISABLE` set produces the correct output.
Also tested with 2017.11, with the same results on both platforms.

**Comment by niner** [comment]
Fixed by https://github.com/MoarVM/MoarVM/commit/97615be0adab68fad5ab5fe89246647c989778d3
