### ISSUE TITLE
nqp::newthread with a loop directly in its code block segfaults

### ISSUE THREAD

**Issue by timo** [MoarVM/MoarVM#774]
https://github.com/MoarVM/MoarVM/blob/master/src/spesh/osr.c#L130

Here the `tc->cur_frame->caller` is null, so the code blows up.

**Comment by timo** [comment]
```
nqp-m -e 'my $t := nqp::newthread({ while 1 { nqp::sleep(1); say("hi") } }, 1); nqp::threadrun($t); nqp::threadjoin($t);'
```

**Comment by jnthn** [comment]
Test added in https://github.com/perl6/nqp/commit/89939e1947
