### ISSUE TITLE
2017.12 moarvm.org/releases tar file has different src/strings/ops.h than github tag

### ISSUE THREAD

**Issue by CurtTilmes** [MoarVM/MoarVM#778]
See https://github.com/rakudo/rakudo/issues/1377

Between 
`http://moarvm.org/releases/MoarVM-2017.12.tar.gz`
and
`https://github.com/MoarVM/MoarVM/archive/2017.12.tar.gz`

This file is different:
```
diff MoarVM-2017.12/src/strings/ops.h MoarVM/src/strings/ops.h
117,118c117,118
<  * If it is different debug information will be printed out. */
< #define MVM_DEBUG_NFG 1
---
>  * If it is different debug information will be printed out.
> #define MVM_DEBUG_NFG 1 */
120,121c120,121
<  * always checks every grapheme manually. Slower. (requires MVM_DEBUG_NFG) */
< #define MVM_DEBUG_NFG_STRICT 1
---
>  * always checks every grapheme manually. Slower. (requires MVM_DEBUG_NFG)
> #define MVM_DEBUG_NFG_STRICT 0 */
```

**Comment by jnthn** [comment]
Seems that our `make release` target could do with a check that the working tree is not dirty; that would have prevented somebody's local changes from ending up in the release. Perhaps a 2017.12.1 would be wise also.

**Comment by jnthn** [comment]
Fixed tarball at http://moarvm.org/releases/MoarVM-2017.12.1.tar.gz and commit to add sanity check to prevent this in the future at https://github.com/MoarVM/MoarVM/commit/ac123bb0b4.
