### ISSUE TITLE
Several spectest files fails when run with MVM_SPESH_NODELAY=1

### ISSUE THREAD

**Issue by dogbert17** [MoarVM/MoarVM#804]
This must be a relatively new problem, i.e. no more than a month old:

    dilbert@Linux-Mint18 ~/repos/rakudo $ ./perl6 -v
    This is Rakudo version 2018.01-204-gbeaad7b built on MoarVM version 2018.01-94-gc7774e3
    implementing Perl 6.c.

    dilbert@Linux-Mint18 ~/repos/rakudo $ MVM_SPESH_NODELAY=1 ./perl6 t/spec/MISC/bug-coverage.t 
    ===SORRY!===
    Iteration past end of iterator

    dilbert@Linux-Mint18 ~/repos/rakudo $ MVM_SPESH_NODELAY=1 MVM_SPESH_BLOCKING=1       ./perl6 t/spec/S32-str/windows-1251-windows-1252-encode-decode.t
    ===SORRY!===
    Iteration past end of iterator

**Comment by dogbert17** [comment]
Masterly detective work by AlexDaniel++ has uncovered a suspect, i.e. https://github.com/MoarVM/MoarVM/commit/c7774e37d2a08726aa51ab8c6262677f5369f982

**Comment by AlexDaniel** [comment]
> has uncovered a suspect, i.e. c7774e3

Proof:
* https://gist.github.com/Whateverable/ec3e52f2c72cad3243b5fc951768b2b3
* https://gist.github.com/Whateverable/9b94475c34efa52cbc27088fb95f3b5f

(https://github.com/rakudo/rakudo/commit/beaad7b979f99d07f546efa0d48b701e6372d9ae)

**Comment by zoffixznet** [comment]
Can't read the code in https://github.com/MoarVM/MoarVM/commit/c7774e37d2a08726aa51ab8c6262677f5369f982, but merely going by the commit title: `"Always split if_o into istrue and if_i"`. 

We can't decompose `if_o` into `istrue` + `if_i`, because the conditional is returned in 2-arg `if_o` if it's false and can be used in places:

```
<Zoffix__> m: use nqp; dd nqp::if(Nil, 42); dd nqp::if(Any, 42); dd nqp::if(Int, 42);
<camelia> rakudo-moar beaad7b97: OUTPUT: «Nil␤Any␤Int␤»
```

**Comment by zoffixznet** [comment]
Also worth mentioning, the bisect is using a test file for which tests for `if/unless` with native types and work for that was recently done https://github.com/perl6/nqp/commit/df45cb8ce9

Maybe the bug is in https://github.com/perl6/nqp/commit/df45cb8ce9 or that code and https://github.com/MoarVM/MoarVM/commit/c7774e37d2a08726aa51ab8c6262677f5369f982 simply exposed it.

**Comment by jnthn** [comment]
> We can't decompose if_o into istrue + if_i, because the conditional is returned in 2-arg if_o if it's false and can be use

At this level, we can do it. The concept of using a value multiple times in an `nqp::` op is a thing handled by the QAST -> MAST phase. The `if_o` and `unless_o` ops in MoarVM only really gives us more compact bytecode.

I don't immediately spot what's wrong, though the code path in question does optimize iterator end tests as part of what it does.

**Comment by AlexDaniel** [comment]
FWIW it is reproducible outside the spectest and also without MVM_SPESH_NODELAY, see https://github.com/rakudo/rakudo/issues/1534#issuecomment-366391924.

**Comment by bdw** [comment]
Spesh bisectable:
```
MVM_SPESH_NODELAY=1 perl ~/Code/Personal/MoarVM/tools/jit-bisect.pl --spesh -- ./perl6 t/spec/MISC/bug-coverage.t 
```

**Comment by zoffixznet** [comment]
> Spesh bisectable:
> MVM_SPESH_NODELAY=1 perl ~/Code/Personal/MoarVM/tools/jit-bisect.pl --spesh -- ./perl6 t/spec/MISC/bug-coverage.t

FWIW, that says: "SPESH Broken frame: 2402" and then makes two huge files [spesh-2402.txt](temp.perl6.party/spesh-2402.txt) and [spesh-2403.txt](https://temp.perl6.party/spesh-2403.txt)

**Comment by bdw** [comment]
Yeah, I get 2357, but it's probably the same frame. I'm thinking of patching the spesh logger to restrict logging to a certain frame.

**Comment by bdw** [comment]
This is a spesh log that I believe to be restricted to the broken frame
[spesh-log-3899.txt](https://github.com/MoarVM/MoarVM/files/1734759/spesh-log-3899.txt)

**Comment by bdw** [comment]
This strongly suggests  that at least some of the annotations (frame handler start/stop/goto) that indicate the 'start' of the instruction are now split in the last part of 'if_o' (being if_i), where they are supposed to be on the 'first' part of `if_o` (now being `istrue`)

**Comment by zoffixznet** [comment]
*(from latest commit message)*
> I believe this fixes MoarVM issue #804.

Unfortunately, the issue appears to persist:

```
cpan@perlbuild4~/R/rakudo (master)$ perl6 -v
This is Rakudo version 2018.01-86-g4a989a5 built on MoarVM version 2018.01-59-g6da2afe
implementing Perl 6.c.
cpan@perlbuild4~/R/rakudo (master)$ MVM_SPESH_NODELAY=1 ./perl6 t/spec/MISC/bug-coverage.t
===SORRY!===
Iteration past end of iterator
```

**Comment by zoffixznet** [comment]
Confirming the fix fixed the bug on my box.

**Comment by AlexDaniel** [comment]
Indeed, looks good. Thank you very much, @bdw!
