### ISSUE TITLE
Shouldn't finish/join current thread.

### ISSUE THREAD

**Issue by marcoonroad** [MoarVM/MoarVM#847]
While writing code for the fork of OO::Actors, I've found the following problem:

> Without prior checking of calling `join`/`finish` on current-thread, the MoarVM crashes.

The following code below is a simple illustration:

```perl6
$*THREAD.finish;
```

The abort message is the following:

```
MoarVM panic: Could not join thread: errorcode -3
```

(Sometimes the error-code is -35, tho.)

It's quite annoying to remember every-time to perform the following check:

```
if $*THREAD.id == $my-dear-thread-variable.id {
    # raising some error here...
}
else {
    # everything seems fine...
}
```

Therefore, such checking should be delegated inside the `join`/`finish` methods themselves.

I dunno if it is the right place to post that, but I'm a newcomer (still) in the Perl6 community.

---

Thanks in advance! :smiley:

**Comment by marcoonroad** [comment]
My Perl 6 version is the following:

```
This is Rakudo Star version 2018.01 built on MoarVM version 2018.01
implementing Perl 6.c.
```

I'm using currently the following machine:

```
Linux Ivalice 4.13.0-39-generic #44~16.04.1-Ubuntu SMP Thu Apr 5 16:43:55 UTC 2018 i686 i686 i686 GNU/Linux
```

**Comment by jnthn** [comment]
Yes, this is the correct place to report a MoarVM panic. I think we should be able to simply throw in this case, not panic, since it seems recoverable.
