### ISSUE TITLE
Missing allocations in --profile

### ISSUE THREAD

**Issue by lizmat** [MoarVM/MoarVM#853]
If I profile

    for ^1000000 { Nil }

it tells me there were 9 garbage collections, yet if I look at the Allocations tab, it tells me that only 4 objects were ever created?

So we're missing (quite a lot) of Allocations in the profiler?

**Comment by MasterDuke17** [comment]
Fixed in https://github.com/MoarVM/MoarVM/commit/8521118b17

**Comment by samcv** [comment]
@lizmat @MasterDuke17 looks fixed, good to close?

**Comment by MasterDuke17** [comment]
@samcv I believe so.
