### ISSUE TITLE
Apparent spesh problem with creating a lot of PseudoHashes in a loop

### ISSUE THREAD

**Issue by MasterDuke17** [MoarVM/MoarVM#865]
Hangs and pegs the cpu. See https://github.com/rakudo/rakudo/issues/1835. Bisected to https://github.com/rakudo/rakudo/commit/76af17a8b1dc79f8923109bbd284afed2e2fe011 which is an NQP bump. Corresponding MoarVM bump in NQP is https://github.com/perl6/nqp/commit/1d2f0fe.

**Comment by timo** [comment]
commented on the rakudo bug: spesh being able to inline the frame causes the pseudostash to contain a direct reference to itself, which causes an infinite recursion while .gist-ing it. i'd consider this "not a moar bug"
