### ISSUE TITLE
Unicode: Case folding special cases

### ISSUE THREAD

**Issue by moritz** [MoarVM/MoarVM#87]
The spectests have caught some cases where moar's case folding isn't sufficient.

In particular, in https://rt.perl.org/Ticket/Display.html?id=121377 I discuss some case folding rules for the German ß

    'ß'.uc;   # should be 'SS'
    'ß'.tclc  # should be 'Ssß'

Also, S32-str/lc.t has this test:

    is 'ΣΣΣ'.lc, 'σσς', 'lower-casing of greek Sigma respects word-final special case';

which raudo-jvm and rakudo-parrot get right, but moar fails (it produces `σσσ`).

**Comment by timo** [comment]
the linked-to RT ticket has been closed for rakudo-moar; we have impressive case-folding capabilities now.
