### ISSUE TITLE
Design of string_index_*

### ISSUE THREAD

**Issue by tisonkun** [MoarVM/MoarVM#874]
https://github.com/MoarVM/MoarVM/blob/eed6fbb312e909fe30bca9e09eb3a7ee1696deaa/src/strings/ops.c#L558

https://github.com/MoarVM/MoarVM/blob/eed6fbb312e909fe30bca9e09eb3a7ee1696deaa/src/strings/ops.c#L659

It's said that our string_index_* design is not that consistent at argument `start`. Sometimes we allow negative integer, sometime we reject, sometime we allow only `-1`.

Anyway, these might be reconsidered to keep somehow consistency.

It causes `nqp::index("xxy","y",-1)` returns `-1` but `nqp::rindex("xxy","y",-1)` returns `2`

**Comment by lizmat** [comment]
> On 10 Jun 2018, at 09:48, 陈梓立 <notifications@github.com> wrote:
> 
> https://github.com/MoarVM/MoarVM/blob/eed6fbb312e909fe30bca9e09eb3a7ee1696deaa/src/strings/ops.c#L558
> 
> https://github.com/MoarVM/MoarVM/blob/eed6fbb312e909fe30bca9e09eb3a7ee1696deaa/src/strings/ops.c#L659
> 
> It's said that our string_index_* design is not that consistent at argument start. Sometimes we allow negative integer, sometime we reject, sometime we allow only -1.
> 
> Anyway, these might be reconsidered to keep somehow consistency.
> 
> It causes nqp::index("xxy","y",-1) returns -1 but nqp::rindex("xxy","y",-1) returns 2

Another inconsistency:

nqp::rindex("xxy","y",-2)   # index start offset out of range

I would expect that to return -1.

**Comment by W4anD0eR96** [comment]
@samcv @timo @bdw any suggestions?

**Comment by samcv** [comment]
@W4anD0eR96 yeah I have noticed that and it is less than ideal. Anything less than -1 is unspecced in the nqp test suite so we could either disallow anything but -1 or allow you to specify negative indexes as being from the end of the string.

I don't mind whichever we choose.

**Comment by W4anD0eR96** [comment]
I prefer the latter, that is, specify negative indexes as being from the end of the string, and note that it might also cause out of range. Say `nqp::index("xxy", "y", -5)` is index out of range.

**Comment by jnthn** [comment]
Perl 6 doesn't allow negatives to `index` and `rindex` and makes one use `*-1` syntax instead, which ends up with the calculation of a positive index. So arguably there's no use case for us to support any negative values in MoarVM.

**Comment by pmichaud** [comment]
Arguably there's no _current_ use case.  :-)

However, NQP (and one of its primary authors) still has fantasies of using NQP and MoarVM to implement things other than Perl 6.  That said, I'm fine with postponing implement of that capability until it's actually needed.  (No comment as to whether this thread/issue rises to the level of "needed".)

Pm

**Comment by W4anD0eR96** [comment]
> Perl 6 doesn't allow negatives to index and rindex and makes one use *-1 syntax instead, which ends up with the calculation of a positive index. So arguably there's no use case for us to support any negative values in MoarVM.

Sure it is more expressive use `*-1` instead of `-1` and thus assert all pos-es are possitive. I was afraid of the cost of `nqp::elems` but it seems acceptable.

**Comment by W4anD0eR96** [comment]
@pmichaud sorry but isn't this a bug fix? or say we have to decide how `nqp::index` and `nqp::rindex` works.

**Comment by samcv** [comment]
In either case I think they should both be the same, which I see as a bug. The only question is which way to change them to conform to. IMO we should change both to conform to how nqp::index does it since that one is used more often.

**Comment by pmichaud** [comment]
I think it's sometimes better to postpone decisions until we actually have immediate use cases to guide the choices.  One might even say that delayed binding in design is a feature as much as it is in programs.  :)

Put another way, it's okay to say that some features (inputs) currently produce undefined results, and that's not necessarily a bug.  It's simply a choice to delay the definition until we have better data/experience upon which to make a decision.

Pm

**Comment by TisonKun** [comment]
Closed as the discussion is over.

**Comment by AlexDaniel** [comment]
But it's still an issue?

**Comment by tisonkun** [comment]
As https://github.com/rakudo/rakudo/issues/1222#issuecomment-346952020, close this one. Please file another to continue the discussion if any.
