### ISSUE TITLE
Intel Skylake pause instruction slowness

### ISSUE THREAD

**Issue by abraxxa** [MoarVM/MoarVM#877]
Not sure if MoarVM or Rakudo is the correct layer but this might also Perl 6:
https://aloiskraus.wordpress.com/2018/06/16/why-skylakex-cpus-are-sometimes-50-slower-how-intel-has-broken-existing-code/

**Comment by zoffixznet** [comment]
Condensed version of the article:

> This is not a .NET issue. It affects all Spinlock implementations which use the `pause` instruction.

**Comment by samcv** [comment]
@abraxxa I don't see the `pause` instruction when I compile MoarVM with clang 5. I checked by running:
```
objdump -d libmoar.so | grep pause
objdump -d moar | grep pause
```

I did not get any results. Was this posted as informational in case we used the pause instruction or do you have information that we are use `pause` or are affected by this issue?

**Comment by abraxxa** [comment]
I just stumbled over the blog post and thought that might affect MoarVM/Rakudo as well.
If not that‘s good!
Maybe Perl 6 on the JVM or Javascript?

**Comment by samcv** [comment]
Going to close.
