### ISSUE TITLE
Build fails on NetBSD with default config

### ISSUE THREAD

**Issue by Kaiepi** [MoarVM/MoarVM#917]
[jit/core_templates.h can't be found by the compiler](https://gist.github.com/Kaiepi/a70d442fbc4ca6d19071dc687ed836be) when building with make. Using gmake instead stops it from happening, but that's not the default setting and it doesn't come installed with the OS. I tested on FreeBSD and OpenBSD and didn't run into this issue.

- OS
NetBSD nbsd.vm.kennel.qt 8.0 NetBSD 8.0 (GENERIC) #0: Tue Jul 17 14:59:51 UTC 2018  mkrepro@mkrepro.NetBSD.org:/usr/src/sys/arch/amd64/compile/GENERIC amd64
- Version
2018.06-309-g428ed0e2a

**Comment by krytarowski** [comment]
Can you use a version from pkgsrc? http://pkgsrc.se/devel/MoarVM

**Comment by Kaiepi** [comment]
pkgsrc's version of MoarVM is 2017.09, along with nqp and Rakudo. Packages using features introduced since then wouldn't be usable.

I'll see if I can fix this though, since someone's bound to run into this problem eventually

**Comment by Kaiepi** [comment]
The problem's with the use of `$<` in the Makefile. BSD make uses `$(.TARGET)` instead, even though certain versions of it are compatible with `$<`. I'll have a fix ready tomorrow
