### ISSUE TITLE
Test fail on file-ops

### ISSUE THREAD

**Issue by TisonKun** [MoarVM/MoarVM#919]
Recently I unfudge some tests on NQP https://github.com/perl6/nqp/commit/15c9774719f98c0c04252a3a1712b35c84b29931

It cause MoarVM travis-ci fails. I could trouble shoot as below

```nqp
# t/nqp/019-file-ops.t L344-351
    for [nqp::const::STAT_MODIFYTIME, nqp::const::STAT_ACCESSTIME, nqp::const::STAT_CHANGETIME] -> $flag {
      ok(nqp::stat_time($file, $flag) == nqp::lstat_time($file, $flag), 'stat_time works as lstat_time on regular file');
      ok(nqp::stat($file, $flag) == nqp::lstat($file, $flag), 'stat works as lstat on regular file');
      ok(nqp::stat_time($symlink, $flag) == nqp::lstat_time($file, $flag), 'stat_time follows symlink');
      if ($flag != nqp::const::STAT_CHANGETIME) {
          ok(nqp::lstat_time($symlink, $flag) != nqp::lstat_time($file, $flag), 'lstat_time doesn\'t follow symlink');
      }
    }
```

so the problem is when `$flag == nqp::const::STAT_CHANGETIME`, it fails on `ok(nqp::lstat_time($symlink, $flag) != nqp::lstat_time($file, $flag), 'lstat_time doesn\'t follow symlink');`

i wonder whether this is by design or a bug we could fix it?

**Comment by TisonKun** [comment]
addition: it doesn't fail on all build opt, but one of the below

or `MVM_OPTIONS="--no-jit" CC='gcc'`
or `MVM_OPTIONS="" CC='gcc'`
or `MVM_OPTIONS="--no-jit" CC='clang'`
or `MVM_OPTIONS="" CC='clang'`

**Comment by TisonKun** [comment]
cc @bdw

**Comment by bdw** [comment]
It fails with or without JIT, so I don't think the JIT is involved?

**Comment by TisonKun** [comment]
@bdw correct. I look again the tarvis report, actually it fails on macOS and pass on Linux.
