### ISSUE TITLE
MoarVM build broken on 32 bit systems

### ISSUE THREAD

**Issue by dogbert17** [MoarVM/MoarVM#940]
A recent commit, i.e. 62a99bcf44d7c481, seems to inadvertently have broken the build on 32 bit systems. 

    dogbert@dogbert-VirtualBox ~/repos/rakudo/nqp/MoarVM $ pwd
    /home/dogbert/repos/rakudo/nqp/MoarVM
    dogbert@dogbert-VirtualBox ~/repos/rakudo/nqp/MoarVM $ git status
    On branch master
    Your branch is up to date with 'origin/master'.
    
    nothing to commit, working tree clean
    dogbert@dogbert-VirtualBox ~/repos/rakudo/nqp/MoarVM $ perl Configure.pl --debug --prefix=../../install/
    Welcome to MoarVM!
    
    Updating submodules .................................... OK
    Configuring native build environment ................... 
        trying to compile a simple C program ............... YES
        probing support of -Werror=* ....................... YES
        Testing pkgconfig .................................. 0.26
    OK
    
        probing whether your compiler thinks that it is gcc  YES
        probing how your compiler does static inline ....... static __inline__
        your CPU can read unaligned values for all of int32 int64 num64
        probing the size of pointers ....................... 4
    JIT isn't supported on platforms with 4 byte pointers.
        probing C type support for: _Bool, bool ............ YES: _Bool,bool
        probing computed goto support ...................... YES
        probing pthread_yield support ...................... NO
        probing support of rdtscp intrinsic ................ YES
    
            make: make
         compile: gcc -Werror=declaration-after-statement -Werror=pointer-arith -O3 -DNDEBUG -g3  -D_REENTRANT -D_FILE_OFFSET_BITS=64 -fPIC -DDEBUG_HELPERS
        includes:  -I3rdparty/libuv/include -I3rdparty/libuv/src -I3rdparty/libatomicops/src -I3rdparty/libtommath -I3rdparty/dyncall/dynload -I3rdparty/dyncall/dyncall -I3rdparty/dyncall/dyncallback
            link: gcc  -O3 -DNDEBUG -g3 -Wl,-rpath,"/@libdir@"
            libs: -lm -lpthread -lrt -ldl
    
      byte order: little endian
    
    Configuring 3rdparty libs .............................. OK
    
      3rdparty: 3rdparty/cmp/libcmp.a
                3rdparty/dyncall/dyncall/libdyncall_s.a
                3rdparty/dyncall/dyncallback/libdyncallback_s.a
                3rdparty/dyncall/dynload/libdynload_s.a
                3rdparty/libatomicops/src/libatomic_ops.a
                3rdparty/libtommath/libtommath.a
                3rdparty/libuv/libuv.a
                3rdparty/sha1/libsha1.a
                3rdparty/tinymt/libtinymt.a
    
    Generating src/gen/config.c ............................ OK
    Generating src/gen/config.h ............................ OK
    Generating Makefile .................................... OK
    Generating tools/check.mk .............................. OK
    Generating build/mk-moar-pc.pl ......................... OK
    
    Configuration SUCCESS.
    
    Type 'make' to build and 'make help' to see a list of
    available make targets.
    dogbert@dogbert-VirtualBox ~/repos/rakudo/nqp/MoarVM $ make -j6 install
    compiling src/main.o
    compiling src/core/callsite.o
    compiling src/core/args.o
    compiling src/core/exceptions.o
    compiling src/core/interp.o
    compiling src/core/threadcontext.o
    src/core/exceptions.c: In function ‘handler_can_handle’:
    src/core/exceptions.c:85:57: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
         MVMuint64           block_label = block_has_label ? (MVMuint64)(f->work[fh->label_reg].o) : 0;
                                                             ^
    src/core/exceptions.c:86:49: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
         MVMuint64          thrown_label = payload ? (MVMuint64)payload : 0;
                                                     ^
    src/core/exceptions.c: In function ‘search_frame_handlers_lex’:
    src/core/exceptions.c:188:13: warning: this decimal constant is unsigned only in ISO C90 [enabled by default]
                 if (fh->category_mask == MVM_EX_INLINE_BOUNDARY) {
                 ^
    src/core/exceptions.c:229:13: warning: this decimal constant is unsigned only in ISO C90 [enabled by default]
                 if (fh->category_mask == MVM_EX_INLINE_BOUNDARY) {
                 ^
    src/main.c: In function ‘main’:
    src/main.c:235:21: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘MVMint64’ [-Wformat=]
                         fprintf(stderr, "ERROR: debug server port out of range. We only accept ports above 1024 and below 65535. (got: %lu)\n", port);
                         ^
    src/core/interp.c: In function ‘MVM_interp_run’:
    src/core/interp.c:1906:42: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
                     GET_REG(cur_op, 0).i64 = (MVMint64)GET_REG(cur_op, 2).o;
                                              ^
    src/core/interp.c:5998:39: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
                     char      *cache    = (char *)MVM_BC_get_I64(cur_op, 12);
                                           ^
    compiling src/core/compunit.o
    compiling src/core/bytecode.o
    compiling src/core/frame.o
    compiling src/core/callstack.o
    compiling src/core/validation.o
    compiling src/core/bytecodedump.o
    compiling src/core/threads.o
    compiling src/core/ops.o
    compiling src/core/hll.o
    compiling src/core/loadbytecode.o
    compiling src/math/num.o
    compiling src/math/grisu.o
    compiling src/core/coerce.o
    compiling src/core/dll.o
    compiling src/core/ext.o
    compiling src/core/nativecall.o
    compiling src/core/nativecall_dyncall.o
    compiling src/core/continuation.o
    src/core/nativecall_dyncall.c: In function ‘MVM_nativecall_invoke’:
    src/core/nativecall_dyncall.c:804:25: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
                             (MVMint64)*(DCpointer *)free_rws[num_rws]);
                             ^
    compiling src/core/intcache.o
    compiling src/core/fixedsizealloc.o
    compiling src/core/regionalloc.o
    compiling src/debug/debugserver.o
    compiling src/gen/config.o
    compiling src/gc/orchestrate.o
    src/debug/debugserver.c: In function ‘request_thread_resumes’:
    src/debug/debugserver.c:704:9: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘size_t’ [-Wformat=]
             fprintf(stderr, "wrong state to resume from: %lu\n", MVM_load(&tc->gc_status));
             ^
    src/debug/debugserver.c:740:9: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘size_t’ [-Wformat=]
             fprintf(stderr, "success resuming thread; its status is now %lu\n", MVM_load(&tc->gc_status));
             ^
    src/debug/debugserver.c: In function ‘write_stacktrace_frames’:
    src/debug/debugserver.c:791:9: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘MVMuint64’ [-Wformat=]
             fprintf(stderr, "dumping a stack trace of %lu frames\n", stack_size);
             ^
    src/debug/debugserver.c: In function ‘MVM_debugserver_add_breakpoint’:
    src/debug/debugserver.c:982:9: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 5 has type ‘MVMuint64’ [-Wformat=]
             fprintf(stderr, "asked to set a breakpoint for file %s line %u to send id %lu\n", argument->file, argument->line, argument->id);
             ^
    src/debug/debugserver.c:1017:9: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘MVMuint64’ [-Wformat=]
             fprintf(stderr, "breakpoint settings: index %u bpid %lu lineno %u suspend %u backtrace %u\n", found->breakpoints_used - 1, argument->id, argument->line, argument->suspend, argument->stacktrace);
             ^
    src/debug/debugserver.c: In function ‘MVM_debugserver_clear_breakpoint’:
    src/debug/debugserver.c:1077:13: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘MVMuint64’ [-Wformat=]
                 fprintf(stderr, "breakpoint index %u has id %lu, is at line %u\n", bpidx, bp_info->breakpoint_id, bp_info->line_no);
                 ^
    src/debug/debugserver.c:1086:13: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘MVMuint64’ [-Wformat=]
                 fprintf(stderr, "breakpoint index %u has id %lu, is at line %u\n", bpidx, bp_info->breakpoint_id, bp_info->line_no);
                 ^
    src/debug/debugserver.c:1090:17: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘MVMuint64’ [-Wformat=]
                     fprintf(stderr, "breakpoint with id %ld cleared\n", bp_info->breakpoint_id);
                     ^
    src/debug/debugserver.c: In function ‘create_context_or_code_obj_debug_handle’:
    src/debug/debugserver.c:1276:13: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘size_t’ [-Wformat=]
                 fprintf(stderr, "can only retrieve a context or code obj handle if thread is 'UNABLE' (is %lu)\n", to_do->body.tc->gc_status);
                 ^
    src/debug/debugserver.c: In function ‘request_context_lexicals’:
    src/debug/debugserver.c:1374:13: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘MVMuint64’ [-Wformat=]
                 fprintf(stderr, "will write %lu lexicals\n", lexcount);
                 ^
    In file included from src/moar.h:100:0,
                     from src/debug/debugserver.c:1:
    src/strings/uthash.h:763:20: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘MVMuint64’ [-Wformat=]
                 struct UT_hash_handle *current_hh =\
                        ^
    src/debug/debugserver.c:1376:9: note: in expansion of macro ‘HASH_ITER’
             HASH_ITER(dtc, hash_handle, lexical_names, entry, {
             ^
    src/debug/debugserver.c: In function ‘socket_reader’:
    src/debug/debugserver.c:2171:9: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘size_t’ [-Wformat=]
             fprintf(stderr, "asked to read %lu bytes\n", limit);
             ^
    src/debug/debugserver.c:2183:13: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘size_t’ [-Wformat=]
                 fprintf(stderr, "%lu ", read);
                 ^
    src/debug/debugserver.c:2189:9: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘size_t’ [-Wformat=]
             fprintf(stderr, "... recv received %lu bytes\n", total_read);
             ^
    src/debug/debugserver.c: In function ‘socket_writer’:
    src/debug/debugserver.c:2205:9: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘size_t’ [-Wformat=]
             fprintf(stderr, "asked to send %3lu bytes: ", limit);
             ^
    src/debug/debugserver.c:2217:13: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘size_t’ [-Wformat=]
                 fprintf(stderr, "%2lu ", sent);
                 ^
    src/debug/debugserver.c:2222:9: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘size_t’ [-Wformat=]
             fprintf(stderr, "... send sent %3lu bytes\n", total_sent);
             ^
    src/debug/debugserver.c: In function ‘debugserver_worker’:
    src/debug/debugserver.c:2529:9: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘MVMuint64’ [-Wformat=]
             snprintf(portstr, 16, "%lu", port);
             ^
    src/debug/debugserver.c:2529:9: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘MVMuint64’ [-Wformat=]
    src/debug/debugserver.c:2606:17: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘MVMuint64’ [-Wformat=]
                     fprintf(stderr, "debugserver received packet %lu, command %u\n", argument.id, argument.type);
                     ^
    compiling src/gc/allocation.o
    compiling src/gc/worklist.o
    compiling src/gc/roots.o
    compiling src/gc/collect.o
    compiling src/gc/gen2.o
    compiling src/gc/wb.o
    compiling src/gc/objectid.o
    compiling src/gc/finalize.o
    compiling src/gc/debug.o
    src/gc/objectid.c: In function ‘MVM_gc_object_id’:
    src/gc/objectid.c:11:14: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
             id = (MVMuint64)obj;
                  ^
    src/gc/objectid.c:33:14: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
             id = (MVMuint64)entry->gen2_addr;
                  ^
    compiling src/io/io.o
    compiling src/io/eventloop.o
    compiling src/io/syncfile.o
    compiling src/io/syncsocket.o
    compiling src/io/fileops.o
    compiling src/io/dirops.o
    compiling src/io/procops.o
    compiling src/io/timers.o
    compiling src/io/filewatchers.o
    compiling src/io/signals.o
    compiling src/io/asyncsocket.o
    compiling src/io/asyncsocketudp.o
    compiling src/6model/reprs.o
    compiling src/6model/reprconv.o
    compiling src/6model/containers.o
    compiling src/6model/parametric.o
    compiling src/6model/reprs/MVMString.o
    compiling src/6model/reprs/VMArray.o
    compiling src/6model/reprs/MVMHash.o
    compiling src/6model/reprs/MVMCFunction.o
    compiling src/6model/reprs/KnowHOWREPR.o
    compiling src/6model/reprs/KnowHOWAttributeREPR.o
    compiling src/6model/reprs/P6str.o
    compiling src/6model/reprs/P6opaque.o
    compiling src/6model/reprs/MVMCode.o
    src/6model/reprs/P6opaque.c: In function ‘dump_p6opaque’:
    src/6model/reprs/P6opaque.c:1749:33: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘MVMint64’ [-Wformat=]
                                     fprintf(stderr, "=%ld", val);
                                     ^
    compiling src/6model/reprs/MVMOSHandle.o
    compiling src/6model/reprs/MVMCompUnit.o
    compiling src/6model/reprs/MVMStaticFrame.o
    compiling src/6model/reprs/P6int.o
    compiling src/6model/reprs/P6num.o
    compiling src/6model/reprs/Uninstantiable.o
    compiling src/6model/reprs/HashAttrStore.o
    compiling src/6model/reprs/MVMThread.o
    compiling src/6model/reprs/MVMIter.o
    compiling src/6model/reprs/MVMContext.o
    compiling src/6model/reprs/SCRef.o
    compiling src/6model/reprs/MVMCallCapture.o
    compiling src/6model/reprs/P6bigint.o
    compiling src/6model/reprs/NFA.o
    compiling src/6model/reprs/MVMException.o
    compiling src/6model/reprs/MVMDLLSym.o
    compiling src/6model/reprs/MVMMultiCache.o
    compiling src/6model/reprs/MVMContinuation.o
    compiling src/6model/reprs/NativeCall.o
    compiling src/6model/reprs/CPointer.o
    compiling src/6model/reprs/CStr.o
    compiling src/6model/reprs/CArray.o
    compiling src/6model/reprs/CStruct.o
    compiling src/6model/reprs/CUnion.o
    compiling src/6model/reprs/ReentrantMutex.o
    compiling src/6model/reprs/ConditionVariable.o
    compiling src/6model/reprs/Semaphore.o
    compiling src/6model/reprs/ConcBlockingQueue.o
    compiling src/6model/reprs/MVMAsyncTask.o
    compiling src/6model/reprs/MVMNull.o
    compiling src/6model/reprs/CPPStruct.o
    compiling src/6model/reprs/NativeRef.o
    compiling src/6model/reprs/MultiDimArray.o
    compiling src/6model/reprs/Decoder.o
    compiling src/6model/reprs/MVMSpeshLog.o
    compiling src/6model/reprs/MVMStaticFrameSpesh.o
    compiling src/6model/6model.o
    compiling src/6model/bootstrap.o
    compiling src/6model/sc.o
    compiling src/6model/serialization.o
    compiling src/mast/compiler.o
    compiling src/mast/driver.o
    compiling src/spesh/dump.o
    compiling src/spesh/graph.o
    compiling src/spesh/codegen.o
    compiling src/spesh/candidate.o
    compiling src/spesh/manipulate.o
    compiling src/spesh/args.o
    compiling src/spesh/usages.o
    compiling src/spesh/facts.o
    compiling src/spesh/optimize.o
    compiling src/spesh/dead_bb_elimination.o
    compiling src/spesh/dead_ins_elimination.o
    src/spesh/optimize.c: In function ‘optimize_coverage_log’:
    src/spesh/optimize.c:1967:26: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
         char *cache        = (char *)ins->operands[3].lit_i64;
                              ^
    compiling src/spesh/deopt.o
    compiling src/spesh/log.o
    compiling src/spesh/threshold.o
    compiling src/spesh/inline.o
    src/spesh/inline.c: In function ‘merge_graph’:
    src/spesh/inline.c:739:5: warning: this decimal constant is unsigned only in ISO C90 [enabled by default]
         inliner->handlers[*inline_boundary_handler].category_mask = MVM_EX_INLINE_BOUNDARY;
         ^
    compiling src/spesh/osr.o
    compiling src/spesh/lookup.o
    compiling src/spesh/iterator.o
    compiling src/spesh/worker.o
    compiling src/spesh/debug.o
    compiling src/spesh/stats.o
    compiling src/spesh/plan.o
    compiling src/spesh/arg_guard.o
    compiling src/spesh/plugin.o
    compiling src/spesh/frame_walker.o
    compiling src/strings/decode_stream.o
    compiling src/strings/ascii.o
    compiling src/strings/parse_num.o
    compiling src/strings/utf8.o
    compiling src/strings/utf8_c8.o
    compiling src/strings/nfg.o
    compiling src/strings/ops.o
    compiling src/strings/unicode.o
    compiling src/strings/normalize.o
    compiling src/strings/latin1.o
    compiling src/strings/utf16.o
    compiling src/strings/windows1252.o
    compiling src/strings/shiftjis.o
    compiling src/strings/shiftjis_codeindex.o
    compiling src/math/bigintops.o
    compiling src/profiler/instrument.o
    compiling src/profiler/log.o
    src/profiler/instrument.c: In function ‘dump_call_graph_node’:
    src/profiler/instrument.c:411:23: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
                 box_i(tc, (MVMint64)pcn->sf));
                           ^
    src/profiler/instrument.c:427:23: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
                 box_i(tc, (MVMint64)pcn->native_target_name));
                           ^
    src/profiler/instrument.c:469:68: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
                 MVM_repr_bind_key_o(tc, alloc_info, pds->id, box_i(tc, (MVMint64)type));
                                                                        ^
    src/profiler/log.c: In function ‘MVM_profile_log_allocated’:
    src/profiler/log.c:230:31: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
             MVMuint32 distance = ((MVMuint64)tc->nursery_alloc - (MVMuint64)obj);
                                   ^
    src/profiler/log.c:230:62: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
             MVMuint32 distance = ((MVMuint64)tc->nursery_alloc - (MVMuint64)obj);
                                                                  ^
    src/profiler/log.c:238:13: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
             if ((MVMuint64)obj > (MVMuint64)tc->nursery_tospace && distance <= obj->header.size && obj != ptd->last_counted_allocation) {
                 ^
    src/profiler/log.c:238:30: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
             if ((MVMuint64)obj > (MVMuint64)tc->nursery_tospace && distance <= obj->header.size && obj != ptd->last_counted_allocation) {
                                  ^
    compiling src/profiler/profile.o
    compiling src/profiler/heapsnapshot.o
    compiling src/profiler/telemeh.o
    compiling src/instrument/crossthreadwrite.o
    compiling src/instrument/line_coverage.o
    src/instrument/line_coverage.c: In function ‘instrument_graph’:
    src/instrument/line_coverage.c:250:36: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
             ins->operands[3].lit_i64 = (MVMint64)line_report_store;
                                        ^
    compiling src/platform/sys.o
    compiling src/platform/random.o
    compiling src/platform/memmem32.o
    compiling src/moar.o
    src/moar.c: In function ‘MVM_vm_create_instance’:
    src/moar.c:97:51: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
         instance->hashSecrets[0] ^= ptr_hash_64_to_64((MVMuint64)instance);
                                                       ^
    compiling src/platform/posix/mmap.o
    compiling src/platform/posix/time.o
    compiling src/platform/posix/io.o
    compiling src/jit/stub.o
    /usr/bin/perl build/mk-moar-pc.pl pkgconfig/moar.pc
    linking libmoar.so
    linking moar
    ./libmoar.so: undefined reference to `MVM_jit_code_copy'
    collect2: error: ld returned 1 exit status
    make: *** [moar] Error 1

**Comment by niner** [comment]
Should be fixed in commit d19c66084d262758ee9367af244ab43344fc923b
Thanks for reporting!
