### ISSUE TITLE
Intermitent problems with Grammar.MoarVM

### ISSUE THREAD

**Issue by JJ** [MoarVM/MoarVM#943]
I have seen this error in a couple of places: in [Toaster](https://toast.perl6.party/module?module=DB::Model::Easy&commit=2018.06-434-g66aa689) and in [the perl6/doc tests](https://travis-ci.com/Raku/doc/builds/148729002?utm_medium=notification&utm_source=email). It goes like this

```
# Use of uninitialized value of type Any in string context.
# Methods .^name, .perl, .gist, or .say can be used to stringify it to 
# 
# There's been this error in file: xt/aspell.t
# something meaningful.
# 
# 
# There's been this error in file: xt/double-dots.t
# Use of uninitialized value of type Any in string context.
# Methods .^name, .perl, .gist, or .say can be used to stringify it to 
# 
# There's been this error in file: xt/double-dots.t
# something meaningful.
# 
# 
# There's been this error in file: xt/double-dots.t
#   in any statement_control at /root/.rakudobrew/moar-master/install/share/nqp/lib/Perl6/Grammar.moarvm line 1
# Use of uninitiali
# 
# There's been this error in file: xt/double-dots.t
# zed value of type Any in string context.
# Methods .^name, .perl, .gist, or .say can be used to stringify it to something meaningful.
#   in any statement_control at /root/.rakudobrew/moar-master/install/share/nqp/lib/Perl6/Grammar.moarvm line 1
# 
# 
# There's been this error in file: xt/aspell.t
#   in any statement_control at /root/.rakudobrew/moar-master/install/share/nqp/lib/Perl6/Grammar.moarvm line 1
# Use of uninitiali
# 
# There's been this error in file: xt/aspell.t
# zed value of type Any in string context.
# Methods .^name, .perl, .gist, or .say can be used to stringify it to something meaningful.
#   in any statement_control at /root/.rakudobrew/moar-master/install/share/nqp/lib/Perl6/Grammar.moarvm line 1
# 
# 
```
But it's got nothing to do with the file itself. It happens sometimes in different files, or not happen at all. It does happen when there's a massive amount of files that are being examined in parallel, apparently. Other than that, I don't feel able to reproduce it, other than point out to places where it's happening. Sorry...

**Comment by jnthn** [comment]
How have you determined this MoarVM-related rather thank Rakudo-related?

**Comment by JJ** [comment]
Just a hunch, really. Also the fact that it mentions Grammar.moarvm.  Also the fact that it's intermitent, so it might go all the way down to the way things work Down There. So, not really sure. It could be nqp, for all I know. I a nutshell: I have no idea.
Would you say it's MoarVM related?

**Comment by JJ** [comment]
I'll try that. Thanks!

**Comment by niner** [comment]
MoarVM is innocent in this case. It's a bug in rakudo regarding concurrent re-checking of precompiled dependencies triggered by `use lib` after loading modules in some of p6doc's test files.

**Comment by JJ** [comment]
Can you please clarify a bit? We would like to have that bug fixed, after
all...

**Comment by niner** [comment]
https://github.com/rakudo/rakudo/commit/f5ce80e1a6
