### ISSUE TITLE
Spectest failures when the DU chain checker is enabled

### ISSUE THREAD

**Issue by dogbert17** [MoarVM/MoarVM#960]
Enabling the DU chain checker has uncovered problems with some spectest files. This feels like a regression.

    dogbert@dogbert-VirtualBox ~/repos/rakudo/nqp/MoarVM $ git diff
    diff --git a/src/spesh/usages.h b/src/spesh/usages.h
    index 2c82fda..a7700ad 100644
    --- a/src/spesh/usages.h
    +++ b/src/spesh/usages.h
    @@ -1,5 +1,5 @@
     /* Option to enable checking of define/use chains for debugging purposes. */
    -#define MVM_SPESH_CHECK_DU 0
    +#define MVM_SPESH_CHECK_DU 1
     
     /* Usage information, which is held per SSA written register. */
     struct MVMSpeshUsages {

    dogbert@dogbert-VirtualBox ~/repos/rakudo $ ./perl6-gdb-m t/spec/S02-literals/quoting.t
    ================================================================================================
    This is Rakudo Perl 6 running in the GNU debugger, which often allows the user to generate useful back-
    traces to debug or report issues in Rakudo, the MoarVM backend or the currently running code.
    
    This Rakudo version is 2018.08.84.g.78.bebc.7 built on MoarVM version 2018.08.46.gfb.8976.a,
    running on linuxmint (18.3.Sylvia) / linux (4.10.0.38.generic)
    
    Type `bt full` to generate a backtrace if applicable, type `q` to quit or `help` for help.
    ------------------------------------------------------------------------------------------------
    Reading symbols from /home/dogbert/repos/rakudo/install/bin/moar...done.
    Starting program: /home/dogbert/repos/rakudo/install/bin/moar --execname=./perl6-gdb-m --libpath=. --libpath=blib --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib /home/dogbert/repos/rakudo/perl6.moarvm --nqp-lib=blib t/spec/S02-literals/quoting.t
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
    [New Thread 0x7ffff633f700 (LWP 2632)]
    MoarVM oops: Malformed DU chain: reading sp_getspeshslot of 6(1) not in graph
    Spesh of '' (cuid: 110, file: gen/moar/BOOTSTRAP.nqp:2186)
    Callsite 0x7ffff7d293a0 (1 args, 1 pos)
    Positional flags: obj
    
      BB 0 (0x7fffec6d3e00):
        line: 2186 (pc 0)
        Instructions:
          no_op           
        Successors: 1
        Predecessors: 
        Dominance children: 1
    
      BB 1 (0x7fffec6d3e88):
        line: 2186 (pc 0)
        Instructions:
          sp_getarg_o       r0(2), liti16(0)
          [Annotation: INS Deopt One (idx 0 -> pc 20; line 2187)]
          [Annotation: Logged (bytecode offset 14)]
          [Annotation: Line Number: gen/moar/BOOTSTRAP.nqp:2186]
          set               r3(2),   r0(2)
        Successors: 2
        Predecessors: 0
        Dominance children: 2
    
      BB 2 (0x7fffec6d3ee8):
        line: 2187 (pc 20)
        Instructions:
          set               r1(2),   r3(2)
          wval              r3(3), liti16(0), liti16(31) (P6opaque: Routine)
          [Annotation: INS Deopt One (idx 1 -> pc 48; line 2188)]
          [Annotation: Logged (bytecode offset 34)]
          sp_p6ogetvc_o     r4(2),   r1(2), liti16(48), sslot(1)
          set               r2(2),   r4(2)
          [Annotation: Logged (bytecode offset 54)]
          sp_decont         r4(5),   r2(2)
        Successors: 3
        Predecessors: 1
        Dominance children: 3
    
      BB 3 (0x7fffec6d3f48):
        line: 2189 (pc 60)
        Instructions:
          [Annotation: INS Deopt One (idx 2 -> pc 60; line 2189)]
          sp_guardtype      r4(3),   r4(5), sslot(0), litui32(60)
          const_i64_16      r5(1), liti16(0)
          const_s           r6(1), lits(perl6)
          sp_getspeshslot   r4(4), sslot(2)
          return_o          r4(4)
        Successors: 
        Predecessors: 2
        Dominance children: 
    
    
    Facts:
          r0(0): usages=0, flags=0    
          r0(1): usages=0, flags=0     DeadWriter
          r0(2): usages=1, flags=13    KnTyp Dcntd Concr
    
          r1(0): usages=0, flags=0    
          r1(1): usages=0, flags=0     DeadWriter
          r1(2): usages=1, flags=13    KnTyp Dcntd Concr
    
          r2(0): usages=0, flags=0    
          r2(1): usages=0, flags=0     DeadWriter
          r2(2): usages=1, flags=0    
    
          r3(0): usages=0, flags=0    
          r3(1): usages=0, flags=0     DeadWriter
          r3(2): usages=1, deopt=0, flags=13    KnTyp Dcntd Concr
          r3(3): usages=0, flags=23    KnTyp KnVal Dcntd TyObj
    
          r4(0): usages=0, flags=0    
          r4(1): usages=0, flags=0     DeadWriter
          r4(2): usages=1, deopt=1, flags=0    
          r4(3): usages=0, deopt=2, flags=277   KnTyp Dcntd TyObj LogGd
          r4(4): usages=1, flags=259   KnTyp KnVal LogGd
          r4(5): usages=1, flags=4     Dcntd
    
          r5(0): usages=0, flags=0    
          r5(1): usages=0, flags=258   KnVal LogGd
    
          r6(0): usages=0, flags=0    
          r6(1): usages=1, flags=2     KnVal
    
    
    Spesh slots:
        0 = STable (List)
        1 = Instance (Scalar)
        2 = Instance (Bool)
    
    Frame size: 126 bytes
    
    
    [Thread 0x7ffff633f700 (LWP 2632) exited]
    [Inferior 1 (process 2628) exited with code 01]
    (gdb)

**Comment by jnthn** [comment]
Fixed in `postrelease-opts` by 7ae914b6593270e7d1d.

**Comment by dogbert17** [comment]
This branch was merged with deba2e1fbf643b1c223, closing issue.
