### ISSUE TITLE
Functioning of our UTF16 encoding and endianess [request for discussion]

### ISSUE THREAD

**Issue by samcv** [MoarVM/MoarVM#966]
So currently writing a utf16 file will only write using the current machine's endianess. This is probably not a bug, but I just added the ability to write to utf16 files yesterday. Similar to how the current utf16 .encode and .decode work, basically if we are on a little endian or big endian machine it defaults to the machine order unless it sees a byte order mark.

This is more problematic when we are doing decodestream because we are not always at the start of the stream. Do we want to set some persistent flag if we see a BOM? What if the person seeks somewhere in the file before reading?

@jnthn what are your thoughts on this. I plan on adding support for explicit utf16le and utf16be as well. That solves many of these issues, though...

* If we see a byte order mark at the start of a file, we should remove it even on explicit mode
* But if we use decodestream, we may not be at the start of the file. Do we just remove any BOM we see anywhere in the file?

People's input is requested.

**Comment by Tux** [comment]
I think I expect perl6 to respect a BOM. Always (except when explicitly told not to). I spoke to others and all that cared about BOM's wish perl6 automatically deals with them at the beginning of a stream/file. Most had no idea that a BOM could also occur halfway a stream (as ZERO WIDTH NO-BREAK SPACE) so they have no idea what to do with them. Unicode says they can be ignored.
Yes, seeking is a problem.

**Comment by b2gills** [comment]
There is also the possibility that someone seeks past binary stuff to the start of a utf16 string. In that case they would want BOM treated as it would at the beginning of the file.

**Comment by samcv** [comment]
Going to close this since it's been implemented.

utf16le and utf16be will treat a BOM as a zero width no-break space, while utf16 will use the BOM to set the endianess and not pass it through.
