### ISSUE TITLE
Strongly bimodal performance on simple Perl 6 loop

### ISSUE THREAD

**Issue by japhb** [MoarVM/MoarVM#968]
See https://gist.github.com/japhb/eb81ecc106fb08ff2e08c9be0e988ed4 for examples of the behavior, where the same loop takes either 5.8 seconds or 42-45 seconds, seemingly on the flip of a coin.

Discussion and experimentation at http://colabti.org/irclogger/irclogger_log/perl6-dev?date=2018-09-20#l583 seems to indicate it is affected by both OSR and BLOCKING spesh control variables; turning off OSR or spesh in general makes it consistently slow, and setting BLOCKING makes it consistently fast.

**Comment by jnthn** [comment]
Fixed by https://github.com/MoarVM/MoarVM/commit/38915b934d6688af95b11ad115cf1fc925a2f2a1.
