### ISSUE TITLE
Unicode support falling behind?

### ISSUE THREAD

**Issue by lizmat** [MoarVM/MoarVM#974]
http://www.unicode.org/versions/Unicode11.0.0/ shows it being at 11.0.  Whereas MoarVM now is at 9.0 ?

**Comment by MasterDuke17** [comment]
I think it's at 10.0, based on this comment `# The UAXes can be accessed at http://www.unicode.org/versions/Unicode10.0.0/` in my unicode.c.

**Comment by jnthn** [comment]
Pretty sure we're at 10, and I *think* that one was an involved upgrade because the segmentation rules changed (affecting some details of how NFG works). They appear to have changed yet again in Unicode 11, alas, so at least in that respect it's not a simple case of "just run a script".

**Comment by samcv** [comment]
Going to close this ticket as I've since updated the Unicode database :)
