### ISSUE TITLE
SEGV when running spectest with MVM_SPESH_NODELAY=1 and MVM_SPESH_BLOCKING=1

### ISSUE THREAD

**Issue by dogbert17** [MoarVM/MoarVM#975]
A SEGV has been uncovered in https://github.com/perl6/roast/blob/master/S03-operators/inplace.t

Steps to repro:

    dogbert@dogbert-VirtualBox ~/repos/rakudo $ MVM_JIT_DISABLE=1 MVM_SPESH_NODELAY=1 MVM_SPESH_BLOCKING=1 ./perl6-gdb-m t/spec/S03-operators/inplace.rakudo.moar
    ================================================================================================
    This is Rakudo Perl 6 running in the GNU debugger, which often allows the user to generate useful back-
    traces to debug or report issues in Rakudo, the MoarVM backend or the currently running code.
    
    This Rakudo version is 2018.09.63.g.56.f.76.ed built on MoarVM version 2018.09.98.g.67.f.85.dc,
    running on linuxmint (18.3.Sylvia) / linux (4.10.0.38.generic)
    
    Type `bt full` to generate a backtrace if applicable, type `q` to quit or `help` for help.
    ------------------------------------------------------------------------------------------------
    Reading symbols from /home/dogbert/repos/rakudo/nqp/MoarVM/../../install/bin/moar...done.
    Starting program: /home/dogbert/repos/rakudo/install/bin/moar --execname=./perl6-gdb-m --libpath=. --libpath=blib --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib /home/dogbert/repos/rakudo/perl6.moarvm --nqp-lib=blib t/spec/S03-operators/inplace.rakudo.moar
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
    [New Thread 0x7ffff6251700 (LWP 32261)]
    1..38
    ok 1 - .= runs with block
    ok 2 - inplace map [0]
    ok 3 - inplace map [1]
    
    [...]
    
    ok 37 - various weird cases of .= calls
        1..4
            1..2
            ok 1 - instantiated an object
            ok 2 - default type is Mu
        ok 1 - default type constraint
        ok 2 - basic type constraint
            1..4
    
    Thread 1 "moar" received signal SIGSEGV, Segmentation fault.
    0x00007ffff755af77 in MVM_frame_invoke (tc=0x604a60, static_frame=0x0, callsite=0x7ffff7cb0380 <typecheck_callsite>, args=0xa05ba8, outer=0x3e9e398, code_ref=0x38cf9b8, spesh_cand=0) at src/core/frame.c:391
    391	    if (static_frame->body.instrumentation_level != tc->instance->instrumentation_level) {
    (gdb) bt
    #0  0x00007ffff755af77 in MVM_frame_invoke (tc=0x604a60, static_frame=0x0, callsite=0x7ffff7cb0380 <typecheck_callsite>, args=0xa05ba8, outer=0x3e9e398, code_ref=0x38cf9b8, spesh_cand=0) at src/core/frame.c:391
    #1  0x00007ffff7550be9 in MVM_interp_run (tc=0x604a60, initial_invoke=0x7ffff76a314a <toplevel_initial_invoke>, invoke_data=0x6a04a8) at src/core/interp.c:5621
    #2  0x00007ffff76a32af in MVM_vm_run_file (instance=0x604010, filename=0x7fffffffe27a "/home/dogbert/repos/rakudo/perl6.moarvm") at src/moar.c:420
    #3  0x00000000004016e7 in main (argc=10, argv=0x7fffffffddb8) at src/main.c:300
    (gdb) info threads
      Id   Target Id         Frame 
    * 1    Thread 0x7ffff7fdb700 (LWP 32257) "moar" 0x00007ffff755af77 in MVM_frame_invoke (tc=0x604a60, static_frame=0x0, callsite=0x7ffff7cb0380 <typecheck_callsite>, args=0xa05ba8, outer=0x3e9e398, 
        code_ref=0x38cf9b8, spesh_cand=0) at src/core/frame.c:391
      2    Thread 0x7ffff6251700 (LWP 32261) "moar" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
    (gdb)

The parameter static_frame looks slightly suspicious being 0x0

Thanks to some wizardry from AlexDaniel++ the offending commit has been identified as https://github.com/rakudo/rakudo/commit/14fa3b696317c85ac8bd2cc6cc64c080451d4cbc

**Comment by AlexDaniel** [comment]
For further use with *ables: https://gist.github.com/AlexDaniel/72431f1657d1324d41d42dde6f87ff03

**Comment by jnthn** [comment]
Didn't get a SEGV, but...

```
$ MVM_SPESH_OSR_DISABLE=1 MVM_SPESH_INLINE_DISABLE=1 MVM_JIT_DISABLE=1 MVM_SPESH_NODELAY=1 MVM_SPESH_BLOCKING=1 ./perl6-m t/spec/S03-operators/inplace.t
1..38
ok 1 - .= runs with block
ok 2 - inplace map [0]
ok 3 - inplace map [1]
ok 4 - inplace map [2]
ok 5 - .= works without surrounding whitespace
ok 6 - inplace grep [0]
ok 7 - inplace grep [1]
ok 8 - inplace grep [2]
ok 9 - inplace int
No such method '' for invocant of type 'Str'. Did you mean any of these?
    IO
    fc
    kv
    lc

  in block <unit> at t/spec/S03-operators/inplace.t line 34

# Looks like you planned 38 tests, but ran 9
```

Nice that we can disable a ton of the more complex optimizations to get the problem.

**Comment by jnthn** [comment]
Oh, completely ignore what I just wrote. I didn't realize there was a fudged version of the test and *that* is what's needed for the SEGV. Now I get it.

**Comment by jnthn** [comment]
So, now I run the correct thing...SEGV with this:

```
$ MVM_SPESH_INLINE_DISABLE=1 MVM_JIT_DISABLE=1 MVM_SPESH_NODELAY=1 MVM_SPESH_BLOCKING=1 ./perl6-m t/spec/S03-operators/inplace.rakudo.moar
```

Not with this:

```
MVM_SPESH_OSR_DISABLE=1 MVM_SPESH_INLINE_DISABLE=1 MVM_JIT_DISABLE=1 MVM_SPESH_NODELAY=1 MVM_SPESH_BLOCKING=1 ./perl6-m t/spec/S03-operators/inplace.rakudo.moar
```

So it's related to OSR.

**Comment by jnthn** [comment]
Fixed with https://github.com/MoarVM/MoarVM/commit/ecbc1295ae
