### ISSUE TITLE
Clang warnings

### ISSUE THREAD

**Issue by bbkr** [MoarVM/MoarVM#98]
Latest clang compiler throws about 500 warnings during compilation process:

http://pastebin.com/6yQTkhyV

```
$ clang --version
Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin13.1.0
Thread model: posix
```

**Comment by jnthn** [comment]
It's now clean of warnings under:

    Debian clang version 3.5.0-1~exp1 (trunk) (based on LLVM 3.5.0)
    Target: x86_64-pc-linux-gnu
    Thread model: posix
