### ISSUE TITLE
Error!!!

### ISSUE THREAD

**Issue by slava8686** [MoarVM/MoarVM#995]
src/math/bigintops.c: In function 'MVM_bigint_rand':
src/math/bigintops.c:1166:13: error: 'MP_GEN_RANDOM_MAX' undeclared (first use in this function)
         if (MP_GEN_RANDOM_MAX >= abs(smallint_max)) {
             ^
src/math/bigintops.c:1166:13: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:645: src/math/bigintops.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by samcv** [comment]
Can you give some information on your operating system and OS version?

**Comment by niner** [comment]
Pretty sure this was fixed in commit eccbc8541be2ba527cc47963ffccccf5e7540a41, cf https://github.com/libtom/libtommath/issues/122
