### ISSUE TITLE
SEGV when running example code from R#1951

### ISSUE THREAD

**Issue by dogbert17** [MoarVM/MoarVM#996]
I managed to golf it down a bit to 

    my $foo;
    
    my %subs := {
        'hash'     => sub { $foo = hash a => "b" },
        '{}'       => sub { $foo = { a => "b" } },
        'my %'     => sub { $foo = my % = a => "b"},
        'my %x ='  => sub { my %x = a => "b"; $foo = %x },
    };
    
    for %subs.kv -> $k, $v {
        $v() for ^200000;
    };

Note that it does not fail every time but often enough. Another thing is that the problem seems to disappear if the code is run with MVM_SPESH_INLINE_DISABLE=1.

running the above code in gdb gives the following:

    dogbert@dogbert-VirtualBox ~/repos/rakudo $ ./perl6-gdb-m segv.pl6 
    ================================================================================================
    This is Rakudo Perl 6 running in the GNU debugger, which often allows the user to generate useful back-
    traces to debug or report issues in Rakudo, the MoarVM backend or the currently running code.
    
    This Rakudo version is 2018.10.129.g.80.edefc built on MoarVM version 2018.10.77.g.6236.eb.5,
    running on linuxmint (18.3.Sylvia) / linux (4.10.0.38.generic)
    
    Type `bt full` to generate a backtrace if applicable, type `q` to quit or `help` for help.
    ------------------------------------------------------------------------------------------------
    Reading symbols from /home/dogbert/repos/rakudo/nqp/MoarVM/../../install/bin/moar...done.
    Starting program: /home/dogbert/repos/rakudo/install/bin/moar --execname=./perl6-gdb-m --libpath=. --libpath=blib --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib --libpath=/home/dogbert/repos/rakudo/install/share/nqp/lib /home/dogbert/repos/rakudo/perl6.moarvm --nqp-lib=blib segv.pl6
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
    [New Thread 0x7ffff6239700 (LWP 7255)]
    
    Thread 2 "moar" received signal SIGSEGV, Segmentation fault.
    [Switching to Thread 0x7ffff6239700 (LWP 7255)]
    0x00007ffff75cc0ae in MVM_multi_cache_find_spesh (tc=0x68eae0, cache_obj=0x7ffff3347368, arg_info=0x7ffff6237450, type_tuple=0x7fffec207590) at src/6model/reprs/MVMMultiCache.c:501
    501	                known_type_st = type_tuple[tt_offset].type->st;
    (gdb) bt
    #0  0x00007ffff75cc0ae in MVM_multi_cache_find_spesh (tc=0x68eae0, cache_obj=0x7ffff3347368, arg_info=0x7ffff6237450, type_tuple=0x7fffec207590) at src/6model/reprs/MVMMultiCache.c:501
    #1  0x00007ffff7619ffa in optimize_call (tc=0x68eae0, g=0x7fffec003440, bb=0x7fffec66cc28, ins=0x7fffec66c3f8, p=0x7fffec3a7770, callee_idx=1, arg_info=0x7ffff6237450) at src/spesh/optimize.c:1857
    #2  0x00007ffff761cbcd in optimize_bb_switch (tc=0x68eae0, g=0x7fffec003440, bb=0x7fffec66cc28, p=0x7fffec3a7770) at src/spesh/optimize.c:2670
    #3  0x00007ffff761d3d1 in optimize_bb (tc=0x68eae0, g=0x7fffec003440, bb=0x7fffec66cc28, p=0x7fffec3a7770) at src/spesh/optimize.c:2918
    #4  0x00007ffff761d434 in optimize_bb (tc=0x68eae0, g=0x7fffec003440, bb=0x7fffec66cbc8, p=0x7fffec3a7770) at src/spesh/optimize.c:2930
    #5  0x00007ffff761d434 in optimize_bb (tc=0x68eae0, g=0x7fffec003440, bb=0x7fffec66cb08, p=0x7fffec3a7770) at src/spesh/optimize.c:2930
    #6  0x00007ffff761e7ba in MVM_spesh_optimize (tc=0x68eae0, g=0x7fffec003440, p=0x7fffec3a7770) at src/spesh/optimize.c:3296
    #7  0x00007ffff760a343 in MVM_spesh_candidate_add (tc=0x68eae0, p=0x7fffec3a7770) at src/spesh/candidate.c:81
    #8  0x00007ffff762736d in worker (tc=0x68eae0, callsite=0x7ffff7dd5540 <null_args_callsite>, args=0x0) at src/spesh/worker.c:16
    #9  0x00007ffff75ad783 in invoke_handler (tc=0x68eae0, invokee=0x682170, callsite=0x7ffff7dd5540 <null_args_callsite>, args=0x0) at src/6model/reprs/MVMCFunction.c:9
    #10 0x00007ffff75537ac in thread_initial_invoke (tc=0x68eae0, data=0x68fe50) at src/core/threads.c:59
    #11 0x00007ffff7512b55 in MVM_interp_run (tc=0x68eae0, initial_invoke=0x7ffff7553721 <thread_initial_invoke>, invoke_data=0x68fe50) at src/core/interp.c:110
    #12 0x00007ffff755386a in start_thread (data=0x68fe50) at src/core/threads.c:87
    #13 0x00007ffff6a4e6ba in start_thread (arg=0x7ffff6239700) at pthread_create.c:333
    #14 0x00007ffff707441d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
    (gdb) info threads
      Id   Target Id         Frame 
      1    Thread 0x7ffff7fdb700 (LWP 7251) "moar" 0x00007ffff75e4587 in MVM_6model_find_method (tc=0x604a50, obj=0x7ffff34d4c18, name=0x33f5960, res=0x74a540, throw_if_not_found=1) at src/6model/6model.c:166
    * 2    Thread 0x7ffff6239700 (LWP 7255) "moar" 0x00007ffff75cc0ae in MVM_multi_cache_find_spesh (tc=0x68eae0, cache_obj=0x7ffff3347368, arg_info=0x7ffff6237450, type_tuple=0x7fffec207590)
        at src/6model/reprs/MVMMultiCache.c:501
    (gdb) p type_tuple[tt_offset].type->st
    Cannot access memory at address 0x35
    (gdb) p tt_offset
    $1 = 1
    (gdb) p type_tuple[tt_offset]
    $2 = {type = 0x25, decont_type = 0x0, type_concrete = 0 '\000', decont_type_concrete = 0 '\000', rw_cont = 0 '\000'}

**Comment by AlexDaniel** [comment]
Bisected to: (2018-09-25) https://github.com/rakudo/rakudo/commit/ace87cb5d99c4a80b6d093cd92c73d5b952f1093


In case somebody needs it later:
```
<+AlexDaniel> bisect: for ^10 { exit 42 if run(<perl6 -e>, ｢sub f1 { hash a=>1 }; sub f2 { hash b=>2 }; sub f3 { hash c=>3 }; f1 for ^10000; f2 for ^10000; f3 for ^10000｣).signal != 0 }
<bisectable6> AlexDaniel, Bisecting by exit code (old=2015.12 new=534d8f6). Old exit code: 0
<bisectable6> AlexDaniel, bisect log: https://gist.github.com/cfe99f2eebc7aeaa593ababdd540041b
<bisectable6> AlexDaniel, (2018-09-25) https://github.com/rakudo/rakudo/commit/ace87cb5d99c4a80b6d093cd92c73d5b952f1093
```

And to confirm:
```
<+AlexDaniel> c: ace87cb5d9^,ace87cb5d9 for ^10 { say run(<perl6 -e>, ｢sub f1 { hash a=>1 }; sub f2 { hash b=>2 }; sub f3 { hash c=>3 }; f1 for ^10000; f2 for ^10000; f3 for ^10000｣).signal }
<committable6> AlexDaniel, ¦ace87cb5d9^: «0␤0␤0␤0␤0␤0␤0␤0␤0␤0␤» ¦ace87cb: «11␤11␤11␤0␤0␤11␤11␤0␤0␤0␤»
```

**Comment by AlexDaniel** [comment]
FWIW this is still not resolved.
